### ISSUE TITLE
Local schemaPath graphql file not being re-read on regeneration if the path contains relative references

### ISSUE THREAD

**Issue by fnimick** [HoudiniGraphql/houdini#1002]
### Describe the bug

Right now, a local schema file provided via `config.schemaPath` which contains `../` is read only once at Houdini startup, and then when queries are edited, it is not updated.

This is likely due to the file path comparison in https://github.com/HoudiniGraphql/houdini/blob/2c7daa48f4adc16de5bea88d8b93db335ba24972/packages/houdini/src/vite/index.ts#L34

My resolved schemaPath is e.g. `/path/to/repository/@app/client/../../data/schema.graphql`, where the absolute filePath is `/path/to/repository/data/schema.graphql`.

### Severity

annoyance

### Steps to Reproduce the Bug

Add a relative path such as `../dir/schema.graphql` to your schemaPath, then update it and observe that your runtime is not regenerated as expected.

**Comment by fnimick** [comment]
Added logging to this point in the code and it's not the result of the relative path - in my setup, `schemaPath` isn't being watched at all:

```
➜  git:(sveltekit-admin) ✗ yarn client dev

<repository>/@app/client/$houdini/runtime/generated.d.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/runtime/generated.d.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/plugins/houdini-svelte/runtime/fragments.d.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/plugins/houdini-svelte/runtime/fragments.d.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/runtime/index.d.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/runtime/index.d.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/runtime/generated.d.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/plugins/houdini-svelte/runtime/fragments.d.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/types/src/routes/(app)/(require-unauth)/forgot/proxy+page.server.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/types/src/routes/(app)/(require-unauth)/login/email/proxy+page.server.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/types/src/routes/(app)/(require-unauth)/register/proxy+page.server.ts
<repository>/data/schema.graphql
<repository>/@app/client/$houdini/types/src/routes/(app)/(require-unauth)/reset/proxy+page.server.ts
<repository>/data/schema.graphql
🎩 Generating runtime...
📃 Unchanged: 31
```

**Comment by AlecAivazis** [comment]
Hey @fnimick! Sorry to hear you're running into this.

I'll find some time this weekend to look into it. The e2e tests have `..` in them so it should be easy to reproduce

**Comment by fnimick** [comment]
@AlecAivazis please don't worry about this yet - @jycouet has a strong hypothesis that I haven't had a chance to test, which is that a schema file located outside the Vite project directory won't be watched at all. Not sure if that would be considered a bug or not?

**Comment by AlecAivazis** [comment]
I'm going to close this since its gone a bit stale. Happy to reopen it once we know it's not a vite issue
