### ISSUE TITLE
Inconsistency between SSR and CSR

### ISSUE THREAD

**Issue by devunt** [HoudiniGraphql/houdini#1009]
### Describe the bug

I'm experiencing inconsistency between SSR and CSR result in following codes

```
// src/client.ts

import { HoudiniClient } from '$houdini';

export default new HoudiniClient({
  url: 'https://non.exists.url',
});
```
```
// src/routes/+page.gql

query Test {
  test
}
```

```
// src/routes/+page.svelte
<script lang="ts">
  import type { PageData } from './$houdini';

  export let data: PageData;

  $: ({ Test } = data);
</script>

<code>{$Test.fetching}</code>
<a href='/'>Force client-render</a>
```

It shows `500: Internal Error` in the initial load (SSR), but it shows `true` in the subsequent navigations.
No errors have been logged to the console, just indefinite fetching status.

Is this a bug or expected behavior?

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

Described above

**Comment by AlecAivazis** [comment]
Closing in favor of: https://discord.com/channels/1024421016405016718/1087829401825185812
