### ISSUE TITLE
Add `@blocking` directive and config

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#1013]
### Describe the feature

Many users have been asking for a way to set `blocking` to `true` globally for their application. We should provide configuration values to set a default behavior as well as directives (ie `@blocking`) for configuring the behavior when relying on a generated load function.

### Criticality

cool improvement, my projects will benefit from it

**Comment by jycouet** [comment]
Reminder: 
- [ ] if throwOnError includes all or query, blocking needs to be true
- [ ] add in config: default blocking strategy
- [ ] add directives `@blocking` `@blocking_false`
- [ ] add a warning if a config is "wrong"
  - [ ] having a throwOnError(all|query) & default blocking is set to false
  - [ ] Just document that `@blocking_false` will never throwOnError
- [ ] update doc query/manual-loading/last chapter about load & result section
