### ISSUE TITLE
houdini executable not found (Windows 10, NVM)

### ISSUE THREAD

**Issue by radio-miskovice** [HoudiniGraphql/houdini#1026]
### Describe the bug

When coding Sveltekit project using Houdini, I noticed $houdini directory did not exist. After diving deeper into the problem I discovered that when I try to call
`houdini generate`
I get error message `'houdini' is not recognized as an internal or external command, operable program or batch file.`
And so I am stuck :(
Windows 10
nodejs 18.15.0
npm 9.5.0
houdini@1.1.3
houdini-svelte@1.1.3
@sveltejs/kit@1.14.0

### Severity

blocking usage of Houdini, but found a workaround (adding .\node_modules\.bin to PATH)

### Steps to Reproduce the Bug

1. In VS Code Open terminal (CMD.EXE)
2. type houdini generate
or do the same in command window

**Comment by jycouet** [comment]
`houdini generate` should happen automatically when you run `npm run dev`. (You shouldn't need to "generate" by hand.)

Let us know

**Comment by radio-miskovice** [comment]
> `houdini generate` should happen automatically when you run `npm run dev`. (You shouldn't need to "generate" by hand.)
> 
> Let us know

Oh, sorry, I started it manually before seeing your comment.
In this case, it is merely a sort-of discomfort. That is because syntax checking complains about missing things that are supposed to be imported from `$houdini`. However, usually I first write some code and then `npm run dev` so in this case, since nothing was generated yet, there was this kind of problem.
Not sure what to do next. Once something has been generated, there is no issue :-D
