### ISSUE TITLE
Svelte not working (not sveltekit)

### ISSUE THREAD

**Issue by tofsjonas** [HoudiniGraphql/houdini#1029]
### Describe the bug

Install seems to work fine, npm run dev works, but both vscode and the browser complains that:
> Property 'init' does not exist on type 'HoudiniClient'.ts(2339)

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

<img width="1256" alt="Skärmavbild 2023-03-30 kl  19 09 31" src="https://user-images.githubusercontent.com/1842179/228916381-1ed3f963-9c03-4eb9-a997-60c306714808.png">
<img width="516" alt="Skärmavbild 2023-03-30 kl  19 17 09" src="https://user-images.githubusercontent.com/1842179/228916433-7733c102-af0a-4c73-9395-d56809fd69d4.png">
<img width="984" alt="Skärmavbild 2023-03-30 kl  19 17 50" src="https://user-images.githubusercontent.com/1842179/228916461-bd9712fb-f224-4be4-b101-e30efa9eb669.png">

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rcvfuc?file=index.html

**Comment by AlecAivazis** [comment]
Oh I think this is a bug in the files that `init` creates. You should be able to just delete that line. I've opened up #1032 to clean up the starter project 👍

**Comment by tofsjonas** [comment]
It works, thank you! 🙏🌷

**Comment by tofsjonas** [comment]
Well, maybe "works" is a bit strong. I don't get THAT error anymore.

Don't know if it's Is it a Svelte/Sveltekit issue, but now, when I copy the code from <https://houdinigraphql.com/> 

```javascript
<script lang ”ts”>
  import { graphql } from "$houdini";

  const allItems = graphql(`
    query AllTodoItems @load {
      items {
        text
      }
    }
  `);
</script>

{#each $allItems.data.items as item}
  <div>{item.text}</div>
{/each}

```
I get: 

<img width="881" alt="Skärmavbild 2023-03-31 kl  10 14 53" src="https://user-images.githubusercontent.com/1842179/229064705-cc5d012e-1dda-43b8-88cb-c606d710111b.png">
😢

**Comment by AlecAivazis** [comment]
Do you have the vite dev server running? that error means your queries haven't been processed by houdini yet

**Comment by tofsjonas** [comment]
Thank you for your speedy replies! 😊

**Comment by AlecAivazis** [comment]
Are there any other error messages printed above that error? For some reason your runtime's not being generated

**Comment by tofsjonas** [comment]
Aha,

It had to be a "real" query. I figured I'd just copy the example and see what happened. Makes sense. This works:

```html
<script lang="ts">
  import { graphql } from "$houdini";

  const allItems = graphql(`
    query getCurrencies @load {
      currencies {
        name
      }
    }
  `);
</script>

{#if $allItems.data}
  {#each $allItems.data.currencies as item}
    <div>{item.name}</div>
  {/each}
{/if}
```

**Comment by tofsjonas** [comment]
Thank you again!

**Comment by tofsjonas** [comment]
Do I have to type the result manually?

`allItems` is typed as `const allItems: getCurrenciesStore`, which made me think that it would be typed automagically, but `$allItems` is typed as `let $allItems: QueryResult<_Data, _Input>`, so `$allItems.data` becomes `any`
