### ISSUE TITLE
Errors when using `nodenext`, `node16`, or `bundler` moduleResolution in tsconfig.json

### ISSUE THREAD

**Issue by mpellegrini** [HoudiniGraphql/houdini#1046]
### Describe the bug

when using the newer TypeScript moduleResolution options `nodenext`, `node16`, or `bundler` (avail in TS 5), can resolve type declaration files. Getting the following error in `vite.config.ts` when I change the tsconfig.json moduleResolution to one of the previous mentioned options.

` Error: Could not find a declaration file for module 'houdini/vite'.`

This is because the `exports` in package.json does not explicitly definite the `types` conditional export and falls back to the default location which doesn't exist.

This is how the `exports` section is define currently in package.json

```
"exports": {
    "./package.json": "./package.json",
    "./codegen": {
      "import": "./build/codegen-esm/index.js",
      "require": "./build/codegen-cjs/index.js"
    },
    ".": {
      "import": "./build/lib-esm/index.js",
      "require": "./build/lib-cjs/index.js"
    },
    "./test": {
      "import": "./build/test-esm/index.js",
      "require": "./build/test-cjs/index.js"
    },
    "./vite": {
      "import": "./build/vite-esm/index.js",
      "require": "./build/vite-cjs/index.js"
    }
  },
```

But because there is no explicit `types` export, ts will look for the type definition name `./build/vite-esm/index.d.ts` which doesn't exist.  it looks like you were trying to do this with the `typesVersion` section but TS only looks at `exports` when the moduleResolution is `nodenext`, `node16`, or `bundler`. 

The correct way would be to define it as follows:

```
"exports": {
    "./package.json": "./package.json",
    "./codegen": {
      "types": "./build/codegen/index.d.ts",
      "import": "./build/codegen-esm/index.js",
      "require": "./build/codegen-cjs/index.js"
    },
    ".": {
      "types": "./build/lib/index.d.ts"
      "import": "./build/lib-esm/index.js",
      "require": "./build/lib-cjs/index.js"
    },
    "./test": {
      "types": "./build/test/index.d.ts",
      "import": "./build/test-esm/index.js",
      "require": "./build/test-cjs/index.js"
    },
    "./vite": {
      "types": "./build/vite/index.d.ts",
      "import": "./build/vite-esm/index.js",
      "require": "./build/vite-cjs/index.js"
    }
  },
```

I have patched via pnpm patch using the above changes and all is good with the project again. But would be ideal to get this into the codebase.  Happy to push up a PR if that would be preferred.

### Severity

annoyance

### Steps to Reproduce the Bug

1. Edit tsconfig.json - add `"moduleResoultion": "bundler"` under `compilerOptions`
2. Open up vite.config.ts - should notice that the `import houdini from 'houdini/vite'` is show in error

```
TS7016: Could not find a declaration file for module 'houdini/vite'. '.../node_modules/.pnpm/houdini@1.1.7/node_modules/houdini/build/vite-esm/index.js' implicitly has an 'any' type.   There are types at '.../node_modules/houdini/build/vite/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'houdini' library may need to update its package.json or typings.
```

**Comment by AlecAivazis** [comment]
Ah nice catch!! All of that configuration is managed by this script: https://github.com/HoudiniGraphql/houdini/blob/main/packages/_scripts/build.js

You'll see its really convention-driven but hopefully you can figure out the best way to add what's necessary. Let me know if you need any other guidance!

**Comment by mpellegrini** [comment]
Thanks @AlecAivazis for the pointer to the build.js file. Definitely a simple fix that I can make.  Seeing that changing the moduleResolution can have a significant impact on the code, even more so since this project is on TS 4.9 without support for  the new 'bundler' option, I am thinking there is not a lot to do on the e2e tests or any test coverage on this.  But I would welcome any thoughts / input on this prior to pushing a PR.

Thanks,
Mike
