### ISSUE TITLE
Houdini reports an error when import asseertion is used in the code

### ISSUE THREAD

**Issue by devunt** [HoudiniGraphql/houdini#1047]
### Describe the bug

Houdini reports an error when import assertion is used in the code, even in the totally not related code.
I suspect there's an annoying bug with AST parser.

### Severity

annoyance

### Steps to Reproduce the Bug

1. Create `src/lib/test.json` file with `{}` as its only contents (contents here really doesn't matter)
2. Create `src/lib/test.ts` file with following code and save it.
    ```typescript
    import obj from './test.json' assert { type: 'json' };
    ```
3. Vite dev server throws `❌ Encountered error in src/lib/test.ts`, even if `test.ts` is used in nowhere and `obj` is also not used.

**Comment by AlecAivazis** [comment]
Ugh yea you're probably right.

Here is where that code lives if you have time to hunt down the necessary configuration: https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini/src/lib/parse.ts
