### ISSUE TITLE
latest sveltekit breaks houdini

### ISSUE THREAD

**Issue by xmlking** [HoudiniGraphql/houdini#1054]
### Describe the bug

after upgrading `sveltejs/kit` from   "1.15.0" to "1.15.5" server fail starting with following error:
> Multiple universal layout module files found in src/routes/ : +layout.js and +layout.js

the error will go away if I comment `houdini()` plugin in `vite.config.ts`

<img width="856" alt="image" src="https://user-images.githubusercontent.com/627951/232332868-a5a6c98b-2507-4f48-a94c-d1836ae0bb97.png">

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

https://github.com/xmlking/svelte-starter-kit
updated svelte/kit to latest in package.json

error can be reproduced if you comment/uncomment  `houdini()` plugin in `vite.config.ts`

### Reproduction

https://github.com/xmlking/svelte-starter-kit

**Comment by AlecAivazis** [comment]
Yea we ran into this and it has been fixed in #1053. It'll be released in `1.2` which is going out tonight 👍
