### ISSUE TITLE
Making `data` non-nullable if `throwOnError` is configured

### ISSUE THREAD

**Issue by devunt** [HoudiniGraphql/houdini#1055]
### Describe the feature

As it is safe to make assumption that `data` will not be null if `throwOnError` is ever configured, it would beneficial to make it non-nullable to get rid of `{#if data}`s and non-null assertions `!` everywhere.

To accomplish this:
* Move `throwOnError` into `houdini.config.js`, since it will affect on code generation.
* Alter `QueryResult` generic to conditionally apply nullability based on the configuration.
* Make runtime to throw accordingly if `throwOnError` is configured in `houdini.config.js`.

Questions:
* Should `errors` field's type be `never` if `throwOnError` is configured?
* How can we introduce this feature without making breaking change?

### Criticality

cool improvement, my projects will benefit from it

**Comment by AlecAivazis** [comment]
So `data` is also `null` when the query is fetching so we cant make the change as things are now. That being said, once #1043 goes in we can start to move in this direction (it's on my list of stuff to do in that PR). 

I'm also not really sure how to support it without a breaking change. Worst case scenario, we ca wait til we have more reasons for 2.0 and include this then.

**Comment by AlecAivazis** [comment]
Thinking this this a bit, I'm not sure it's a good move idea to move this to the codegen portion. The error behavior should be able to be environment specific (ie in production errors might act differently than in local dev). I agree it would be a lot better if it was possible but for now I'm not sure there's a way. More than happy to reopen this issue if we come up with something.
