### ISSUE TITLE
Houdini Plugin Conflicting with latest SvelteKit

### ISSUE THREAD

**Issue by maxzeroedge** [HoudiniGraphql/houdini#1060]
### Describe the bug

Trying to build application with latest sveltekit gives 
`Multiple universal layout module files found in src/routes/ : +layout.js and +layout.js`

Apparently, there is some problem with the houdini plugin and latest @sveltejs/kit (worked fine in 1.15.0, but fails in 1.15.5+)
Removing houdini() from plugins in vite.config lets the build succeed.

Using the houdini plugin is apparently creating a new +layout.*, which is conflicting with the existing +layout.* of the user

It seems related to this PR (https://github.com/sveltejs/kit/pull/9590) 

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

1. Create new Svelte kit project
2. Add Houdini to it
3. Run the project

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-jjttza

**Comment by AlecAivazis** [comment]
Thanks for reporting this @maxzeroedge! This has been fixed in 1.2 which should be released very soon. If you have time to test the release candidate, that would be super helpful. You can grab it with the `@next` tag.

**Comment by AlecAivazis** [comment]
`1.2.0` is out! Thanks for the patience 👍
