### ISSUE TITLE
Couldn't pull your latest schema: request failed, reason: Socket connection timeout

### ISSUE THREAD

**Issue by xmlking** [HoudiniGraphql/houdini#1077]
### Describe the bug

I am noticing random  `Couldn't pull your latest schema` when I start dev server.
is this any race condition and timeout issue?
 
`Couldn't pull your latest schema: request to https://xxx/v1/graphql failed, reason: Socket connection timeout`
<img width="1389" alt="Screenshot 2023-04-29 at 9 44 26 AM" src="https://user-images.githubusercontent.com/627951/235314137-7fdb051b-4d50-4269-af3c-444096476c8b.png">

### Severity

annoyance

### Steps to Reproduce the Bug

https://github.com/xmlking/svelte-starter-kit

### Reproduction

https://github.com/xmlking/svelte-starter-kit

**Comment by jycouet** [comment]
Is it happening randomly? Sometimes it's working, and sometimes you have this message?

I see that you have configured `watchSchema.interval: 0`.  Ok.
Here is the code for pulling:
https://github.com/HoudiniGraphql/houdini/blob/c1363fe938ab94281272cad8939b892fd705a803/packages/houdini/src/lib/introspection.ts

Can you put a number to interval to have 5 sec or 10 sec and see if it's failing from time to time?

**Comment by xmlking** [comment]
it was random (20% times when I start with `pnpn dev`)
I don't see any other logs, watching for 5 min.
<img width="625" alt="image" src="https://user-images.githubusercontent.com/627951/235315608-e6c5ed2f-1b21-4fb2-82a2-8f2c9f1da0b6.png">

**Comment by jycouet** [comment]
`internal` is in `ms`. You should put 5000 for 5 seconds.

Could it be that you have a "cold start" on the first hit asking for introspection?

**Comment by xmlking** [comment]
changed, I see  `Socket connection timeout` in a couple of repos i am working on (each using different hosted hasura API backends) 
5 ` failed, reason: Socket connection timeout` 
3 `failed, reason: read ETIMEDOUT` 
<img width="618" alt="image" src="https://user-images.githubusercontent.com/627951/235316277-0da70acf-28cc-4f47-bf35-ad12abdf2410.png">

**Comment by xmlking** [comment]
I am using node 20

**Comment by jycouet** [comment]
I'll probably create an account there to have a look. 👀

**Comment by jycouet** [comment]
👋 @xmlking 
Do you have any updates on this ticket?

**Comment by xmlking** [comment]
Now it seams like working. Not sure what fixed it :(
