### ISSUE TITLE
Typescript moduleResolution node16 or nodenext break typings resolution

### ISSUE THREAD

**Issue by haleksandre** [HoudiniGraphql/houdini#1079]
### Describe the bug

Setting the `compilerOptions.moduleResolution` to either `node16` or `nodenext` break the typings resolution of Houdini. The reason is that when this option is set to those, you require to add the file extensions to the import statements, which the generated `$houdini` directory does not.  

The application still seems to work fine (dev & build), but you will get annoying typing issues like below.
```ts
import { graphql } from '$houdini'
/* 
  Relative import paths need explicit file extensions in EcmaScript 
  imports when '--moduleResolution' is 'node16' or 'nodenext'. 
  Consider adding an extension to the import path.ts(2834)
*/

//or

import { graphql } from '$houdini/index.js'
/*
Module '"$houdini/index.js"' has no exported member 'graphql'.ts(2305)
*/
```

Could it be possible to make an option, which once enabled, would make the generated code appends the extension on the generated import statements? 

[typesafe-i18n](https://github.com/ivanhofer/typesafe-i18n) had similar issues & already fixed this via an option [`esmImport`](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/generator#esmimports) so it could be something to look into.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. git clone https://github.com/HoudiniGraphql/example-sveltekit-todo.git
2. add `compilerOptions.moduleResolution: nodenext` to `tsconfig.json`
3. open any file which import `$houdini` in vscode

**Comment by AlecAivazis** [comment]
I'd be curious to see if there's any downside to having the extensions always present and avoiding the extra config. If you have some time to give it a shot and update the imports in the runtime directory I would really appreciate it.

**Comment by AlecAivazis** [comment]
I'm closing this issue since its gone a bit stale. feel free to let me know if you want to keep exploring options here
