### ISSUE TITLE
get the clean data types without the fragment types

### ISSUE THREAD

**Issue by macmillen** [HoudiniGraphql/houdini#1110]
### Describe the feature

I want to create mocked data to test my svelte components with houdini fragments inside with a mocked service worker. For that I need the pure graphql types of the query without the `$fragments` keys.

I can achieve that with some really ugly type acrobatics:
``` ts
type DashboardPayload = CleanseHoundini<
  Omit<Dashboard$result["dashboard"], "tiles"> & {
    tiles: (Omit<Dashboard$result["dashboard"]["tiles"][number], "widget"> & {
      widget: Widget$data;
    })[];
  },
  "Dashboard"
>;

export const baseDashboard: DashboardPayload = {
  __typename: "Dashboard",
  tiles: [{ widget: { id: "expected_visitor_count", ... } }],
};
```

the qgraphql query in +page.gql:
``` gql
query Dashboard {
  dashboard {
    tiles {
      id
      position
      size
      widget {
        ...Widget
      }
    }
  }
}
```

the fragment inside the svelte component:
``` svelte
  $: widget = fragment(
    _widget,
    graphql(`
      fragment Widget on DashboardWidget {
        id
        timeSpan
        dataType
        data {
          ... on DashboardDataIntValue {
            prevValue
            value
          }
          ... on DashboardDataMoneyValue {
            prevMoneyValue: prevValue
            moneyValue: value
          }
          ... on Error {
            key
            messages
          }
        }
      }
    `)
  );
```

But that's really a bad dev experience.

Proposed solution
- either output the types like `XYZ$pure`
- or create a type helper to cleanse the types like `Purify<XYZ>`

### Criticality

cool improvement, my projects will benefit from it

**Comment by AlecAivazis** [comment]
👋  Hey @macmillen!

There are already `$data` types exported for each fragment that contain just the shape of the fragment - does that work?

**Comment by macmillen** [comment]
hey @AlecAivazis i'm already using these as you can see in the example code (Widget$data). the thing is that i want to have the pure parent type with the fragments being the $data types without me having to do these crazy type acrobatics

**Comment by AlecAivazis** [comment]
Ah! I understand now. Sorry for not reading your message more carefully.

I think I am in favor of your second option to create a type helper. Would you be willing to submit a PR that adds a `FlattenSelection` utility type that does exactly that?

**Comment by macmillen** [comment]
let's say we want to transform this type:

``` ts
export type MyDashboard$result = {
    readonly dashboard: {
        readonly tiles: ({
            readonly id: string;
            readonly widget: {
                readonly " $fragments": {
                    Widget: {};
                };
            };
        })[];
    };
};
```

into this:

``` ts
export type MyDashboard$result = {
    readonly dashboard: {
        readonly tiles: ({
            readonly id: string;
            readonly widget: Widget$data;
        })[];
    };
};
```

actually i don't think it's possible to create a type helper because in this example it would need to be aware of the `Widget$data` to replace the `widget` fragment type with `Widget$data`. i'm not sure but i think the only solution is to generate the types

**Comment by AlecAivazis** [comment]
I _think_ we could pull it off by generating a type that maps those strings to the `$data` types and then index it in the helper using the string in the ` $fragments` key. That being said, i'm not sure its worth the effort: using `MyQuery$whatever` is pretty much the same as `Whatever<MyQuery>` and the codebase already has all of the logic to generate the definition. 

I'm good with whichever option you prefer

**Comment by macmillen** [comment]
I think the type generation would be easier than writing the type helper but i don't think i am able to write a PR for that unfortunately

**Comment by V-ed** [comment]
A thousand times this - currently, fragments are literally not usable in my codebase because the types are messed up.

<table>
<tr>
 <td>Types generated
 <td>Values provided
<tr>
 <td><img src="https://github.com/HoudiniGraphql/houdini/assets/16652915/6862eb50-8b14-44b5-b8ea-e3ac5ea3b6fe">
 <td><img src="https://github.com/HoudiniGraphql/houdini/assets/16652915/82b7ee86-12b3-4780-a88e-f9c9ac044b4c">
</table>

I'm okay with extending the type with a `" $fragments"` key, but at least add the fragment data to the returned type, as currently, in my example, `sessionUser` has no keys in typescript, yet all the data is there in the actual javascript object.

---

I do have to say that I don't use the stores as "usual" per se, as I mainly use the client as [server only loads](https://houdinigraphql.com/api/query#server-only-load). Therefore, my problem is similar in that I would need to use convoluted type acrobatics just to get the data structure, which is what I would have hoped _not_ to do using this library.

**Comment by AlecAivazis** [comment]
I'm going to close this since its gone stale and its not the recommended pattern for Houdini. If someone runs into this issue and wants to add it, ill happily provide whatever guidance they want
