### ISSUE TITLE
option to output  `houdini pull-schema` command results  to system out 

### ISSUE THREAD

**Issue by xmlking** [HoudiniGraphql/houdini#1115]
### Describe the feature

I have a need for generating schema for a specific **role** to be used  by [genqlient](https://github.com/Khan/genqlient)
the default behavior of  `houdini` CLI is to overwrite `schema.graphql` project root. 

would be nice if I can redirect the output to a new file like this 
```
houdini pull-schema -h "x-hasura-admin-secret=mykey" -h "x-hasura-allowed-roles=aaa bbb" -h "x-hasura-role=aaa" > aaa.schema.graphql
```

### Criticality

None

**Comment by AlecAivazis** [comment]
Hm maybe I am not following but you should be able to configure where the schema is written to with the `schemaPath` configuration value. Does that satisfy your needs?

**Comment by xmlking** [comment]
I needed to run  `houdini pull-schema` in another golang repo, where I don't have `houdini.config.js` 
I like the `houdini cli`  compared to golang  based tools like [gqlfetch](https://github.com/suessflorian/gqlfetch) (buggy...)

**Comment by AlecAivazis** [comment]
Ah gotcha! Well I am totally fine with adding a `-o` flag to the command to allow you to specify a path to write the file to. If that works and you have the time/energy to submit a PR I'd gladly review it
