### ISSUE TITLE
Behavior of fetching in Svelte Houdini stores changed in a breaking way

### ISSUE THREAD

**Issue by TeyKey1** [HoudiniGraphql/houdini#1117]
### Describe the bug

It appears that the behaviour of the `fetching` variable in houdini-svelte document stores changed in the update v1.2.1 due to #1068 which breaks my lazy-loading components. I'm defining my graphql queries in separate files and then import them as houdini stores:

```js
import { MyAwesomeQueryStore } from '$houdini';

const MyAwesomeQuery = new MyAwesomeQueryStore();

console.log($MyAwesomeQuery.fetching) // Returns true since v1.2.1 but used to return false

function fetchData() {
    if ($MyAwesomeQuery.fetching) return;

    MyAwesomeQuery.fetch(); // Is never called as fetching is true but data is not actually being fetched
}
```

As seen in the snippet above, `fetching` appears to be `true` at the time of store creation, even though the data was never being fetched. This behaviour is different to pre v1.2.1 where fetching initialized to `false`, which generally makes more sense as `fetch()` has not yet been called.

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

1. Instantiate a new houdini document store with houdini-svelte v1.2.1 or higher
2. observe the initial value of the `fetching` variable of this document store which should be `true`
3. Downgrade to 1.2.0
4. observe the initial value of the `fetching` variable of this document store which should be `false` now

**Comment by jycouet** [comment]
Hi @TeyKey1, 
You are right, thank you for the official report. 

Actually, we talked about it here: https://github.com/HoudiniGraphql/houdini/pull/1085 _(if you want a bit of history)_

Summary: Three topics are deeply nested and that make the thing full magic complicated.
- A/ `fetching` initial value
- B/ queries `initialization setup isolation`
- C/ Destructuring data via `let || $:`
_(knowing that each topic can have queries in the file and/or in an external file.)_

---

## Way to do today:
###  Option 1
Define your queries in the component directly 👍

### Option 2
Define your queries not in a `MyQuery.gql` but in a `MyQuery.svelte`
like this: 
```html
<script lang="ts">
  import { graphql } from "$houdini";
  graphql(`
    query MyQuery {
      me {
        name
      }
    }
  `);
</script>
```

---

## Going further:
Once I'll have a bit more time, I would like to finish the linked PR to have in the constructor for the store, an arg to manually overwrite the `fetching` initial state. _If you want to give a try let me know._

**Comment by TeyKey1** [comment]
Hello @jycouet 

Thanks for the workarounds and the context. That should solve my issue for the time being.

Generally, I was planning to take a closer look under the hood of houdini & houdini-svelte to understand some of the magic happening :D In case that PR is still open by that time I might give it a try

**Comment by AlecAivazis** [comment]
I'm going to close this since it sounds like it has been addressed in the short term and the medium/long term solution is already captured in a PR
