### ISSUE TITLE
Houdini is loading all my stores at once causing performance issue

### ISSUE THREAD

**Issue by mingsterism** [HoudiniGraphql/houdini#1136]
### Describe the bug

I just wish to call one of my stores, but looking at the network request, it's calling all my stores located in the path $houdini/plugins/houdini-svelte/stores

I'm calling my store like this
```
import { load_GetSysLocations } from '$houdini';
import type { PageLoad } from './$types';

export const load: PageLoad = async (event) => {
  const variables = {
    // id: // Something like: event.url.searchParams.get('id')
    };

  return await load_GetSysLocations({ event, variables });
};
```

however, all 50 other load_* functions get called as well. 

How can this be avoided as it would cause a performance issue. 

this is examples of my files in `$houdini/plugins/houdini-svelte/stores`
![image](https://github.com/HoudiniGraphql/houdini/assets/12984614/1cf97742-f88e-4009-b6f7-415debd26a7e)

Looking at the network tab, i can see all the calls and the performance issue. 
![image](https://github.com/HoudiniGraphql/houdini/assets/12984614/33841d31-a6e3-4198-9cca-16e2c7ed439c)

Thanks

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

`npm run dev`

**Comment by devunt** [comment]
This only happens in dev server. In the production build, the codes are splitted correctly by vite/esbuild and only the required houdini store codes are loaded when they are actually needed.

**Comment by AlecAivazis** [comment]
Huh that's strange

> all 50 other load_* functions get called as well 

When you say that they get called, do you mean the functions are invoked or just loaded?

Do you mind sharing your `houdini.config.js` file?

**Comment by AlecAivazis** [comment]
I'm going to close this since its gone a bit stale. if you want to dig into some more, feel free to reach out on discord 👍
