### ISSUE TITLE
Cannot use it alongside sveltekit-flash-message

### ISSUE THREAD

**Issue by kloon15** [HoudiniGraphql/houdini#1137]
### Describe the bug

I'm trying to build a demo application featuring Houdini in SvelteKit and i ran into this issue:

> If i wrap the loadFlash function around load i end up with two load functions and breaks the app. Removing it makes it run but i need flash messages.

`Internal server error: Transform failed with 2 errors:
/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts:14:13: ERROR: Multiple exports with the same name "load"
/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts:14:13: ERROR: The symbol "load" has already been declared
  Plugin: vite:esbuild
  File: /home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts:14:13

  Multiple exports with the same name "load"
  12 |  }
  13 |
  14 |  export const load = loadFlash(async (
     |               ^
  15 |      {
  16 |          locals

  The symbol "load" has already been declared
  12 |  }
  13 |
  14 |  export const load = loadFlash(async (
     |               ^
  15 |      {
  16 |          locals

      at failureErrorWithLog (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:1649:15)
      at /home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:847:29
      at responseCallbacks.<computed> (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:703:9)
      at handleIncomingPacket (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:762:9)
      at Socket.readFromStdout (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:679:7)
      at Socket.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) (x4)
Error: Transform failed with 2 errors:
/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts:14:13: ERROR: Multiple exports with the same name "load"
/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts:14:13: ERROR: The symbol "load" has already been declared
    at failureErrorWithLog (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:1649:15)
    at /home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:847:29
    at responseCallbacks.<computed> (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Multiple exports with the same name "load"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'The symbol "load" has already been declared'
    }
  ],
  warnings: [],
  frame: '\n' +
    '\x1B[33mMultiple exports with the same name "load"\x1B[39m\n' +
    '12 |  }\n' +
    '13 |  \n' +
    '14 |  export const load = loadFlash(async (\n' +
    '   |               ^\n' +
    '15 |      {\n' +
    '16 |          locals\n' +
    '\n' +
    '\x1B[33mThe symbol "load" has already been declared\x1B[39m\n' +
    '12 |  }\n' +
    '13 |  \n' +
    '14 |  export const load = loadFlash(async (\n' +
    '   |               ^\n' +
    '15 |      {\n' +
    '16 |          locals\n',
  loc: {
    column: 13,
    file: '/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts',
    length: 4,
    line: 14,
    lineText: 'export const load = loadFlash(async (',
    namespace: '',
    suggestion: ''
  },
  plugin: 'vite:esbuild',
  id: '/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts',
  pluginCode: 'import { buildSessionObject } from "$houdini/plugins/houdini-svelte/runtime/session";\n' +
    'import type { LayoutServerLoad } from "./$types";\n' +
    'import { loadFlash } from "sveltekit-flash-message/server";\n' +
    '\n' +
    'export async function load(event) {\n' +
    '    const __houdini__vite__plugin__return__value__ = {};\n' +
    '\n' +
    '    return {\n' +
    '        ...buildSessionObject(event),\n' +
    '        ...__houdini__vite__plugin__return__value__\n' +
    '    };\n' +
    '}\n' +
    '\n' +
    'export const load = loadFlash(async (\n' +
    '    {\n' +
    '        locals\n' +
    '    }\n' +
    ') => {\n' +
    '    return {\n' +
    '        user: locals.user\n' +
    '    };\n' +
    '}) satisfies LayoutServerLoad;'
}`

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

1. Have a basic load function in the global +layout.server.ts file:
```
import type { LayoutServerLoad } from './$types'
import { loadFlash } from 'sveltekit-flash-message/server'

export const load = (async ({ locals }) => {
  return {
    user: locals.user,
  }
}) satisfies LayoutServerLoad

```
2. Wrap it in loadFlash()
3. Fails with `Multiple exports with the same name "load"`

**Comment by AlecAivazis** [comment]
Oh wow sorry I lagged on responding to this! I thought we were being smarter about how we modified the `load` function. I'll  make sure that we modify an existing load function. 

In the meantime, could you try flipping the order of the two vite plugins?

**Comment by AlecAivazis** [comment]
Okay so from the error message it looks like the problem is that there are two `loads` defined in the root `+layout.server.ts` which we use to set up our session stuff. I went to the [session tests](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/plugin/transforms/kit/session.test.ts) and we have a test that verifies that we don't define another `load` function if one is already present. Intsead we augment the existing definition with what we need. So either `sveltekit-flash-message` isn't checking to augment an existing `load` or for some reason houdin isn't able to identify the overlap. 

Let me know how things go with reversing the plugins 👍

**Comment by kloon15** [comment]
> Oh wow sorry I lagged on responding to this! I thought we were being smarter about how we modified the `load` function. I'll make sure that we modify an existing load function.
> 
> In the meantime, could you try flipping the order of the two vite plugins?

Same exact result. Still generates a second load function.

**Comment by AlecAivazis** [comment]
Okay cool so that means it should be something we can fix. Do you mind putting together a repo with the necessary files/dependencies? I'm bouncing between a lot of things and it would help me quickly figure out what's going on

**Comment by kloon15** [comment]
> Okay cool so that means it should be something we can fix. Do you mind putting together a repo with the necessary files/dependencies? I'm bouncing between a lot of things and it would help me quickly figure out what's going on

Sure, [here](https://github.com/kloon15/houdini-flash-msg)

**Comment by eikaramba** [comment]
i added an issue on the sveltekit-flash-message repo, just gonna link it here, as i just stumpled upon this issue here as well. good that there is some progress :)
https://github.com/ciscoheat/sveltekit-flash-message/issues/29

**Comment by eikaramba** [comment]
okay i have debuged the transformer plugin a little bit and can see that houdini seems to not find the existing load function.

i added console output before the following line
https://github.com/HoudiniGraphql/houdini/blob/1fa23927cf702df35268ceef29550937c757990a/packages/houdini-svelte/src/plugin/transforms/kit/session.ts#L112
`console.log("load function found?",load_fn,page2.script.body);`




and this is the result:
```
load function found? null [
  {
    type: 'ImportDeclaration',
    source: {
      value: '$houdini/plugins/houdini-svelte/runtime/session',
      loc: null,
      type: 'StringLiteral',
      comments: null,
      extra: [Object]
    },
    specifiers: [ [Object] ],
    importKind: undefined
  },
  Node3 {
    type: 'ImportDeclaration',
    start: 0,
    end: 45,
    loc: SourceLocation3 {
      start: [Position3],
      end: [Position3],
      filename: undefined,
      identifierName: undefined
    },
    importKind: 'value',
    specifiers: [ [Node3] ],
    source: Node3 {
      type: 'StringLiteral',
      start: 28,
      end: 44,
      loc: [SourceLocation3],
      extra: [Object],
      value: '$lib/constants'
    },
    assertions: []
  },
  Node3 {
    type: 'ImportDeclaration',
    start: 47,
    end: 106,
    loc: SourceLocation3 {
      start: [Position3],
      end: [Position3],
      filename: undefined,
      identifierName: undefined
    },
    importKind: 'value',
    specifiers: [ [Node3] ],
    source: Node3 {
      type: 'StringLiteral',
      start: 73,
      end: 105,
      loc: [SourceLocation3],
      extra: [Object],
      value: 'sveltekit-flash-message/server'
    },
    assertions: [],
    trailingComments: [ [Object] ]
  },
  Node3 {
    type: 'ExportNamedDeclaration',
    start: 159,
    end: 787,
    loc: SourceLocation3 {
      start: [Position3],
      end: [Position3],
      filename: undefined,
      identifierName: undefined
    },
    exportKind: 'value',
    specifiers: [],
    source: null,
    assertions: [],
    declaration: Node3 {
      type: 'VariableDeclaration',
      start: 166,
      end: 787,
      loc: [SourceLocation3],
      declarations: [Array],
      kind: 'const'
    },
    leadingComments: [ [Object] ]
  }
]
```
