### ISSUE TITLE
cache.get doesn't work on server side

### ISSUE THREAD

**Issue by cranelee** [HoudiniGraphql/houdini#1139]
### Describe the feature

When graphQL request run at clientside cArticle has values, but at serverside cArticle is null

```
   // code in +page.ts
    const cacheArticle = cache.get('Article', { id });
    const cArticle = cacheArticle.read({
        fragment: graphql(`
            fragment ArticleCacheInfo on Article {
                id
                contentType
            }
        `)
    });
```

### Criticality

nice to have

**Comment by jycouet** [comment]
Yes, the cache is not on the serverside as it could be quite dangerous.
eg: If Bob asks for article 7, can Alice access it too?

Maybe you can share a bit more about your use case to elaborate on a solution?

**Comment by AlecAivazis** [comment]
I'm going to close this since its gone a bit stale. More than happy to open this back up later
