### ISSUE TITLE
Variables does not work with pagination

### ISSUE THREAD

**Issue by samuel-utbult-oborgen** [HoudiniGraphql/houdini#1175]
### Describe the bug

I have set up a query with a `@paginate` attribute in a `+page.gql` file with a `+page.ts` handling variables for sorting (and I will add filtering later). The initial load works just fine but the next load caused by `.loadNextPage()` causes the request to fail as the sorting parameter is not included in the request. Only the pagination parameters are included.

I propose this could be fixed by simply including all variables in the initial request in all subsequent requests.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Create a `+page.gql` file like this (I specifically use Hot Chocolate in the server but it should be similar to how other server frameworks handles sorting):
```
query GetElements($order: [ElementSortInput!]!) {
    ships(first: 10, order: $order) @paginate(name: "Elements") {
        edges {
            node {
                field
            }
        }
    }
}
```
2. Create a `+page.ts` file like this:
```
import type { GetElementsVariables } from "./$houdini";

export const _GetElementsVariables: GetElementsVariables = () => {
    return {
        order: [
            {
                field: "ASC",
            },
        ],
    };
};
```
3. Create a `+page.svelte` file like this:
```
<script lang="ts">
    import type { PageData } from "./$houdini";
    export let data: PageData;
    $: ({ GetElements } = data);

    async function loadNext() {
        await GetElements.loadNextPage();
    }
</script>

<!-- Irrelevant HTML implementation that calls loadNext on certain occations.
    -->
```
4. `.loadNextPage()` make requests that fail.

**Comment by samuel-utbult-oborgen** [comment]
I figured out why this happened. I used a network plugin in the client to make my requests like how it was done before the current iteration of HoudiniClient was implemented. This made it so `data` (or possibly `error`) were the only fields in the result value, which means `variables` was missing. This caused the pagination logic to not include any extra variables in the following requests. Could you possibly add some kind of warning about this?

**Comment by AlecAivazis** [comment]
Ahhh makes total sense! I'm surprised there wasn't a type error. Do you have any ideas for how we could detect this situation?

**Comment by samuel-utbult-oborgen** [comment]
I used to have a plugin that looked like this (but very simplified):
```
const plugin: ClientPlugin = () => {
    return {
        async network(context, { resolve }) {
            const result = await context.fetch!("/graphql", {
                method: "POST",
                body: JSON.stringify({
                    query: context.text,
                    variables: context.variables,
                }),
            });
            const responseContent = await result.text();
            const response = JSON.parse(responseContent);
            resolve(context, response);
        },
    };
};

export default new HoudiniClient({
    url: "/graphql",
    plugins: [
        plugin,
    ],
});
```
The result of `JSON.parse` should be a `QueryResult` but it clearly is not since the server only responds with an object with a `data` or `error` field. This is a problem inherent to Typescript because of the `any` type being cast to a `QueryResult`.

Is there any particular reason why it's the client's responsibility to pass back `variables` along with `fetching`, `partial`, `stale` and `source`? To me, a client would simply make requests and pass the responses back to a framework that would take care of these values internally.

Where are these fields added to the result? As it stands right now, I don't see how `network` plugins could be used at all since these fields would have to be added manually. For instance, how would one currently use a custom `fetch` function?

**Comment by samuel-utbult-oborgen** [comment]
I have just encountered such a case. I need to inject some logic that depends on the returned status code (specifically to reload the page on 401 responses to re-authenticate the user). I have managed to solve it through monkey-patching like this:
```
if (browser) {
    const realFetch = fetch;
    window.fetch = async (
        input: RequestInfo | URL,
        init?: RequestInit | undefined,
    ): Promise<Response> =>
        new Promise((resolve, reject) =>
            realFetch(input, init)
                .then((response) => {
                    if (response.status === 401) {
                        location.reload();
                    } else {
                        resolve(response);
                    }
                })
                .catch(reject),
        );
}
```
However, it's not a very elegant solution. Could this logic be injected some other way without causing any other problems?

**Comment by AlecAivazis** [comment]
Yea, I agree the plugin API could be cleaned up a bit in that respect. Those values are there because its easy to do and it keeps things simple. I think eventually some of these fields would be marked optional and the values from `ctx` could be inferred instead of making you pass it manually like i do in the [default fetch plugin](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini/src/runtime/client/plugins/fetch.ts).

I'm going to close this issue since the original bug is no longer a problem but we can keep the conversation going 👍
