### ISSUE TITLE
Do not load houdini.config.js in the browser

### ISSUE THREAD

**Issue by lubiah** [HoudiniGraphql/houdini#1229]
### Describe the bug

I just realized houdini.config.js is being imported inside client side code. How are we to use env variables if this file is imported into client side code

### Severity

annoyance

### Steps to Reproduce the Bug

1. Start a new houdini project with sveltekit
2. Check the browser tab

**Comment by jycouet** [comment]
Yeah, `houdini.config.js` is going to the browser. It's very handy for `marshal`, `unmarshal` for example.
Would you describe a bit more your use case to understand better your concern?

**Comment by lubiah** [comment]
Yeah, my problem was with loading sensitive data. I just realized Houdini provides the env variable through the function

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by jycouet** [comment]
Great, I'll close the issue then. If you find something else don't hesitate to reopen && || join uor discord 💪
