### ISSUE TITLE
I need more information on Errors

### ISSUE THREAD

**Issue by LazerJesus** [HoudiniGraphql/houdini#1232]
### Describe the bug

Somewhere in my schema is an error. But the debugging info Houdini provides doesnt help me find where.

This is the error message i get on build and then it fails:
```
🎩 Generating runtime...
❌ undefined does not match field "name": string of type Identifier
error when starting dev server:
Error: undefined does not match field "name": string of type Identifier
[[...]]
error: script "dev" exited with code 1 (SIGHUP)
```

how can i get information like Object or File?

### Severity
blocking all usage of Houdini

### Reproduce
1. have a schema error
2. start a vite dev server

**Comment by LazerJesus** [comment]
hi @jycouet 
what is 0 operation? 
I need more information for debugging in general. 
this is not the entire schema but the only occurence of name. 

```
type Query {
  curriculumsRead: [Curriculum!]!
}

type Curriculum {
  id: ID!
  name: String!
}
```

**Comment by LazerJesus** [comment]
removing houdini from the vite plugins allows the server to start.
```
 defineConfig({
    plugins: [sveltekit()]
})
```

**Comment by jycouet** [comment]
What I mean by `0 Operation` is to know if you have already some queries or mutations in your frontend?

With this small schema, you have the same error? Or only when you have the complete schema?
_(You can comment `watchSchema` to not overwrite your `schema.graphql`)_

Could you share the complete schema for me to check as well?

**Comment by LazerJesus** [comment]
I was able to isolate the Object causing the issue by comment-toggling all types and resolvers. 
but i dont want to have to resolve to that level of manual labor just to get information on the source of the issue. 
all that labor would have been saved if 1. i had the name of the object or 2. the  file and line in the error message `undefined does not match field "name"`
how can i enable that if thats possable? if not then how do other deal with this?

**Comment by jycouet** [comment]
If I understand correctly, it was a Server / GraphQL Schema issue, correct? 
To be able to help with a better message, we have to reproduce 'the error' in our e2e test and it will help everyone 👍.

Our messages today are more focused on the client side of it. We assume that your server is 👍

Let's try to improve that! Can you share the bit that was causing the issue?

**Comment by LazerJesus** [comment]
the issue was on the front end. 
the server is type checked and was building fine without any conflicts, misses, or inconsistencies. I am using pothos-graphql. 
as you can see in the error logs i posted, there was no information about the client side location of the error.

**Comment by jycouet** [comment]
Okay, I apologize 😢

Can you show the query you were doing so that we reproduce in the e2e tests?

Thx!

**Comment by LazerJesus** [comment]
i'd love to but i've solved the issue yesterday and that particular state wasn't gited. if it happens again, i will.
but my problem was the lack of information about the issue, not this specific issue.

**Comment by jycouet** [comment]
Yes! 
But I need more info about your issue, because usually errors look like this: 
![Capture d’écran 2023-11-22 à 09 46 57](https://github.com/HoudiniGraphql/houdini/assets/5312607/6017ab63-f460-492b-8356-7525c10552f1)

Where you see the `filePath`, the `field`, the `type`... Everything! 🎉

So why not in your case? I would like to understand your case to do things better 😉.

**Comment by LazerJesus** [comment]
ok yeah thats what i need. ok then lets go from the ground up.

package.json
```json
{
    "name": "frontend",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "dev": "vite --force dev",
        "build": "vite build",
        "preview": "vite preview",
        "check": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json",
        "check:watch": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json --watch",
        "lint": "prettier --plugin-search-dir . --check . && eslint .",
        "format": "prettier --plugin-search-dir . --write .",
        "storybook": "storybook dev -p 6006",
        "build-storybook": "storybook build"
    },
    "devDependencies": {
        "@storybook/addon-docs": "^7.5.2",
        "@storybook/addon-essentials": "^7.5.2",
        "@storybook/addon-interactions": "^7.5.2",
        "@storybook/addon-links": "^7.5.2",
        "@storybook/addon-svelte-csf": "^4.0.9",
        "@storybook/blocks": "^7.5.2",
        "@storybook/builder-vite": "^7.5.2",
        "@storybook/svelte": "^7.5.2",
        "@storybook/sveltekit": "^7.5.2",
        "@storybook/testing-library": "^0.2.2",
        "@sveltejs/adapter-auto": "^2.0.0",
        "@sveltejs/adapter-node": "^1.3.1",
        "@sveltejs/kit": "^1.20.4",
        "autoprefixer": "^10.4.14",
        "eslint": "^8.28.0",
        "eslint-config-prettier": "^8.5.0",
        "eslint-plugin-storybook": "^0.6.15",
        "eslint-plugin-svelte": "^2.30.0",
        "houdini": "^1.2.10",
        "houdini-svelte": "^1.2.10",
        "postcss": "^8.4.24",
        "postcss-load-config": "^4.0.1",
        "prettier": "latest",
        "prettier-plugin-svelte": "latest",
        "storybook": "^7.5.2",
        "svelte": "^4.0.5",
        "svelte-check": "^3.4.3",
        "svelte-preprocess": "^5.0.4",
        "tailwindcss": "^3.3.2",
        "typescript": "^5.0.0",
        "@storybook/addon-actions": "^7.5.2",
        "vite": "^4.4.9"
    },
    "type": "module",
    "dependencies": {
        "graphql-scalars": "^1.22.4",
        "svelte-swipe": "^2.0.3"
    }
}
```

viteconfig
```js
import { defineConfig } from "vite";
import { sveltekit } from "@sveltejs/kit/vite";
import houdini from "houdini/vite";

export default defineConfig({
    plugins: [houdini(), sveltekit()],
    logLevel: "info",
    mode: "development"
});
```
svelte config
```js
import { vitePreprocess } from "@sveltejs/kit/vite";
import preprocess from "svelte-preprocess";

import adapter from "@sveltejs/adapter-node";

/** @type {import('@sveltejs/kit').Config} */
const config = {
    kit: {
        adapter: adapter(),
        alias: {
            $houdini: "./$houdini"
        }
    },

    preprocess: [
        vitePreprocess({})
        // preprocess({
        //   postcss: true
        // })
    ]
};

export default config;
```
houdini.js
```js
import { DateTimeResolver, DateTimeMock } from "graphql-scalars";
/// <references types="houdini-svelte">

/** @type {import('houdini').ConfigFile} */
const config = {
    watchSchema: {
        url: "http://localhost:4000"
    },
    plugins: {
        "houdini-svelte": {}
    },
    scalars: {
        DateTime: DateTimeResolver
    }
};

export default config;
```

I'll try setting up the project in a way that it reproduces the error.

**Comment by LazerJesus** [comment]
ok so, just introducing a faulty gql string results in your verbose error. i search.

**Comment by AlecAivazis** [comment]
I'm going to close this since its gone a bit stale. Let me know if you are still running into issues and we can reopen this if you run into something reproducible that we can try
