### ISSUE TITLE
Svelte Reactive Statements create "false" nulls

### ISSUE THREAD

**Issue by Rudedog9d** [HoudiniGraphql/houdini#1235]
### Describe the bug

When using the value of a query store directly in a reactive statement, fetches that occur **after the initial fetch** create `null` values in the data where there shouldn't be any.

I'll try to get a replay.io made of the situation.

### Severity

annoyance

### Steps to Reproduce the Bug

I was using the following code to fetch some information about our users:

```ts
  $: teamStore = new TeamByPkStore();
  $: teamStore.subscribe((result) => {
    if (result.errors?.length) console.error('failed fetch', result.errors);
  });
  $: team = $teamStore.data?.teams_by_pk;
  $: fetch(teamId);

  function fetch(team_id: string) {
    teamStore.fetch({ variables: { team_id } });
  }
```

Then using `team` directly in code later. Team has many nested fields

<details>
  <summary>Team Structure if you care</summary>
  
```ts
export type TeamByPk$result = {
    readonly teams_by_pk: {
        readonly id: UUID;
        readonly long_name: string | null;
        readonly institution_id: UUID | null;
        readonly max_team_size: number | null;
        readonly name: string;
        readonly team_full: boolean | null;
        readonly team_size: number | null;
        readonly team_lead_id: UUID | null;
        readonly liaison_id: UUID | null;
        readonly members: ({
            readonly user_id: UUID;
            readonly user: {
                readonly id: string;
                readonly first_name: string | null;
                readonly last_name: string | null;
                readonly email: string | null;
            } | null;
        })[];
        readonly liaison: {
            readonly id: string;
            readonly first_name: string | null;
            readonly last_name: string | null;
            readonly email: string | null;
        } | null;
        readonly institution: {
            readonly name: string;
            readonly id: UUID;
            readonly regions: ({
                readonly region_id: UUID;
                readonly institution_id: UUID;
                readonly region: {
                    readonly name: string;
                };
            })[];
        } | null;
        readonly " $fragments": {
            TeamFields: {};
        };
    } | null;
};
```
  
</details>

The page would initially load fine. When we made a change to a team:

- We would call a mutation within a svelte component
- Call the `fetch` function (via a custom event)

When the data was returned:
- `teams_by_pk.members[].user` was null (even though `user_id` was populated)
    - `members[].user` is actually a remote schema, okay fine, maybe thats the problem?
- `teams_by_pk.institution.regions` was an array of `[null, null]`
    - Okay, that should NEVER happen (both by our data and the type generated from the schema)

After alot of trial and error, we discovered that this DOES work as expected:

```ts
  $: teamStore = new TeamByPkStore();
  $: teamStore.subscribe((result) => {
    if (result.errors?.length) console.error('failed fetch', result.errors);
  });
  let team: TeamByPk$result['teams_by_pk'];
  $: fetch(teamId);

  async function fetch(team_id: string) {
    await teamStore.fetch({ variables: { team_id } });
    if ($teamStore.data) team = $teamStore.data.teams_by_pk;
  }
```

Taking the debugging a step further, maybe it's still fetching data? So we put in this statement:

```ts
 $: if ($teamStore.fetching) {
    console.log('caught you fetching!');
  } else {
    console.log('finally done fetching are we?', $teamStore.data?.teams_by_pk);
  }
```

The result, we did see "caught you fetching" a few times, but the data was still not complete. 

We also tried this with the same "false `null`" results:

```ts
$: if (!$teamStore.fetching && $teamStore.data) team = $teamStore.data?.teams_by_pk;
```

I've marked this as an annoyance because we do have a path forward, this works fine:

```ts
$: teamStore = new TeamByPkStore();
  $: teamStore.subscribe((result) => {
    if (result.errors?.length) console.error('failed fetch', result.errors);
  });
  let team: TeamByPk$result['teams_by_pk'];
  $: fetch(teamId);

  async function fetch(team_id: string) {
    // this is the main change - await the fetch and only set teams after
    await teamStore.fetch({ variables: { team_id } });
    if ($teamStore.data) team = $teamStore.data.teams_by_pk;
  }
```

I assume this behavior isn't expected and some weird bug in the way svelte stores are interacting with reactive statements?

**Comment by AlecAivazis** [comment]
Any update here @Rudedog9d?

I'm going to close this since its gone a bit stale and we can reopen if necessary. feel free to drop by the discord channel for faster response times!
