### ISSUE TITLE
Cache.markStale + houdini_load.fetch not reaching the server.

### ISSUE THREAD

**Issue by LazerJesus** [HoudiniGraphql/houdini#1240]
### Describe the bug

I have a query defined, and it does not refetch when i tell it to.
It looks like this:
```graphql
export const _houdini_load = graphql(`
    query GetSentence($input: GetSentence_Input!) @cache(policy: NetworkOnly) {
    }
}
```
here i try to mark it as stale and refetch. 
```js
        cache.markStale("GetSentence");
        const variables = _GetSentenceVariables({ params: { id: gameId } });
        const response = await _houdini_load.fetch({ variables });
```
no request is sent to the server.

houdini config
```js
const config = {
    // defaultCachePolicy: "NetworkOnly",
    features: {
        imperativeCache: true
    },
}
```

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

```
        "houdini": "^1.2.10",
        "houdini-svelte": "^1.2.10",
```

**Comment by jycouet** [comment]
Could you add where you have these code blocs? 

From what I understand, `imperativeCache` is not needed here.
Note also that `cache` is not used in the kit server.

**Comment by LazerJesus** [comment]
sure.

this snippet is from a +page.js in my routes folder:
```graphql
export const _houdini_load = graphql(`
    query GetSentence($input: GetSentence_Input!) @cache(policy: NetworkOnly) {
    }
}
```

this is in a store.js in the same directory as the query above. 
```js
        cache.markStale("GetSentence");
        const variables = _GetSentenceVariables({ params: { id: gameId } });
        const response = await _houdini_load.fetch({ variables });
```
some more context on.
i create a store that contains a fetchSentence function.
this function is called once on init of the store and later from a storemethod.
the init returns a fresh sentence. no problem.
but when i call fetchSentence later, the sentence returned by `GetSentence` is the same as the old even tho i marked the cache as stale AND set the query to `NetworkOnly`.
```
function createStore() {
    const Store = writable({
        sentence: null,
        error: null
    });
    const { subscribe, set, update } = Store;

    const fetchSentence = async (gameId) => {
        cache.markStale("GetSentence");
        const variables = _GetSentenceVariables({ params: { id: gameId } });
        const response = await _houdini_load.fetch({ variables });
        const error = response.errors && response.errors[0];
        const sentence = !error && response.data.GetSentence;
        return { sentence, error };
    };
   [...]
    return {
        subscribe,
        init: async ({ gameId }) => {
            const { sentence, error } = await fetchSentence(gameId);
           [...]
    },
        getSentence: async ({gameId}) => {
            const { sentence, error } = await fetchSentence(gameId);
           [...]
     }
 }
```

**Comment by jycouet** [comment]
I don't really get why you are doing all this. You are somehow recreating the store that Houdini is already giving you 🤔. _I'm maybe missing something?_

I would do something like: 
```js
# +page.js
export const _houdini_load = graphql(`
    query GetSentence($input: GetSentence_Input!) @cache(policy: NetworkOnly) {
    }
}
```
And in `data` of your `+page.svelte`, you have your store, and you can refetch.

In Addition, you can do also this in any other *.svelte file:
```js
<script>
const store = new GetSentenceStore()

const getNewOne = () => {
  store.fetch({ gameId: 7 })
}
</script>

<button on:click={getNewOne}>Get Data Plz</button>
{JSON.Stringify($store, null, 2)}
```

**Comment by LazerJesus** [comment]
@jycouet i sent an abbreviated version of the store. there is a lot going on in there. including fetching and storing multiple sentences in parallel. 
this method just doesnt fit my architecture.

**Comment by jycouet** [comment]
Okay, sorry that I didn't grasp what you are trying to do.
I'm not sure how to help you best.

For sure, you can do a "bigger" or "custom" store to have your right abstraction but in order to help I need more context/code. When you are in the client, houdini provides you regular stores... So you can derive and do everything you want. The code I suggested is naive, but it's like this that you should interact with stores. 

What I can point out, is that "_houdini_load" is meant to be used in a universal load function.

Let me know how to help more 👍

**Comment by LazerJesus** [comment]
ok i got it to work the way i like.
replaced `_houdini_load` with `sentenceStore.fetch` basically. but still in the context of my store. storeception.

**Comment by jycouet** [comment]
Great to read 🎉

**Comment by LazerJesus** [comment]
what was the issue tho wiht my invalidating cache strategy?

**Comment by jycouet** [comment]
In the fetch function you have the policy arg where you can tune stuff directly. 

"manual" cache invalidation is for more complex usecases
