### ISSUE TITLE
SvelteKit 2 support

### ISSUE THREAD

**Issue by eikaramba** [HoudiniGraphql/houdini#1241]
### Describe the feature

SvelteKit 2 was released - error handling has changed and is the biggest breaking change for this library i guess.

### Criticality

waiting for it before migrating to sveltekit 2

**Comment by jycouet** [comment]
I think there is also something with the `load` & `await` 🤔
Do you already have a repro? or?

**Comment by eikaramba** [comment]
i just tested a private project of mine. interestingly houdini works there although i updated to sveltekit 2.0 - i haven't tested every case, but was suprised that no error was shown or something like that.

**Comment by jycouet** [comment]
I confirm that everything is working as expected with `"@sveltejs/kit": "^2.0.0"`

e2e tests running on kit 👇
![Capture d’écran 2023-12-18 à 19 44 10](https://github.com/HoudiniGraphql/houdini/assets/5312607/cfa16109-e99e-4fdb-b779-ecd9fec09277)

I'll do a PR to bump e2e tests, but I guess we can close this "issue"?

**Comment by eikaramba** [comment]
yes this can be closed, sry i really thought that more would be needed. unfortunately i wasn't able to run the code at the time to verify my claim :)

**Comment by xmlking** [comment]
@jycouet  find following issue, when I created fresh project today. looks like vite plugin order of execution issue!
https://github.com/HoudiniGraphql/houdini/issues/1246
