### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'setup')

### ISSUE THREAD

**Issue by tienpvse1** [HoudiniGraphql/houdini#1247]
### Describe the bug

Hi everyone, I'm kinda new to Sveltekit and Houdini
Currently I'm facing an issue with SinglePage mode when using paginate query

- Sveltekit version:  2.0.0
- Houdini version:  1.2.34,
- houdini-svelte version: 1.2.34

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

my +page.gql look like this 
```graphql
query Launches {
	launches(limit: 10) @paginate(mode: SinglePage)  {
		id
		mission_name
	}
}
```
And this is my +page.svelte
```svelte
<script lang="ts">
	import { Button } from 'flowbite-svelte';
	import type { PageData } from './$houdini';

	export let data: PageData;

	$: ({ Launches } = data);
</script>

<Button color="alternative" on:click={() => data.Launches.loadNextPage()}>Load more</Button>

{#if $Launches.data?.launches}
	{#each $Launches.data?.launches as launch}
		<h1>{launch?.mission_name}</h1>
	{/each}
{/if}
```
When I press the button the browser says:
![image](https://github.com/HoudiniGraphql/houdini/assets/86212960/71704097-30fe-4811-9705-c09db123fe11)

![image](https://github.com/HoudiniGraphql/houdini/assets/86212960/fd1c287b-447f-45f4-9021-578103aa5cad)

**Comment by AlecAivazis** [comment]
Hello @tienpvse1!

Unforunately there isn't enough information in this issue to debug what's going on. Can you put together a reproduction or push your code up somewhere?

**Comment by tienpvse1** [comment]
Hi @AlecAivazis, here's the link of my repository: https://github.com/tienpvse1/houdini-sveltekit
