### ISSUE TITLE
Houdini for Express Servers

### ISSUE THREAD

**Issue by Rudedog9d** [HoudiniGraphql/houdini#1254]
### Describe the feature

Would it be possible to create a generic server-side "plugin(?)" for houdini that enabled it's use with general servers like express? Having a type-generated client for servers would be an awesome resource.

I see that there are separate folders for `houdini`, `houdini-svelte`, and `houdini-react` - so it seems like the app was built with expansion to other frameworks in mind.

What would it take to create a version of Houdini that supports being a server-side client? Is that possible?

### Criticality

nice to have

**Comment by Rudedog9d** [comment]
For example, my team would like to build a new microservice in NodeJS that runs on an interval. It will read some data from our GraphQL server, do some business logic, then insert the result into the server.

We love Houdini and would like to keep using it as our gql client, but the application wouldn't be running a UI - so we're not sure the best way to utilize Houdini.

**Comment by tienpvse1** [comment]
Hi @Rudedog9d, if you want type generated client, maybe you can try [graphql-request](https://github.com/jasonkuhrt/graphql-request) with [graphql codegen](https://the-guild.dev/graphql/codegen) with [graphql-request plugin](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-graphql-request). It's really easy to set things up btw

**Comment by Rudedog9d** [comment]
Oh thanks! We had seen the first two libs before, but [typescript-graphql-request](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-graphql-request) helped bring it all together. Thanks for the link @tienpvse1! Sorry for the noise, maintainers :smile:

**Comment by AlecAivazis** [comment]
Sorry I didn't respond sooner! I'm definitely curious to hear what houdini could do to help you server-side. We probably don't need the cache subscription stuff 🤔

**Comment by Rudedog9d** [comment]
@AlecAivazis We'd love to just use it as a generic GQL client, not tied to any specific front-end framework. Our main "API" and database is [Hasura](https://hasura.io/), so any services we write interface with the DB through GQL.

We're currently trying to write a small typescript-based microservice that reaches out to Hasura, summarizes some data, and takes a "snapshot" of it. So super simple, but generated types would be idea <3

**Comment by AlecAivazis** [comment]
oh well you might be able to get pretty far just using houdini (without `houdini-svelte`) and a custom codegen plugin. Houdini's core generates the types and the custom plugin could generate the functions you would use to invoke each document. Let me know if this direction interests you, i can try to give some examples if so

**Comment by Rudedog9d** [comment]
@AlecAivazis I would definitely be interested in that :eyes: that's the direction I was hoping to go, as we really like Houdini in our UIs
