### ISSUE TITLE
Use GraphQL field descriptions to generate JSDoc comments on `$result` types

### ISSUE THREAD

**Issue by ewen-lbh** [HoudiniGraphql/houdini#1274]
### Describe the feature

In short, adding JS Doc-style comments on fields in `$houdini/artifacts/QueryName.d.ts` would allow showing description of fields in the IDE.

For example, with the following GraphQL schema:

```graphql
type Query {
    """Some documentation here"""
    example: String!
}
```

and the following document:

```graphql
query Example {
    example
}
```

The following store type definition would be created:

```diff
  export type Example$result = {
+ /** Some documentation here */
      readonly example: string;
  }
```

And would allow to see the documentation of the query on hover in (most?) IDEs.

![image](https://github.com/HoudiniGraphql/houdini/assets/39094199/e4641e16-976b-4a09-b9dd-055267b64562)

Of course, this would also apply to sub-fields, not just the root `Query` type's fields

### Criticality

cool improvement, my projects will benefit from it

**Comment by ewen-lbh** [comment]
Something like 

```ts
prop.comments = [AST.blockComment(field.description)]
```

after https://github.com/HoudiniGraphql/houdini/blob/4bc4790d0ee4fff1480c2723d1585cfa58463a60/packages/houdini/src/codegen/generators/typescript/inlineType.ts#L258-L265

could work (`AST.blockComment` probably does not exist, I'm not familiar enough with recast's API)

**Comment by ewen-lbh** [comment]
I'm willing to do a PR if maintainers are OK with this feature

**Comment by AlecAivazis** [comment]
Oh good idea! Seems like a really nice improvement 👍
