### ISSUE TITLE
List operations with hop to parent

### ISSUE THREAD

**Issue by SeppahBaws** [HoudiniGraphql/houdini#1299]
### Describe the bug

A part of our schema looks something like this:
```gql
type Organization implements Node {
  id: ID!
  name: String!
  module1Settings: Module1Settings!
  # more fields...
}

type Module1Settings {
  # Note the lack of an ID field here...
  someConnection(first: Int, after: String, last: Int, before: String): SomeOtherTypeConnection!
}
```
The reason for this is that in the database, these properties are stored straight on the `Organization` table, but for ease of use in the API, we're adding a shadow type (`Module1Settings`).

The problem is that when I add a `@list` on this `someConnection` field, the cache doesn't find the correct list.

Debugging the [`ListManager.get`](https://github.com/HoudiniGraphql/houdini/blob/6c5dbda72fb4b7c42dc85a3991e9705224dda080/packages/houdini/src/runtime/cache/lists.ts#L21) method, I see that it gets the correct lists:
```js
[
  { recordID: "Organization:org1Id.module1Settings", recordType: "Module1Settings", ... },
  { recordID: "Organization:org2Id.module1Settings", recordType: "Module1Settings", ... },
]
```

When it tries to get the `parentID` on L41: https://github.com/HoudiniGraphql/houdini/blob/6c5dbda72fb4b7c42dc85a3991e9705224dda080/packages/houdini/src/runtime/cache/lists.ts#L41
it returns `Module1Settings:org1Id`. Then it tries to find a list where that parentID matches, which of course will fail, since the correct parentID should be `Organization:org1Id`.

For now I can work around it with simply not using the list operations and manually refetching the original query, but it feels like something that Houdini should be able to handle somehow...

### Reproduction

(will try to create one later)

**Comment by AlecAivazis** [comment]
Hmm, this is a bit tricky. Since there isn't an ID its hard to know how we would structure the API to support this situation. My gut says that this is probably best handled using the imperative api 🤔
