### ISSUE TITLE
Setting a custom node interface ID field to support Supabase's Graphql ?

### ISSUE THREAD

**Issue by roeeklinger** [HoudiniGraphql/houdini#1307]
### Describe the bug

According to the Supabase [docs](https://supabase.com/docs/guides/graphql/api#nodeid)

> By default relay expects the ID field for types to have the name id. pg_graphql uses nodeId by default to avoid conflicting with user defined id columns. You can configure relay to work with pg_graphql's nodeId field with relay's nodeInterfaceIdField option. More info available [here](https://github.com/facebook/relay/tree/main/packages/relay-compiler#supported-compiler-configuration-options).

Does Houdini have a config option like Relay's `nodeInterfaceIdField` to customize the expected node interface field name?

**Comment by jycouet** [comment]
If I remember correctly, you can set `defaultKeys: ["nodeId"]` in the config

https://houdinigraphql.com/api/config
