### ISSUE TITLE
Unmarshalling lists of scalars not working

### ISSUE THREAD

**Issue by Faroukhamadi** [HoudiniGraphql/houdini#1321]
### Describe the bug

We have a custom type defined that has `marshal()` and `unmarshal()` methods, this fails when we have an array.
Here's our temporary solution:

```js
scalars: {
  Money: {
    type: 'Money',
    unmarshal(val) {
      // This is the line that I believe shouldn't exist
      if (Array.isArray(val)) {
        return val.map((v) => new Money(parseInt(v)));
      }
      return val ? new Money(parseInt(val)) : new Money(0);
    },
  }
}
```

**Comment by SeppahBaws** [comment]
Ok wow I found a way to reproduce it, and I think I see why this has flown under our radar for so long...

In our tests we only ever test with `Date`s. A fun side-effect about JavaScript Dates is that they can also gracefully handle anything other than what the spec describes the constructor to be: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#passing_a_non-date_non-string_non-number_value

In our e2e tests, I added a little endpoint to the API that returns a list of Dates and I tweaked the unmarshal function to log what's coming in and going out:
```js
scalars: {
  DateTime: {
    type: 'Date',
    unmarshal(val) {
      console.log('Unmarshalling date:', val, new Date(val));
      return new Date(val);
    },
    marshal(val) {
      return val.getTime();
    }
  },
}
```

In the console I'm greeted with this lovely message
![image](https://github.com/HoudiniGraphql/houdini/assets/10342829/269c99c7-3c4e-428d-ad29-6ad9ed68518d)

Oh JavaScript why must you be so weird... 🙃🙃🙃

**Comment by Faroukhamadi** [comment]
This is why we need to use Javascript more and everywhere, would love to see a fix!
