### ISSUE TITLE
Since 1.2.55, only one list is updated on list insert

### ISSUE THREAD

**Issue by jamesbirtles** [HoudiniGraphql/houdini#1341]
### Describe the bug

I am witnessing a fair bit of funkiness going on with list updates since updating to 1.2.55.

The actual code I have is a fair bit more complex than this and displays some slightly stranger behaviour, but here is a minimal example & reproduction that is demonstrating at least _an_ issue with the list updates.

Given a mutation like
```gql
mutation AddItem($value: String!) {
  addItem(value: $value) {
    ...Items_List_1_insert
    ...Items_List_2_insert
  }
}
```

and a query like
```gql
query PageQuery {
  list1: items @list(name: "Items_List_1") {
    id
    value
  }
  list2: items @list(name: "Items_List_2") {
    id
    value
  }
}
```

You would expect both lists to get the new item after running the AddItem mutation, and indeed this is what happens in 1.2.54, but in 1.2.55 only one list gets updated (seemingly the second?).

See the repro link for the full code.

I assume its as a result of the changes in #1337 

### Reproduction

https://stackblitz.com/edit/houdini-1-2-55-list-insert-bug?file=src%2Froutes%2F%2Bpage.svelte

**Comment by AlecAivazis** [comment]
Thanks for taking the time to put together a reproduction - i should have some time to look into this in the next few days (hopefully tomorrow)

**Comment by AlecAivazis** [comment]
Well... that was a silly bug. Sorry about that! The fix should be deployed in a few minute

**Comment by AlecAivazis** [comment]
@jamesbirtles were there other problems with list updates that didn't get addressed

**Comment by AlecAivazis** [comment]
Great to hear!
