### ISSUE TITLE
bpchar not recognized by default even though it is the same as char and character

### ISSUE THREAD

**Issue by joleeee** [HoudiniGraphql/houdini#1347]
### Describe the bug

```
⚠️  Missing definitions for the following scalars: bpchar
Generated types will contain an any type in place of these values. To fix this, provide an equivalent
type in your config file:

{
  scalars: {
    /* in your case, something like */
    bpchar: {                  // <- The GraphQL Scalar
      type: "YourType_bpchar"  // <-  The TypeScript type
    }
  }
}

For more information, please visit this link: https://houdinigraphql.com/api/config#custom-scalars
```

From postgres doc
> bpchar (with length specifier) and char are aliases for character

**Comment by AlecAivazis** [comment]
I think you are confusing your database's types with GraphQL's. `bpchar` is not one of GraphQL standard types and as such you must teach Houdini how you want to serialize/deserializle the scalar for your frontend. [Here](https://graphql.org/learn/schema/#scalar-types) is a list of GraphQL's default scalars and [here](https://houdinigraphql.com/api/config#custom-scalars) is Houdini's documentation for how to configure it.
