### ISSUE TITLE
Rendering children raises syntax error?

### ISSUE THREAD

**Issue by m1212e** [HoudiniGraphql/houdini#1369]
### Describe the bug

When I try to render children via the new @render annotation, I get the following error:
```
❌ Encountered error in src/routes/+layout.svelte
Unexpected character '@'
```
This is my layout. Using the `<slot />` directive instead works fine. Also removing the houdini plugin from the vite config fixes the error.
```ts
</script lang="ts">
	let { children }: { children: Snippet } = $props();
</script>

<ParaglideJS {i18n}>
	{@render children()}
	 <!-- <slot /> -->
	<Footer />
	<LanguageSwitcher />
</ParaglideJS>

```

**Comment by SeppahBaws** [comment]
Svelte 5 will only be supported once it releases into stable 5.0 - but you can play around with our preview release with the `@canary` tag on npm.

**Comment by m1212e** [comment]
I see. Thought since https://github.com/HoudiniGraphql/houdini/pull/1300 is merged this is done. Thanks for the quick response, I'll give that a shot!
