### ISSUE TITLE
Specify the conditions under which automatically updating the fields works

### ISSUE THREAD

**Issue by m1212e** [HoudiniGraphql/houdini#1393]
### Describe the bug

In the [docs](https://houdinigraphql.com/api/mutation#updating-fields) it's stated that 'houdini should take care of the details for you as long as you request the updated data alongside the record’s id'. It would be helpful to know under which conditions this works. What criteria is used to determine the entities ID. This is useful to be able to understand how to structure the data in the application to ensure smart updates performed by houdini after a mutation.

I think the relevant code could be this function: https://github.com/HoudiniGraphql/houdini/blob/b93c013fc477dbaebf145ce6d2d2f74860f00c06/packages/houdini/src/codegen/transforms/addID.ts#L62

According to this behavior it could be assumed that naming the id literally "id" is a good way to approach this. But what would happen if the id is named differently such as "key" or in a case I recently had, something completely arbitrary where the graphql models were generated from a database schema and the primary key had a business domain specific name.
It would have helped me a lot if there was a quick explaination on how this works in detail or at least, what to stick to to ensure houdini behaves as expected.

**Comment by SeppahBaws** [comment]
By default Houdini looks for a field called "id" to determine the object's id. See the docs on the config: https://houdinigraphql.com/api/config#fields
![image](https://github.com/user-attachments/assets/b8348546-eb1a-4fe6-92a3-6b67c86a5e95)

The linked section in the docs also explains how you can specify a custom id name for specific types only.

Does this clear things up for you?

**Comment by m1212e** [comment]
Yes, thats exactly what I was looking for, thanks a lot!
