### ISSUE TITLE
Optimistic updates

### ISSUE THREAD

**Issue by pixelmund** [HoudiniGraphql/houdini#152]
I don't know if there currently is a way to do optimistic updates.

But let's say a user wants to like a post, instead of waiting for the response and updating the ui afterwards we should provide a way for optimistic updates, which instantly let's the cache update and if the mutation fails revert the update.

Relay Docs: [https://relay.dev/docs/guided-tour/updating-data/graphql-mutations/#optimistic-updates](https://relay.dev/docs/guided-tour/updating-data/graphql-mutations/#optimistic-updates)

**Comment by AlecAivazis** [comment]
Currently there is no way to provide an optimistic response to a mutation. 

Coincidentally this has been at the front of my brain for the past few days. The situation is rather complex when there are multiple pending mutations that have optimistic updates, especially with operations that add or remove from lists. I don't have a clear picture yet for how to implement this but I suspect we will need to introduce a layer architecture [similar to urql](https://kitten.sh/graphql-normalized-caching). If you have any ideas I'd love to hear them. I'm probably going to tackle this after I get #125 in so I can let the ideas percolate for a bit (unless someone else picks it up).

**Comment by AlecAivazis** [comment]
Wanted to get this idea down: when a user is submiting an optimistic update, their payload won't know the correct id to provide for a new element that they want to add to some list which might run into some weirdness if the optimisic id is used as the input for a mutation. Ideally, the cache would be able to recognize that the id being used as a mutation input and block the requests until the original mutation resolves and provides a correct id.
