### ISSUE TITLE
File upload support

### ISSUE THREAD

**Issue by lberezy** [HoudiniGraphql/houdini#154]
Are there plans for houdini to support file uploads?

I see in the example that there's a `Upload` custom scalar, but nothing is done with it.
I understand that custom scalars can be added but can't quite work out how to use this with the Upload type.

**Comment by AlecAivazis** [comment]
hey @lberezy! It's definitely something houdini should support. I've been working on #125 for the past few weeks but once that gets in, I'll try to find some time to put together an example to explore what's missing

**Comment by AlecAivazis** [comment]
So I spent some time looking into this and I'm not sure Houdini should take a specific stance on how file uploads happen since there are a bunch of different techniques. I think the `metadata` field is probably "enough" since a user can pass whatever objects they need to the network function. [Here's a link](https://www.houdinigraphql.com/api/query/store#passing-metadata) for more information about the new field. The example talks about queries but the `mutate` method has the same field.

I'm going to close this issue but if the `metadata` field doesn't satisfy someone's needs I'd gladly reopen it

**Comment by 524c** [comment]
Hello @AlecAivazis, how are you?
Congratulations on Houdini. I'm using it in a project.
I would like to know what is the status for upload support.
In a previous VueJS project, I used villus, which supports upload: https://github.com/logaretm/villus

I'm going to study if it would be viable to use the villus implementation for uploading in Houdini.

**Comment by 524c** [comment]
Hello @AlecAivazis, how are you?
Congratulations on Houdini. I'm using it in a project.
I would like to know what is the status for upload support.
In a previous VueJS project, I used villus, which supports upload: https://github.com/logaretm/villus

I'm going to study if it would be viable to port the villus implementation for uploading in Houdini.

**Comment by 524c** [comment]
Hello @AlecAivazis, how are you?
Congratulations on Houdini. I'm using it in a project.
I would like to know what is the status for upload support.
In a previous VueJS project, I used villus, which supports upload: https://github.com/logaretm/villus

I'm going to study if it would be viable to porting the villus implementation for uploading in Houdini.

**Comment by 524c** [comment]
Hey @AlecAivazis! Congratulations on Houdini. I'm using it in a project.

I'm studying how I could implement upload support in Houdini. Could you tell me what status this is in today?

**Comment by 524c** [comment]
Hey @AlecAivazis, congratulations on Houdini. I'm using it on a new project.
I've just implemented support for single and multiple file multipart uploads. I still need to implement tests, but if you guys can evaluate initially, I'll do PR on a different branch.

**Comment by AlecAivazis** [comment]
oh fantastic! It's funny you mention it because I also just recently implemented file uploads for an application of mine so it would be awesome to compare our approaches and see what we can add to houdini to make our lives easier 👍 

If you want to submit a PR, i'd love to take a look!

**Comment by 524c** [comment]
How fantastic. I studied Houdini, and decided to implement it in runtime/lib/network, I don't know if it was a bad choice, but in my tests it works very well. I will prepare the PR and send it next 😁

**Comment by 524c** [comment]
I'm in Brazil. It's a little late here and I'm going to sleep now. Hope I didn't do anything too weird in this PR. It's a version I just made 😁
