### ISSUE TITLE
Pass session to non-route load

### ISSUE THREAD

**Issue by neoel** [HoudiniGraphql/houdini#188]
I'm using svelte-kit and houdini (looking awesome I might add). 
BUt I'm having difficulty getting session state in the variables. 

I'm expecting something like this to work. 
```svelte
<script context="module" lang="ts">
    export function MyQueryVariables({ page, fetch, session, stuff }): MyQuery$input {
        return {
            ...session.state
        }
    }
</script>
```

But the function is only being called with page as a parameter.

**Comment by AlecAivazis** [comment]
really? huh.

If you set your session and then log it, you get undefined? I know a few people are relying on sessions to get user information, not sure why its not working for you.

@pixelmund any ideas?

**Comment by neoel** [comment]
This is my houdiniconfig:

```js
	schemaPath: 'schema.gql',
	sourceGlob: 'src/**/*.svelte',
	module: 'esm',
	framework: 'kit',
	apiUrl: 'http://graphql'
}
```

**Comment by neoel** [comment]
Weird, I'm getting passed the right props in another function, diving into it 👀

**Comment by AlecAivazis** [comment]
Ah nice catch! I'll leave this ticket open to track passing session to component loads

**Comment by fehnomenal** [comment]
FWIW the new code is located at https://github.com/HoudiniGraphql/houdini/blob/main/src/runtime/query.ts#L282.

I need this now and will try to fix the problem.
