### ISSUE TITLE
Calling queries in endpoints

### ISSUE THREAD

**Issue by neoel** [HoudiniGraphql/houdini#189]
Its ofcourse possible to just use fetch. But I think it would be nice if there is a way of using houdini in server endpoints

**Comment by AlecAivazis** [comment]
Definitely! I really like this idea. I'm not sure if the preprocessor runs on endpoint files but its absolutely worth checking out.

**Comment by Jytesh** [comment]
The preprocesser doesn't run on the endpoints, just checked
