### ISSUE TITLE
Lazy Query or option to pause query

### ISSUE THREAD

**Issue by SorenHolstHansen** [HoudiniGraphql/houdini#200]
It would be nice to have the option to use lazy queries, or skip queries

**Comment by Flexicon** [comment]
Yes! Lazy Queries are a total must have. Otherwise we basically end up having to code "hacks" around running queries if we want to run queries on certain events - like search form submission, etc.

**Comment by AlecAivazis** [comment]
supporting `@skip` is definitely something I'd like to address. Until then, you should be able to use a component inside of an `#if` block to pull this off.

**Comment by Flexicon** [comment]
True, we can do that alright. And it's pretty much how I ended up working around the limitation.

But some @skip or lazy query in general would be fantastic in the long run!

**Comment by endigma** [comment]
Any updates on this feature?

**Comment by AlecAivazis** [comment]
@endigma not yet! I've been totally consumed by the store API but once that's in place, I'm going to get back to working through these tickets. If you wanted to take a shot at it, I'd love to provide any guidance you need. Feel free to reach out on discord if you want a more direct method of getting ahold of me

**Comment by AlecAivazis** [comment]
Thinking about this some more, I think the store api was basically “lazy queries” in disguise. Now that there is a way to programmatically interact with a query you can use it wherever you want. I’ll leave this open for a bit longer in case you think of something I missed

**Comment by AlecAivazis** [comment]
I'm pretty convinced now that the store api satisfies these needs. The only thing that's really "missing" is the ability to define the lazy query inline but I think that's a separate feature
