### ISSUE TITLE
Destructuring data store

### ISSUE THREAD

**Issue by eden-omb** [HoudiniGraphql/houdini#217]
Say for instance I'm trying to query for all my products like so:
```
let { data } = query(graphql`
  query AllProducts {
    products {
      ...
    }
  }
`
console.log('products:' $data.products)
```
In this example, `$data` is a store containing an object `{ products: [...] }`. I would like for there to be some way to get a store containing only what's under the `products` key. I tried wrapping this myself using a convenience function and  `derived` from `svelte/store`, but had issues regarding Svelte only being able to work with stores being defined top-level. Is there any way to do this with native Houdini, or will I have to wrap things with RxJS or something?

**Comment by AlecAivazis** [comment]
Hey @eden-omb sorry to hear you are running into issues. 

To quickly answer your question, you shouldn't need RxJS or anything like that if you are using houdini and it's doing what it should. Can you provide an example that reproduces your error with derived stores? Also, does it need to be a store or would a reactive statement work for you?

**Comment by eden-omb** [comment]
Hey, thanks for the swift reply!

A reactive statement is how I solved it in the meanwhile, I'd like to not need the extra statement and have the store come with just the data instead of the data behind a key.

I tried a few things. As a baseline, this works just fine:
```
let products = derived(query(graphql`
  query AllProducts {
    products {
      ...
    }
  }
`.data, $data => $data.products)
console.log('products:', $products)
```

Things start getting hairy when I try to extract this into a convenience function. I want to have this be equivalent to the previous snippet::
```
let products = namedQuery('products', graphql`
  query AllProducts {
    products {
      ...
    }
  }
`)

function makeQuery(key, graphqlQuery) {
  return derived(query(graphqlQuery).data, $data => $data[key])
}
```
I get:
```
TypeError: Cannot read properties of undefined (reading 'kind')
    at Module.query (/$houdini/runtime/query.js:16:18)
    at namedQuery (index.svelte:113:24)
```
And strangely enough, when I log the `graphqlQuery` parameter, it comes out undefined!

**Comment by AlecAivazis** [comment]
Yes extracting it into a convinience function might have some strange behavior since the generated load function wouldn't be magically invoked and passed the way a query expects. Unforunately I dont think there is a way to avoid destructuring the store and still support the refetch API or the other things you can do with `query()`. I know this isn't the answer you want but I think it would be very limiting to force the `query` api to be fixed to a single return value
