### ISSUE TITLE
NocoDB compatibility

### ISSUE THREAD

**Issue by pascoual** [HoudiniGraphql/houdini#226]
To get it works with [NocoDB](https://www.nocodb.com/) graphQL API we need to add two elements to headers in /src/environment.js:
```
headers: {
...
  'Accept': 'application/json',
  "xc-auth": "Your Account Token"
}
```
Without "Accept" we have a parsing error as NocoDB send HTML instead of JSON.
Even initializing and generating Houdini like this:
```
npx houdini init -ph xc-auth="Your Account Token"
npx houdini generate -ph xc-auth="Your Account Token"
```
The NocoDB auth token is not saved somewhere, need to add it manually.

**Questions:**
1 - can Houdini add Accept for compatibility purpose ?
2 - how to save auth token on houdini init ?

**Comment by AlecAivazis** [comment]
hey @pascoual! Short answer is that houdini doesn't currently provide a way to save this configuration. Until there is something official, I recommend using something like dotenv to save your auth headers and loading the configuration before calling `generate`. Let me know if you need any more help!

**Comment by AlecAivazis** [comment]
I'm going to close this to keep things tidy. Please let me know if you need more help
