### ISSUE TITLE
Are partial results already possible with Houdini?

### ISSUE THREAD

**Issue by frederikhors** [HoudiniGraphql/houdini#233]
Hi @AlecAivazis,

I just discovered this wonderful project. Endless congratulations.

I'm currently using Urql on all projects but as you may know Urql and Svelte don't get along very well (no SSR, broken (Svelte) API and others).

I haven't used Houdini yet (I'll try in the next few hours), but one thing that keeps me from changing is the following and from a quick read it doesn't seem to me that with Houdini you can get it today: **I HOPE I AM WRONG**.

This is what the world calls: `Partial results` which Urql obtains with [Schema awareness](https://formidable.com/open-source/urql/docs/graphcache/schema-awareness/).

This is one of the biggest points in favor of solutions like urql or apollo for me. And that's one of the reasons I really enjoy working with Graphcache (normalized data) and schema awareness. Although it makes everything much heavier (in terms of development and runtime).

The UX show in the hands of the user is that the application looks native and almost offline (if the internet is fast enough). The loading spinners disappear completely and everything seems immediate.

Ultimately that's why I chose to complicate my life by choosing to develop single page apps (SPAs) instead of multi-page (server rendered) apps (MPAs).

**A very simple example is the list > detail**. As soon as I enter the details I can show the data that I have already shown in the list and download in the background (almost without the person noticing, especially if I do it in the prefetch) the data that did not appear in the list.

I know that you understand what I mean and I also know that it is difficult to understand well how to organize this thing.

Is it already possible today with Houdini?

If you answer me yes, I could pass out with joy... :smile:

**Comment by AlecAivazis** [comment]
Hey @frederikhors! Thank you for the kind words. 

At the moment, Houdini _can_ use the cache'd data from a list view to avoid that second network request if possible. Unforunately, it's an all or nothing thing so I'm not sure it fits your use case perfectly. To be concrete, the list view would have to ask for every field that is a part of the details view in order for it to use the cached data. This is described by the [`CacheOrNetwork` policy](https://github.com/AlecAivazis/houdini#cache-policy). 

Correct me if I'm wrong but it sounds like the best way to support what you want is by adding another cache policy that doesn't care if all of the data is available. As long as _any_ of it is there we should use that and then send a network request for the rest. Is that accurate? If so, it seems like a great thing to support and wouldn't take more than a few days to get out. At the moment, I am focusing on getting the website going and debugging a recent upgrade to the cache but would gladly shift focus onto this afterwards. If you felt up for it, I would also be open to providing any guidance you need to add the new cache policy.

**Comment by frederikhors** [comment]
> to avoid that second network request if possible

This is not my primary goal. The main purpose is to ensure that the user immediately has the data that he has already seen in the list a few seconds ago. If you think about it this is very powerful! Because it gives a sensation of speed to the user who does not even notice the existence of a background call for data that is not there. Obviously it depends on the app you are building but 90% of apps are like that.

> the best way to support what you want is by adding another cache policy

I don't know if this is the best way. The three current caches seem sufficient to me. You reason this way because you created the caches, but maybe it can be solved differently.

> As long as any of it is there we should use that and then send a network request for the rest. Is that accurate?

Yep. And of course you need to have indicators like "isStale", "isFetching", something like that. So I can (if I want to) show indicators of running query.

I think this "feature" is very powerful and could make a lot of people use Houdini.

The concept is well explained here and I am currently using it with Urql: https://formidable.com/open-source/urql/docs/graphcache/schema-awareness/#partial-results.

**Comment by frederikhors** [comment]
I think that a good way to help you understand how to solve it can be to create a more complex demo. I can do it myself so I learn Houdini too. But I need a few hours. I will be using StackBlitz with SvelteKit.

And can I ask you something? Do your apps use such a system today? Do you have this need? Imagining a navigation latency of 3 seconds for the API, when you go from a list to a detail do you have spinners spinning? How does it behave? Have you ever wondered this?

**Comment by AlecAivazis** [comment]
I absolutely agree it's a great feature for Houdini. All of the apps I've built with houdini have used `CacheAndNetwork` policies which doesn't have the support for partial responses, but it would be a very powerful improvement. It's a little unclear if the best move is to have partial results returned with the current cache policies or introduce a new one but I'm sure as the idea sits in the back of my head today I will have a more concrete opinion. I'm trying to think if there's ever a time you _dont_ want partial responses 🤔

**Comment by frederikhors** [comment]
> I'm trying to think if there's ever a time I wouldn't want partial responses 🤔

BINGO!

**Comment by AlecAivazis** [comment]
@frederikhors now that the cache and homepage work are done, im going to try to get this out relatively soon. Here's how I'm currently thinking each cache policy will handle partial results:

- NetworkOnly doesn't need any changes
- CacheOrNetwork: if the data is totally available in cache then there's no network call. If the data is partial, the partial value is used and a network request will also be sent. If none of the data is present, a network request will be sent to look up the information. In some sense, Cache*Or*Network behaves like Cache*And*Network if there are partial results.
- CacheAndNetwork: Cache value will be used first regardless of partial or not and then a network request will be sent for the rest.

Does that map well onto the way you think it should work?

**Comment by frederikhors** [comment]
> and then a network request will be sent for the rest

For all the data, right?

I think it's ok. 

Comparing to [urql's request policy](https://formidable.com/open-source/urql/docs/api/core/#requestpolicy) what are the differences?

Do we miss `cache-only`?

**Comment by frederikhors** [comment]
> and then a network request will be sent for the rest

For all the data, right?

I think it's ok. 

Comparing to [urql's request policy](https://formidable.com/open-source/urql/docs/api/core/#requestpolicy) what are the differences? Do we miss their `cache-only`?

**Comment by AlecAivazis** [comment]
Yea, for now it'll be all data but we can get smarter about that with time. 

I'm not against having a `CacheOnly` policy for completeness. It's one of those things that I probably wouldn't use very often but it doesn't hurt anything to have it.

**Comment by frederikhors** [comment]
Or maybe we can use `CacheOrNetwork` with some "flag".

**Comment by AlecAivazis** [comment]
@frederikhors, I just opened #240 which adds support for partial results by extending the cache policies as I described above. There is still some more testing to do but it should be ready relatively soon.
