### ISSUE TITLE
Add local directives to schema when pulling from server

### ISSUE THREAD

**Issue by ronkeiser** [HoudiniGraphql/houdini#234]
List directives appear to be removed when generating the schema using the `--pull schema` flag.

At first, I added them to my schema manually like so:

`directive @list(name: String!, connection: Boolean) on FIELD`

but this produced an error when generating unless I formatted the comments exactly the same way as in the schema transform:

```
"""
@list is used to mark a field for the runtime as a place to add or remove
entities in mutations
"""
directive @list(name: String!, connection: Boolean) on FIELD
```

According to the contributing guide, there is a [separate transform for lists](https://github.com/AlecAivazis/houdini/blob/main/CONTRIBUTING.md#internal-graphql-schema) but the link is broken.

Am I correct in assuming that the intended behavior is for list directives to remain in the generated schema, even when pulling the server schema? I'd like them to remain for local validation and it's a bit inconvenient having to manage the directives manually. 

Thank you so much for your work on this wonderful project!

**Comment by AlecAivazis** [comment]
Hey @ronkeiser! Sorry to hear you are running into issues. The `@list` directive should get automatically added by the  houdini runtime you don't need to specify it in the server schema. Is there a particular reason you need `@list` in the api's schema?

**Comment by ronkeiser** [comment]
It's just nice to have so that the IDE validates my queries/mutations and looks nice. I suppose the simple solution is to put them in a different file. 

Thank you for a quick reply!

**Comment by ronkeiser** [comment]
Ok! I'll dig into it and see what I can do.

**Comment by AlecAivazis** [comment]
Hey @ronkeiser are you still interested in giving this a shot? I'd love to get more people contributing so I'm happy to wait for you to find the time but I just merged the big cache work I have been consumed by so I can try to get something going if you prefer

**Comment by ronkeiser** [comment]
Hey, I had a chance to look at this over the weekend. At first I thought there would be quite a simple solution but now I'm perhaps more unsure of how to solve this. Let me tell you what I'm thinking:

It looks like the schema is pulled and written first, before the generator runs through all of the validations/transforms etc. In order for the schema to pass local validation when using Houdini's custom directives and list fragments, we need some of the output of the internalSchema and list transforms. (We might need `fragment All_Items_insert` to be defined, for example.)

This raises a couple of questions for me:

Should the custom directives be added selectively depending on which directives the user implements? Or is it best to keep it simple and append them wholesale like the schema transform? The first feels a little more in the 'style' of Houdini similar to the way types are generated based on naming convention. These transforms are primarily for the runtime - is it appropriate to inject another write schema step in the middle of generation or would it be better to borrow some of this functionality for when the schema is written right at the beginning? 

Ultimately I'm sure you'll do a faster/better job so I'm very happy to let you handle this. I would definitely like to look at your solution so I can learn, and I'll look for ways to contribute in the future. (I'm a huge fan of both GraphQL and Svelte).

Btw, I just saw the new API docs and they look great! I love the Pokemon example.

**Comment by AlecAivazis** [comment]
Let me think on this a bit more and once i have a halfway-decent solution I'll share it here and you can see if you want to take it on.
