### ISSUE TITLE
Clarification on updating fragments after a mutation

### ISSUE THREAD

**Issue by colllin** [HoudiniGraphql/houdini#236]
Could you help me understand how the fragments are connected to the mutation results?

I'm experiencing an issue where I send the same mutation twice with different data and results, and one time it updates the fragment, and the other time it doesn't.

1. If I send the mutation with the fields similar to `{published_at: "some_iso_string"}`, the mutation succeeds but the fragment is not updated.  When I refresh the page, the data is updated and shows that the record is now "published".

1. If I then send the mutation with the fields similar to `{published_at: null}`, the mutation succeeds AND the fragment is updated automatically.  My UI changes to remove the "unpublish" button and instead display a "publish" button.

1. Note: If I refresh the page here, the page comes back the same, confirming that the mutation was successful in a different way.

1. If I then send the mutation the first way again, with fields similar to `{published_at: "some_other_iso_string"}`, then the mutation succeeds again, and the fragment is not updated again (the page doesn't change).

1. Again, refreshing the page confirms that the item is in fact "published".

This is a screenshot of the mutation result from both mutations:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/185923/158485769-2fecc968-207a-47db-bc50-b6416c86a0c8.png">

How can I start to debug what is happening here?

**Comment by AlecAivazis** [comment]
Hey @colllin - is this example public somewhere i can take a look?  it's very strange that the UI isn't updating. Can you confirm what version you have installed?

**Comment by AlecAivazis** [comment]
Could you try using `houdini@next` and `houdini-preprocess@next`? They include a major cache update that might fix your problems.

**Comment by AlecAivazis** [comment]
I just published the changes under version `0.13.0` - let me know if you still see your issue

**Comment by AlecAivazis** [comment]
I'm going to close this since I believe it to be fixed in `0.13.0`. please let me know if you are still running into issues and we can investigate

**Comment by colllin** [comment]
Thanks so much Alec, you crushed it.  It works flawlessly now.  🙌 

Unfortunately I'm moving on from this app.  Thanks for getting us this far, I think you're onto something special here.  Good luck in the future and I hope to see you around. ✌️

**Comment by AlecAivazis** [comment]
Thanks for the kind words! Hope to hear from you again 😄
