### ISSUE TITLE
Enforce route variable function if there are non-null arguments

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#242]
A query like the following should not _require_ a variable function

```graphql
query AboutQuery($first: Int, $after: String, $last: Int, $before: String { 
   ...
}
```

**Comment by fehnomenal** [comment]
Probably also when the query has only default arguments (nullable or not).

**Comment by AlecAivazis** [comment]
I'm removing the bug tag since this no longer errors. The preprocessor now looks for the variable functions existence before generating a reference to it. While it did cover the original scenario, we did lose a "fast fail" since the user has to look at the network response to see why the error failed. 

We now need a check that a variable function exists if the query has non-nullable inputs
