### ISSUE TITLE
Supporting importing graphql documents from files

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#255]
A user should have the freedom to decide if they want to import their documents from a file or define them inline.

**Comment by vhscom** [comment]
I assume something about the way the houdini pre-processor was designed is used is what's leading to this limitation and causing issues like #201. If so, and there's an opportunity to generic graphql preprocessor of some sort I think that would be a nice feature of the design.

**Comment by vhscom** [comment]
I assume something about the way the houdini pre-processor was designed is what's leading to this limitation and causing issues like #201. If so, and there's an opportunity to generic graphql preprocessor of some sort I think that would be a nice feature of the design.

**Comment by vhscom** [comment]
I presume something about the way the houdini pre-processor was designed is what's leading to this limitation and causing issues like #201. If so, and there's an opportunity to generic graphql preprocessor of some sort I think that would be a nice feature of the design.

**Comment by vhscom** [comment]
I presume something about the way the houdini pre-processor was designed is what's leading to this limitation and causing issues like #201. If so, and there's an opportunity to generic graphql preprocessor of some sort I think that would be a nice feature of the design—and something I perceive to be lacking in all other SvelteKit GraphQL libraries I've seen to date.

**Comment by vhscom** [comment]
I presume something about the way the houdini pre-processor was designed is what's leading to this limitation and causing issues like #201. If so and there's an opportunity to create a generic graphql preprocessor I think that would be a nice feature of the design, and something I perceive to be lacking in the community.
