### ISSUE TITLE
Subscription connection using "Sec-WebSocket-Protocol" : "graphql-transport-ws" for "graphql-ws"

### ISSUE THREAD

**Issue by ClaytonFarr** [HoudiniGraphql/houdini#257]
I've been unable to get a Houdini subscriptions working due to browser not being able to connect to the GraphQL API websocket.

After digging in further, it looks like Houdini is making the connection request with the `Sec-WebSocket-Protocol` header set to `graphql-transport-ws` when the client is graphql-ws.

I've tried overriding this by manually setting the header to `graphql-ws` in the createClient `connectionParams` object but the request continues to use a `graphql-transport-ws` value.

**Is there another way the `Sec-WebSocket-Protocol` header value can be set?**

My API requires this header to be present to connect. Thanks

**Comment by ClaytonFarr** [comment]
My current environment settings - 

```js
import { browser } from '$app/env';
import { Environment } from '$houdini';
import { createClient } from 'graphql-ws';
import * as config from '$lib/config-public';

// this function can take a second argument that will
// contain the session data during a request or mutation
async function fetchQuery({ text, variables = {} }) {
	const result = await this.fetch(config.API.GRAPHQL_URL, {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json'
		},
		body: JSON.stringify({
			query: text,
			variables
		})
	});
	// parse the result as json
	return await result.json();
}

// this client is used to handle any socket connections that are made to the api
// since websockets only exist on the client, set to null on the server
const socketClient = browser ? createClient({ 
	url: config.API.GRAPHQL_WS,
	connectionParams: () => {
		return {
			headers: {
				'Sec-WebSocket-Protocol': 'graphql-ws'
			},
		};
	},
 }) : null;

export default new Environment(fetchQuery, socketClient);

```

**Comment by ClaytonFarr** [comment]
The connection request headers sent by Houdini in the browser (same whether `connectionParams` setting set in enviroment, or not) -

<img width="567" alt="image" src="https://user-images.githubusercontent.com/1226545/161832098-db006879-246e-42ac-935c-79b49b978f4b.png">

**Comment by ClaytonFarr** [comment]
The connection request headers sent by Houdini in the browser.

This is the same whether the connectionParams setting is present or not -

![Frame 1](https://user-images.githubusercontent.com/1226545/161833323-25d35993-3f3b-470c-9ed5-a56791317273.png)

**Comment by AlecAivazis** [comment]
Hey @ClaytonFarr - sorry you are running into this. I'm not really sure what the root cause is since houdini doesn't really set any custom headers or configure the websocket client (it just calls the `subscribe.next` function). Could this be an issue with the version of `graphql-ws` you are using?

**Comment by ClaytonFarr** [comment]
Hey @AlecAivazis, thanks for the quick reply and clarification. That helps to know.

I'll double-check at `graphql-ws` as well. After looking at the package initially, I presumed it would default to the latest protocol name, but crazier things have happened.

I'll circle back with what I find out.

**Comment by ClaytonFarr** [comment]
For future folks who might be banging their heads against this particular wall...

From `graphql-ws` author @enisdenjo: https://github.com/enisdenjo/graphql-ws/issues/185#issuecomment-847234413 -

> The sub-protocol of `graphql-ws` is `graphql-transport-ws` (new GraphQL over WebSocket Protocol)
> The sub-protocol `graphql-ws` belongs to `subscriptions-transport-ws` (deprecated Apollo client / Protocol)

The sub-protocol of each one _includes the key words of the other protocol's name_ 😭

I'm sure `graphql-ws` hands were tied here, but how many sunny afternoons have been consumed by this sad artifact of history?

Thanks again @AlecAivazis for the quick help to look in the right direction.
