### ISSUE TITLE
TypeError: this.data[startingIndex] is undefined 

### ISSUE THREAD

**Issue by ClaytonFarr** [HoudiniGraphql/houdini#258]
I'm getting the error below in the browser on a route with a single mutation and subscription. I'm not sure yet what could be causing it.

**Any suggestions for how to debug or resolve this?** 

Thanks for any help

## Console Error

```console
Uncaught (in promise) TypeError: this.data[startingIndex] is undefined
    resolveLayer storage.js:152
    mutation mutation.js:80
    instance callback.svelte:52
    run index.mjs:18
    mount_component index.mjs:1803
    flush index.mjs:1067
    init index.mjs:1895
    Root root.svelte:920
    createProxiedComponent svelte-hooks.js:341
    ProxyComponent proxy.js:242
    Proxy<Root> proxy.js:349
    initialize start.js:706
    _hydrate start.js:1606
    start start.js:1643
    <anonymous> callback:629
storage.js:152:13
```

## Route Code

```html
<script lang="ts">
	import { onMount } from 'svelte';
	import { browser } from '$app/env';
	import { goto } from '$app/navigation';
	import { query, mutation, subscription, graphql } from '$houdini';
	import * as config from '$lib/config-public';

	export let installCode: string;

	const sendExchangeRequest = mutation(graphql`
		mutation SendExchangeRequest($installCode: String!) {
			ExchangeInstallCode(input: { installCode: $installCode })
		}
	`);
	onMount(() => {
		try {
			sendExchangeRequest({ installCode });
		} catch (error) {
			goto('/oauth/error?type=codeError');
		}
	});

	let { data: matchingExchangedCodes } = subscription(
		graphql`
			subscription MatchingExchangedCodes($installCode: String!) {
				AccountReadModels(filter: { lastRequestCode: { eq: $installCode } }) {
					id
					authExpiresAt
					lastRequestCode
				}
			}
		`,
		{ installCode }
	);
</script>

<template lang="pug">

  +if('!!$matchingExchangedCodes?.AccountReadModels')
    p Connected!
    +else()
      p Connecting...

</template>

```

**Comment by AlecAivazis** [comment]
Hey @ClaytonFarr - looks like you're running into an issue caused by the recent optimistic response patch. Let me see if I can figure out what could be happening on one of my apps. Is your project public or could you put together a small reproduction so I can make sure to fix the issue?

**Comment by AlecAivazis** [comment]
Oh, interesting. So I think the issue is the mutation inside of `onMount`. could you try putting that on a button or something so we can verify?

**Comment by AlecAivazis** [comment]
I'm pretty sure #259 will fix this. Even if it doesn't, it's a situation I didn't think about and needed to cover so thanks for bringing this up. Going to deploy this now so you can tell me if we need to reopen it

**Comment by ClaytonFarr** [comment]
Wow @AlecAivazis , quick hands 🙌

It looks like the error still shows up when you move the mutation outside of onMount and call it explictly as well

**Comment by ClaytonFarr** [comment]
Thanks Alec, when that's ready I'll test it again and get you a sample repo if it has issues. Really appreciate the help

**Comment by AlecAivazis** [comment]
My guess is that this is caused when a mutation resolves before a query is fired - does that sound like what's happening for you?

**Comment by ClaytonFarr** [comment]
Perhaps. In this case the mutation is firing before the subscription is created and called - at least when the mutation is in onMount. 

When the mutation was called via a button it would have been after the subscription creation (and still crated console error)

**Comment by ClaytonFarr** [comment]
I tried updating to the new package (0.13.8) but it didn't come down. I'm guessing these take a while to publish to npm?

I'll try this again a bit later and circle back. Thanks Alec

**Comment by AlecAivazis** [comment]
I'm running into a problem with the changesets action. If you want to test the changes locally, you can edit the `$houdini/runtime/cache/storage.js` and add the following block on line 234 (after the check for `startingIndex === null`):

```
// if we are resolving the base layer make sure we start at zero
if (startingIndex === -1) {
    startingIndex = 0
}
```

**Comment by AlecAivazis** [comment]
Okay, looks like `0.13.8` has been deployed now. thanks for being patient

**Comment by ClaytonFarr** [comment]
@AlecAivazis, that fix removed the error on my end too 💯 Thanks!

**Comment by AlecAivazis** [comment]
Great to hear!
