### ISSUE TITLE
Better configuration?

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#262]
Custom id's highlighted an area for possible improvement for the API. Right now, the config file is getting very bloated with all sorts of different things. The type config feels especially clunky for imposing a team's conventions. For example, if a user did not have a single entity that used `id` or the `Node` interface, they would have to update a very large object every time a new type is added to their schema.

There are probably some very good posts out there about different ways to approach this problem.

**Comment by DanielHritcu** [comment]
Is using [graphql-config](https://www.the-guild.dev/graphql/config) considered ?

I like the way KitQL makes use of it, feel's a bit over the hand to duplicate the schema/documents in houdini.config and graphql-config.

Maybe even use it for multiple endpoints in the future.

**Comment by AlecAivazis** [comment]
> Is using [graphql-config](https://www.the-guild.dev/graphql/config) considered ?

yea it was considered but we ultimately decided that we wanted to be able to control the format and enforce javascript for logic.

I'm closing this now that plugins can modify config files. It's still not _ideal_ but it's more than enough until there is a more concrete use case
