### ISSUE TITLE
Typescript type generation with embedded fragments for queries

### ISSUE THREAD

**Issue by Penait1** [HoudiniGraphql/houdini#265]
Hi,

We're using fragments in our queries.
For Example:

```
fragment<PostalAddress>(graphql`
  fragment PostalAddress on PostalAddressModel {
    id
    city
    country
  }`, null) 


const { data } = query<GetPerson>(graphql`
	query GetPerson($id: Int!) {
		GetPerson(a0: $id) {
			name
                        email
                        postalAddress { 
                          ...PostalAddress
                        }
		}
	}
`);
```

The problem that we are facing is that the following typescript file gets generated roughly:

```
export type GetPerson$result = {
    readonly GetPerson: {
        readonly postalAddress: {
            readonly $fragments: {
                PostalAddress: true
            }
        }
        readonly name: string,
        readonly email: string
    }
};
```

While we would expect

```
export type GetPerson$result = {
    readonly GetPerson: {
        readonly postalAddress: {
            readonly id: string,
            readonly city: string,
            readonly country: string    
        }
        readonly name: string,
        readonly email: string
    }
};
```

How can we fix this? This breaks our auto completion within our IDE and makes typescript compilation complain that we are accessing attributes that don't exist.

**Comment by AlecAivazis** [comment]
Hey @Penait1!

Unforunately, this is working as intended. The idea is that a component or route should not depend on data they did not explicitly ask for. This seems like a big constraint but houdini is forcing you to build your app in a future-proof way.  For more information, check out the [relay docs](https://relay.dev/docs/principles-and-architecture/thinking-in-relay/#data-masking). On top of that, fragment definition should be tightly associated with a component and not used as a graphql-only abstraction (ie you shouldn't pass `null`) - if you are trying to use do something with the postal address, that logic should get moved to its own component with a fragment.
