### ISSUE TITLE
don't run husky install on projects depending on houdini

### ISSUE THREAD

**Issue by oplik0** [HoudiniGraphql/houdini#278]
Currently, the posinstall script tries to work even for projects that don't have husky installed. However, because I'm using houdini in a monorepo, where it's not installed in the main repository folder, and I am using husky, it breaks on this step with `Error: .git can't be found (see https://git.io/Jc3F9)` - which isn't caught.

This could be fixed just by adding more conditions to the error handler, but I think a better solution would be to move this step from `postinstall` to `prepare` (which is now suggested in [Husky docs](https://typicode.github.io/husky/#/?id=install), see https://github.com/typicode/husky/issues/884), as `prepare` scripts don't run on dependencies at all.

Edit: I just realized houdini is using yarn, and it stopped supporting `prepare` in v2. It appears the way Husky recommends to avoid pushing the script onto people depending on a package is to use [`pinst`](https://github.com/typicode/pinst) by the same author to remove postinstall on `prepack` hook: https://typicode.github.io/husky/#/?id=yarn-2
```json
"scripts": {
    "postinstall": "husky install",
    "prepack": "pinst --disable",
    "postpack": "pinst --enable"
  }
```

**Comment by AlecAivazis** [comment]
Oh good catch! Thanks for submitting a fix 👍
