### ISSUE TITLE
`isRoute` is rather naive

### ISSUE THREAD

**Issue by fehnomenal** [HoudiniGraphql/houdini#281]
I like to colocate components to the only route where they are used, so I end up with something like `src/routes/__layout.svelte` which uses `src/routes/__layout/header/Searchbar.svelte`. `isRoute` does what it's supposed to do and determines (by checking the file name prefix for `src/routes`) `Searchbar` is a route and not a component.

My easy workaround is to put such components into `/lib` or whatever but I think `isRoute` should be more smart, i.e. also taking the svelte config into account (https://kit.svelte.dev/docs/configuration#files).

**Comment by AlecAivazis** [comment]
Ah yea, totally something we should support. Want to take a shot at implementing it? If not, I'll try to get to it this week

**Comment by fehnomenal** [comment]
Well, I don't know when I can find time for it...

I wish we could utilize `load_config` from https://github.com/sveltejs/kit/blob/28139749c4bf056d1e04f55e7f955da33770750d/packages/kit/src/core/config/index.js#L30 but it is not exported in the published npm package. Maybe something with git dependencies?

**Comment by jhubbardsf** [comment]
Shouldn't a component located without the routes direction be prefixed with an underscore? So _Searchbar.svelte. Which would prevent it from being a route (which it should be anyways, since you don't want users to be able to navigate to it). Not sure if Houdini takes that into account.

**Comment by fehnomenal** [comment]
Yeah, you can exclude whole folders by prefixing them with `_`. And no houdini does not take this into account hence the feature request.
