### ISSUE TITLE
Add way to mark data as stale/invalid

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#287]
### Discussed in https://github.com/HoudiniGraphql/houdini/discussions/286

<div type='discussions-op-text'>

<sup>Originally posted by **frederikhors** April 23, 2022</sup>
Is there an invalidate() api like https://formidable.com/open-source/urql/docs/graphcache/cache-updates/#invalidating-entities?</div>

**Comment by fehnomenal** [comment]
Maybe https://kit.svelte.dev/docs/loading#output-dependencies can be used? I.e. the generated load would put all query names into the `dependencies` array and the user would be able to invalidate individual queries (but I guess it would execute the whole load function again?).

**Comment by jycouet** [comment]
I think that this one might get a priority. What do you think?

To move forward, what do we want to support?
- `invalidate("TYPE")`
- `invalidate("TYPE", "KEY")`

**Comment by frederikhors** [comment]
I think we should support everything. The invalidation is CRITICAL.

Btw thanks for all your work @jycouet @AlecAivazis!

**Comment by AlecAivazis** [comment]
I think this is part of a larger conversation concerning how we want to organize the imperative API. Ideally we need to invalidate, all instances of a type, a type with a specific id, and a field within a particular type. I think the API for doing this can get quite unwieldy unless we impose a little organization into the overall structure. I started fleshing out some of my thoughts here: #58

**Comment by jycouet** [comment]
Let's close this one in favor of #58 which will take care of this.

**Comment by AlecAivazis** [comment]
I'm going to reopen this since it will come as a second effort once #748 gets merged

**Comment by frederikhors** [comment]
@AlecAivazis is this available as of today?

**Comment by jycouet** [comment]
Tests are passing, PR will be done later today 🥳

A lot of cool things will happen in the coming days 👀
