### ISSUE TITLE
Parser error with mixed type and value imports

### ISSUE THREAD

**Issue by fehnomenal** [HoudiniGraphql/houdini#289]
Since some time kit generates a `tsconfig.json` with some defaults and forces us to extend from it (https://github.com/sveltejs/kit/blob/60b3e9e9f489befe64d95afc812b1fcb921563e2/packages/kit/src/core/sync/write_tsconfig.js#L82). This file mainly sets
```json
		"importsNotUsedAsValues": "error",
		"isolatedModules": true,
		"preserveValueImports": true
```
which means types must be imported with `import type`. The example seems outdated in this regard and just uses a normal value import.

While writing queries/mutations/fragments vscode helpfully suggests the correct imports and I end up with something like
```ts
   import { fragment, graphql } from '$houdini';
```

After writing the gql string I generate and try to add the type and vscode insists on generating
```ts
  import { fragment, graphql, type GetMyCartItems } from '$houdini';
```
ESLint is happy but now preprocessing fails with (originating from the `preprocess-esm/index.js` file)

> Error while preprocessing /.../src/routes/warenkorb.svelte - Unexpected token, expected "," (3:26)

The workaround is simple:
```ts
  import type { GetMyCartItems } from '$houdini';
  import { fragment, graphql } from '$houdini';
```
but I did this so often I can no longer be bothered with this...

Could this be related to the second parsing phase with babel?

**Comment by AlecAivazis** [comment]
Hm, interesting. I'll try to find some time to dig into this to see what could be causing it. Babel is configured to parse the file with the typescript parser so I would be surprised if it's causing the issue 🤔

**Comment by vhscom** [comment]
Just bumped into this as well running `npx houdini init`. Error was:

```term
Error: Encountered error parsing src/lib/shared/components/calendar/Calendar.svelte: Unexpected token, expected "," (2:22)
```

The line of code indicated by the error:

```ts
  import dayjs, { type Dayjs } from 'dayjs';
```

Column 22 is the end of the `type` keyword so I refactored it to:

```ts
import dayjs from 'dayjs';
import type { Dayjs } from 'dayjs';
```

And it resolved the error.
