### ISSUE TITLE
Rapid queries resulting in overlapping responses

### ISSUE THREAD

**Issue by fehnomenal** [HoudiniGraphql/houdini#290]
While building a search-as-you-type text field I went with updating a query parameter on each input and thus firing `load` for every keystroke without throttling.
During typing some requests returned a response **after** the **next** request has responded. So I got the previous results displayed.

I could imagine to solve this either by throttling the `fetchQuery` call (but how can this be configured? and how does this work with ssr?) or by storing an `AbortController` from https://www.npmjs.com/package/node-abort-controller for each query and abort it if existing.

I like the second approach more and am willing to implement it.

Any thoughts?

**Comment by AlecAivazis** [comment]
As long as we have a reasonable polyfill for the browser I think having a way to abort a request is a good approach 👍

**Comment by jycouet** [comment]
I would add a `debounce` with ~300ms on the input field.

**Comment by AlecAivazis** [comment]
I totally misunderstood your point initially but now that I took some time to understand what you were suggesting I can give you a better answer. 

As of `v0.15.0`, you can pass a `metadata` field to a document store's `fetch` method which will get passed all the way to your network function. You can see an example [here](https://www.houdinigraphql.com/api/query/store#passing-metadata).  That should work for one-off cases like you are asking about for a search input but it sounds like you are also looking for a way to do this globally at a network level. 

At the moment, that kind of global configuration is very clunky - it all has to get baked into the one function you pass to your client. I think houdini will inevitably have some abstraction for build more complicated network logic but I'm really not sure what that looks like. If you have any ideas, I'd love to here them.

**Comment by AlecAivazis** [comment]
I'm actually going to close this in favor of #365 so we can consolidate the conversations
