### ISSUE TITLE
Paginated list insertion not working

### ISSUE THREAD

**Issue by pixelmund** [HoudiniGraphql/houdini#305]
Hey i don't know if i'm doing something wrong or this is a bug, but for me paginated lists doesn't insert correctly anymore. 

> The removal of notes works fine!

Reproduction:

Go to: [https://skytro.up.railway.app](https://skytro.up.railway.app) and sign in with the following credentials:

```
User: test-houdini@test.com
PW: 123456
```

Navigate to https://skytro.up.railway.app/notes and try to create a note.
The created note only appears after reloading the page and if you look into the console it shows an note beeing added but it is null. 
If you check the network tab the response looks correct.

Maybe i have an issue somewhere in my Code, those are the files which handle the notes feature:

[notes/index.svelte](https://github.com/pixelmund/svelte-kit-boilerplate/blob/main/src/routes/notes/index.svelte) 
[notes/_create.svelte](https://github.com/pixelmund/svelte-kit-boilerplate/blob/main/src/routes/notes/_create.svelte) 
[notes/_note.svelte](https://github.com/pixelmund/svelte-kit-boilerplate/blob/main/src/routes/notes/_note.svelte)

**Comment by AlecAivazis** [comment]
Oh no! That's not good, I'll try to reproduce this in the next few days. Would it be possible to run the sveltekit app locally?

**Comment by pixelmund** [comment]
I restarted the project a few weeks ago. I can probably try an older version and find out which one broke it. You can run it locally either through railway which is free or via local postgres where you'd have to add the DATABASE_URL inside the .env.

**Comment by pixelmund** [comment]
I think you have to set a variable inside railway: `VITE_COOKIE_SECRET`, it's used to encrypt the cookie sessions.

**Comment by AlecAivazis** [comment]
Perfect that worked! I'll let you know what I find 👍

**Comment by AlecAivazis** [comment]
Ah ha! I think i figured it out, this was definitely subtle but it's definitely houdini's fault. I'll get a fix out ASAP

**Comment by pixelmund** [comment]
Awesome!

**Comment by AlecAivazis** [comment]
I just merged #306 which fixes the issue (confirmed on my local version), ill let you know once its deployed @pixelmund

**Comment by pixelmund** [comment]
Thank you! I've just confirmed it's fixed and ofc i'll let you know if i run into any issues.
