### ISSUE TITLE
Preprocessor with external files

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#325]
At the moment, if a user wants to use the preprocessor to generate a load function they must define their queries inline and use the appropriate "inline" function for the runtime. It would be nice to be able to somehow tell the preprocessor to generate a load function for a store. 

An example api: 

```svelte
<script context="module">
    import ViewerProfileStore from '$houdini/stores/ViewerProfile'

    export const routeStore = ViewerProfileStore
</script>

{$ViewerProfileStore.data.viewerProfile.firstName}
```

**Comment by jycouet** [comment]
I put my notes here, because I want to explore this later 👍

## Inline
It relies on `TemplateExpression` prefixed with `graphql`
```svelte
<script>
    import { query, graphql } from '$houdini'

    const { data } = query(graphql`
        query AllTodoItems {
            items {
                text
            }
        }
    `)
</script>
```

## External
With:
```svelte
<script>
    import { GQL_AllTodoItems } from '$houdini'

    $: browser && GQL_AllTodoItems.fetch()
</script>
```

How to identify a store?
1.0 prefix `GQL_`
2.1 method `.fetch(`
- It's a query
- having flag SSR?
- having flag Blocking
- No need context
- No need event

2.2 method `.mutate(`
- It's a mutation
- No need context

...

**Comment by AlecAivazis** [comment]
unforunately matching the `GQL_` prefix doesn't work for users that are importing stores directly or creating their own. If we had some kind of module-level variable that we could look for, we could just generate the code to reference that variable so we wouldn't have to be very clever

**Comment by jycouet** [comment]
I'm not sure what you mean by `module-level variable`?

Anycase, we need a mechanism to say "Hey, on this store please do this and that preprocessor part". Like an Opti-In preprocessor function.

I think we need a bit of usage to see in what direction to go.

**Comment by AlecAivazis** [comment]
i meant something like this (the important part being that the variable is exported from the module context). SvelteKit uses this pattern in a few places as a way to provide configuration for the route (for example, when [disabling prerendering](https://kit.svelte.dev/docs/page-options#prerender).

```
<script context="module">
    import ViewerProfileStore from '$houdini/stores/ViewerProfile'

    export const routeStore = ViewerProfileStore
</script>
```

**Comment by AlecAivazis** [comment]
Just a heads up for people, support for this will be added as part of the upcoming work to support the new KitQL api 👍
