### ISSUE TITLE
Provide API for fetching data without caching the result

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#356]
In situations like search, the value doesn't always need to be cached. We should give users a way to fetch, paginate, etc. without writing the values to cache

**Comment by jycouet** [comment]
With a flag like `skipCaching`?

**Comment by AlecAivazis** [comment]
I think the flag should probably show up in 2 different places: on `fetch` for  one-off situations as well a query-level configuration value. Maybe a new `CachePolicy`, something like `NoCache`

**Comment by jycouet** [comment]
Yes, `CachePolicy`: `NoCache` is probably the easiest & simplest solution 👍
Adding in the doc that it's doing a network request and NOT caching data.

**Comment by MattiasMartens** [comment]
I've created a PR to implement this feature, but tests don't work on my machine so I am unable to verify it (I describe the error in the PR). Currently working on patching it over to our own environment so we can test it live against our code.
