### ISSUE TITLE
Infer inline query variables from route parameters

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#372]
If a route's path contains parameters that match a query's variables, the user shouldn't have to define a variable function if its just going to do `({params}) => params`.  

Questions:
- How do we handle massaging custom scalars?

**Comment by AlecAivazis** [comment]
`/foo/[id=MyCustomScalar]` could automatically match and unmarshal for the variables

**Comment by jycouet** [comment]
I would love to have queryParam as well.
`/foo?pageSize=20`

I was thinking that we know that `pageSize` is an `Int` in the schema, so we don't need to specify the `scalar`. No?
Either the `unmarshal` works either we throw?

`/foo?startFrom=2000-01-01T00:00:00.000Z`
