### ISSUE TITLE
houdini preset-cli

### ISSUE THREAD

**Issue by david-plugge** [HoudiniGraphql/houdini#382]
It would be nice to have a [preset](https://github.com/preset/preset) to add houdini to an existing sveltekit app.

**Comment by david-plugge** [comment]
I didnt even know about `npx houdini init`, no idea how i missed that.
I´ve tested the init command with a new sveltekit project, it seems like the init command just adds the `houdini.config.js` and `houdiniClient.js` files. With a svelte-adder or preset the preprocessor, watch-and-run plugin and the houdini alias could be added aswell.
In addition an option to use either js or ts would be pretty nice, or maybe even autodetect that by looking for a tsconfig.json.

A little off topic, it would be nice to set the pull headers in the `houdini.config.js` and make use of env vars.

**Comment by jycouet** [comment]
FYI 1/ new SvelteKit (after .359); 
- Has a problem with fetch `POST`
- Change some config files (`vite.config.js` will be needed now)
=> Let's keep this out of this issue.

FYI 2/ we will update the KitQL doc to simplify the installation process with `npx houdini init`

---

We already started improving the onboarding with: https://github.com/HoudiniGraphql/houdini/pull/381
And your inputs are very valuable, thx 👍

If we manage to do the preprocessor & co directly with `npx houdini init`, we don't need svelte-adder or preset, correct?

**Comment by david-plugge** [comment]
> If we manage to do the preprocessor & co directly with `npx houdini init`, we don't need svelte-adder or preset, correct?

Yes there is no need for multiple setup tools.
The init command should just create a completely working setup.
