### ISSUE TITLE
Optimistic Fetches

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#383]
The computation for partial data relies on running into a field we've already seen before. We should be able to provide a hint to the cache when looking up the data so it can infer the result and potentially grab a larger partial result

a possible API:

```javascript
store.fetch({ variables: {}, optimistic: { ... } }) 
```

**Comment by jycouet** [comment]
Just so that I don't forget my internal brainstorming ^^

I see 2 options:

1/ Free, I put what I want, it "just" needs to be type compliant
```ts
store.fetch({ variables: {}, optimistic: { 
  id: "123",
  name: "teststests"
  activities: [
    { id: 1, name: "Bike" }
  ] 
} }) 
```

2/ Using a helper to be smart
```ts
store.fetch({ variables: {}, optimistic: { 
  cache.get("List of Maching Queries (with the type)", inputs_of_the_query)
} }) 
```

**Comment by AlecAivazis** [comment]
> 
> 1/ Free, I put what I want, it "just" needs to be type compliant
> 
> ```ts
> store.fetch({ variables: {}, optimistic: { 
>   id: "123",
>   name: "teststests"
>   activities: [
>     { id: 1, name: "Bike" }
>   ] 
> } }) 
> ```

Would be cool if we only made the user provide the ids if they are okay with the current cached result

> 
> 2/ Using a helper to be smart
> 
> ```ts
> store.fetch({ variables: {}, optimistic: { 
>   cache.get("List of Maching Queries (with the type)", inputs_of_the_query)
> } }) 
> ```

I'm not sure I'm following what this would do. It seems like a mistake to couple yourself to the body of another query but maybe there's a situation I'm not seeing

**Comment by jycouet** [comment]
The main point was to have the 2 versions.

1/ Free to go crazy 
``` js
store.fetch({ variables: {}, 
  optimistic: { 
    ... 
  }
}) 
```

2/ To solve some specific use cases. Maybe it's more:
``` js
store.fetch({ variables: {}, 
  optimisticSelector: (id) => id === variables.id, // we know the store, so the return type. Select unique item is possible?
  optimistic: { 
    ...
  }
}) 
```

Not couple to the query, to the type directly.
Anyway not right now, need more thoughts.
