### ISSUE TITLE
Fragment "Mutation" doesn't exist error

### ISSUE THREAD

**Issue by Nukiloco** [HoudiniGraphql/houdini#390]
Currently when running houdini generate, I been getting this error in my ``mutation.gql`` file.
```
houdini generate

🎩 Generating runtime...
❌ Encountered error in src/lib/server/modules/user/schema/_Mutation.gql
Fragment "Mutation" doesn't exist in its own document?!
```
This is the source code to the file:
```
type Mutation {
	test: String
}
```

I don't get what I'm doing wrong here?

**Comment by jycouet** [comment]
This part: 

```graphql
type Mutation {
	test: String
}
```

Is a `typedef`. It's server-side to describe your schema.
_I usually use another extension: `mutation.graphql` to not be confused._

---

If you want to trigger a mutation, it would be something more like:
`mutation.gql`
```graphql
mutation MyMutationName {
  test
}
```

**Comment by Nukiloco** [comment]
Ah so houdini is reading my server typedefs. Though I thought houdini needed the typedef schema files?

**Comment by Nukiloco** [comment]
@jycouet 
One of the repos/stackblitz I was looking at was this one. And the houdini config seems to point to those files.
https://stackblitz.com/edit/jycouet-kitql-qj8cbn?file=.kitql.yaml,.graphqlrc.yaml,houdini.config.js,src%2Flib%2Fmodules%2F__init%2Ftypedefs%2F_Query.graphql&title=KitQL%20Demo%202

**Comment by jycouet** [comment]
Correct, 
that's why I put typedefs with ".graphql"
And operations with ".gql"

Like this, you can set good parameters (globs) in "houdini.config. js"

**Comment by Nukiloco** [comment]
I set the ``schemaPath`` to be instead ``src/lib/server/modules/**/schema/*.gql`` in the config file which works now. Thanks for the help!
