### ISSUE TITLE
VSCode preprocessor types

### ISSUE THREAD

**Issue by david-plugge** [HoudiniGraphql/houdini#393]
VSCode doesnt give me type intellisense on the preprocessor.

![image](https://user-images.githubusercontent.com/59972093/178117672-9d4dd7b6-de2a-48e0-a5c4-7769611d9043.png)

![image](https://user-images.githubusercontent.com/59972093/178117681-1efbcb14-45b1-44b4-b0c9-be51a4fc28df.png)

**Comment by AlecAivazis** [comment]
Thanks for reporting this.

I think all that's missing is a `types` entry in [here in package.json](https://github.com/HoudiniGraphql/houdini/blob/main/package.json#L18) that points to `build/preprocess/index.d.ts`. If you wanted to submit a PR, I'd happily review it otherwise I'll try to get to it if I find some time soon

**Comment by david-plugge** [comment]
> I think all that's missing is a `types` entry in [here in package.json](https://github.com/HoudiniGraphql/houdini/blob/main/package.json?rgh-link-date=2022-07-09T18%3A15%3A47Z#L18) that points to `build/preprocess/index.d.ts`

I´ve already tried that, still doesnt work for me.
```json
"./preprocess": {
	"import": "./build/preprocess-esm/index.js",
	"types": "./build/preprocess/index.d.ts",
	"require": "./build/preprocess-cjs/index.js"
}
```

After a bit of searching i´ve found out that there is a key called `typedVersions`.
This workes for me:
```json
"exports": {
  ".": {
    "types": "./build/cmd/index.d.ts"
  },
    "./preprocess": {
    "import": "./build/preprocess-esm/index.js",
    "require": "./build/preprocess-cjs/index.js"
  }
},
"typesVersions": {
  "*": {
    "preprocess": ["build/preprocess/index.d.ts"]
  }
}
```

I will create a PR
