### ISSUE TITLE
Preprocessor configFile relative path

### ISSUE THREAD

**Issue by david-plugge** [HoudiniGraphql/houdini#395]
In a monorepo i have a project at `/packages/shop`.
To get the preprocessor working i have to set the relative path from the monorepos root directory. If the path changes i have to update the config file too.
```js
houdini({
  configFile: 'packages/shop/houdini.config.js'
})
```
This is working for me aswell, but it is somewhat ugly and i will always have to look it up for new projects
```js
houdini({
  configFile: new URL(import.meta.url).pathname.replace('svelte.config', 'houdini.config')
})
```

Beeing able to just put `./houdini.config.js` in there would be pretty nice.
Or even just a `.` and resolve the config from the current directory with its default name.
When working in a monorepo it could also check for a config file in the root directory and if there is none look up the current folder.

**Comment by AlecAivazis** [comment]
Oh yea good idea! [Here's](https://github.com/HoudiniGraphql/houdini/blob/70f9f71065767075de037b9dd4ac190101588037/src/common/config.ts#L642) where that logic lives

**Comment by david-plugge** [comment]
```
Cannot find module '/home/david/dev/atelierJS/atelierJS/houdini.config.js' imported from /home/david/dev/atelierJS/atelierJS/packages/atelierjs-website/node_modules/.pnpm/houdini@0.15.5/node_modules/houdini/build/preprocess-esm/index.js
```
I just cant solve this problem. The svelte extension seems to import the svelte.config.js from the root of the monorepo and so does not find houdini.config.js. This is what i´ve tried:
```js
'./houdini.config.js'

'./packages/shop/houdini.config.js'

path.resolve('./houdini.config.js')

path.resolve('./packages/shop/houdini.config.js')

new URL(import.meta.url).pathname.replace('svelte.config', 'houdini.config')
```
