### ISSUE TITLE
Queries are broken when prerendering

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#400]
At the moment, prerendering a query breaks with the following error: `Attempted to access session from a prerendered page. Session would never be populated.` We need to update `getHoudiniContext` so that it doesn't fail here. Ideally, we could find a way to surface this error if we are using `session` in the network function during prerender

**Comment by phenomen** [comment]
I use graphql to generate website sitemap from `sitemap.xml.js` endpoint (fetching page/product slugs and returning XML). This feature is critical for SEO. It works with `graphql-request` but I have no idea how to do it with `houdini` since `generate` throws an error:
```
❌ Encountered error in src/houdiniClient.js
Syntax Error: Unexpected Name "import".
```
