### ISSUE TITLE
Support query/mutation in endpoint

### ISSUE THREAD

**Issue by jycouet** [HoudiniGraphql/houdini#402]
See: https://github.com/jycouet/kitql/issues/174

**Comment by phenomen** [comment]
I generate website sitemap from `sitemap.xml.js` endpoint (fetching page/product slugs and returning XML). This feature is critical for SEO. It works with `graphql-request` but I have no idea how to do it with `houdini`. I added `js` extension to `houdini.config.js` but `generate` still throws an error:
```
❌ Encountered error in src/houdiniClient.js
Syntax Error: Unexpected Name "import".
```
