### ISSUE TITLE
Allow make path not `$houdini`?

### ISSUE THREAD

**Issue by endigma** [HoudiniGraphql/houdini#412]
Having a dollar sign amidst a sea of `.something` for hidden folders filled with codegen seems unnecessarily "look at me", perhaps this can be configurable?

I would much rather to be able to put this into `src/lib/gen/houdini` next to other codegen things

**Comment by AlecAivazis** [comment]
Thanks for opening this @endigma! It's definitely on our list of things to do when we  have time. I'm going to close this issue since its a duplicate of #391. Feel free to join the conversation over there 👍
