### ISSUE TITLE
Wrong variable function input for inline component queries

### ISSUE THREAD

**Issue by fehnomenal** [HoudiniGraphql/houdini#421]
I wrote about this already here: https://github.com/HoudiniGraphql/houdini/pull/366#issuecomment-1175407910 but now the problem resurfaced while trying to upgrade another project to the new store API.

Basically the problem is that the variable function only gets two values when being executed in the client, namely `props` and `session`:
https://github.com/HoudiniGraphql/houdini/blob/8be5953ae4237ef0f84346c595446ba8cd3feaee/src/preprocess/transforms/query.ts#L735-L764

My old code is using `stuff` via `page` but this is obviously no longer working.

Directly using `$page.stuff...` does not work because "Cannot reference store value inside <script context="module">".

Route `...Variable` functions get a `LoadEvent` passed. Can we try to pass component `...Variable` functions a trimmed `LoadEvent`? Something like:

```ts
type TrimmedLoadEvent = {
	params: Record<string, string>;
	props: Record<string, string>;
	routeId: string | null;
	session: App.Session;
	stuff: Partial<App.Stuff>;
	url: URL;
}
```

**Comment by fehnomenal** [comment]
Btw: my current workaround is by defining the query in a gql file and calling via `$: browser && GQL_...fetch({ variables: { foo: $page.stuff... } })`

**Comment by jycouet** [comment]
Thanks for reporting this @fehnomenal 
Good workaround going a bit more manual while this is not supported in the preprocessor yet.

Most of `TrimmedLoadEvent` is already in place with `getHoudiniContext()`. 
Now, _"just"_ need to support all items and push them to the preprocessor variables function.

How urgent do you need it in preprocessor? Do you want to give it a shot?

**Comment by AlecAivazis** [comment]
Ah crap! I totally forgot to verify that we fixed your `stuff` issue before we merged that - so sorry! I'll try to find some time this week to address this is no one else gets to it. 

Also, just a heads up it looks like `$page.stuff` might be removed at some point: https://github.com/sveltejs/kit/issues/4911

**Comment by fehnomenal** [comment]
> How urgent do you need it in preprocessor? Do you want to give it a shot?

Well, as the project is just for a side business and not my day job and there is a workaround available it is not on the top of my priority list.

When I get a few minutes I will tackle it.

**Comment by fehnomenal** [comment]
> Also, just a heads up it looks like $page.stuff might be removed at some point

Wow, thanks for mentioning that. We'll see if there and what will be a replacement.

Maybe it's time for me to fully switch to stores and ditch the inline queries

**Comment by AlecAivazis** [comment]
I was able to sneak in some time tonight so I put #423 together. Hopefully that addresses your issue
