### ISSUE TITLE
Houdini doesn't recognise the socketClient!?

### ISSUE THREAD

**Issue by OlmoDalco** [HoudiniGraphql/houdini#425]
Client was set up according to the docs:

```ts
import { HoudiniClient, type SubscriptionHandler } from '$houdini/runtime'
import { createClient } from 'graphql-ws';
import { browser } from '$app/env'

async function fetchQuery({ fetch, session, text = '', variables = {} }) {...}

const socketClient: any | null = browser ? new createClient({
	url: "ws:/localhost:3200/graphql",
}) : null;

export default new HoudiniClient(fetchQuery, socketClient)
```

but i still get the following error message: **The current Houdini Client is not configured to handle subscriptions. Make sure you passed a socketClient to HoudiniClient constructor.**

**Comment by fehnomenal** [comment]
Are you trying to execute a subscription during ssr? In this case `browser === false` and `socketClient === null`

**Comment by OlmoDalco** [comment]
Ok, found a solution:
```ts
// ItemUpdate.listen({ id: itemID })
$: browser ? ItemUpdate.listen() : null;
```

**Comment by OlmoDalco** [comment]
Follow up question: Is there  a way to preload data via a query to deliver a prerendered list (ssr) and then keep the data up to date via a subscription once it's established on the client?

**Comment by AlecAivazis** [comment]
Glad to see your original issue was resolved @OlmoDalco and thanks for helping out @fehnomenal!

You can definitely! The best way to pull that off is to use `@list` on the field in your query and then use [list operation fragments](https://www.houdinigraphql.com/api/mutation/store#lists) inside of your subscription to mutate the result. Without knowing your query I can't give you an exact query to copy and paste but here's the general gist:

```graphql
query MyQuery { 
    myListField @list(name: "My_List") { 
        id}
        } 
    `
```
