### ISSUE TITLE
Allow user to specify unique constraints on mutation operations

### ISSUE THREAD

**Issue by ghost** [HoudiniGraphql/houdini#427]
Is there any mechanism to preload data on the server for server site rendering and the replace the data in the store with updates from a subscription once it's established on the client?

**Comment by OlmoDalco** [comment]
Thanks, for the quick response and amazing work!

**Comment by OlmoDalco** [comment]
Still struggling to implement it.  Here is an example:

_Load Data for server side rendering of an initial list_  
```graphql
query Messages($id:ID!){
      Message(where:{user_id:{_eq:$id}) @list(name:"User_Messages"){
           id
           title
           status
     }
}
```


_Then replace Data with event data from subscription once it's establish on the client to keep the list in sync with the database_
```graphql 
subscription MessageUpdates($id:ID!){
      Message(where:{user_id:{_eq:$id}){
           id
           title
           status
          ...User_Messages_insert
     }
}
```

This will add newly created abut also previously loaded messages to the store again and thus create duplicate entries. Is there a way to replace elements with an id that's already present in the store or to completely replace the stored data (...User_Messages_replace)?

**Comment by AlecAivazis** [comment]
Oh interesting. No at the moment that's not support by the mutation operations. I can try to get to something this week. I do have one question: if object is already present in the list, should `inserting` it remove the old entry and insert it in the specified location or should it just leave the record where it was originally and just update values?

**Comment by AlecAivazis** [comment]
I'm going to close this since I think this use case is now best served with the imperative API.
