### ISSUE TITLE
How to set Inline Documents  Query Variables?

### ISSUE THREAD

**Issue by OlmoDalco** [HoudiniGraphql/houdini#432]
I am trying to create a type ahead search field using svelte-select, but have no idea how to pass the searchString to the inline document query. 

```ts
async function loadOptions(searchString:string){
     const {data } = await query(graphl`query Test($searchString:String!){
         Test(where:{
             name:{
                 _eq:$searchString
             }
         }){
            id 
            name
     }`)
    return data
}
```

**Comment by OlmoDalco** [comment]
For anyone who runs into the same trouble:
async function loadOptions(searchString:string){
     await GQL_Test.fetch({variables:{searchString:string})
    return $GQL_Test.data.Test
}

**Comment by AlecAivazis** [comment]
Sorry I didn't see this earlier! The recommended way is to use the `fetch` field on the [returned object](https://www.houdinigraphql.com/api/query/inline).
