### ISSUE TITLE
Your project defines a Node interface but it does not conform to the Global Identification Spec.

### ISSUE THREAD

**Issue by Rar9** [HoudiniGraphql/houdini#433]
Using drupal 9 graphql v4

Your project defines a Node interface but it does not conform to the Global Identification Spec.

If you are trying to provide the Node interface and its field, they must look like the following:

interface Node {
        id: ID!
}

extend type Query {
        node(id: ID!): Node
}

**Comment by jycouet** [comment]
Strange to see all these servers having 
```graphql
type XXX implements Node
```
Not having `node(id: ID!): Node` implementation!

So, the server is saying, "Hey, you can use node(...) to query the type XXX" and actually, you can't!
Two options for endpoint builder:
1/ Don't `... implements Node` if you don't provide the implementation!
_or_
2/ Provide the implementation!

**With this kind of thing, `#GraphQL` has a high entry barrier!**

---

When the server tells Houdini _(by the introspection query)_ "hey, we have some types that implement Node", then Houdini will make use of it for you in some cases _(pagination for example)_!

Today, Houdini says that you have a problem with the schema _(and it's true, you have a problem with your schema!)_
![image](https://user-images.githubusercontent.com/5312607/180614342-8a3545b7-a614-4687-84fa-d702452e36aa.png)
And you should fix your schema (for reasons I explained above).

In the meanwhile, Houdini users are blocked 😓
I propose to:
1/ Switch the error to a warning (saying the same thing), and continue the normal flow
2/ Each time Houdini is using a Node implementation with a server not well configured => Throw the error msg.

**Comment by jycouet** [comment]
For info, [Vendure](https://www.vendure.io/) will fix it here: https://github.com/vendure-ecommerce/vendure/issues/1666

**Comment by AlecAivazis** [comment]
> 1/ Switch the error to a warning (saying the same thing), and continue the normal flow
> 2/ Each time Houdini is using a Node implementation with a server not well configured => Throw the error msg.

Both of these sound good to me. I think (2) might already happen 🤔

**Comment by yasserlens** [comment]
> For info, [Vendure](https://www.vendure.io/) will fix it here: [vendure-ecommerce/vendure#1666](https://github.com/vendure-ecommerce/vendure/issues/1666)

For Vendure - what would you suggest we do until this fix is in place?
I still gete ❌ There is a problem with your project's schema error. Using Vendure version 1.6.4.

P.S: I'm new to GraphQL

Thanks!

**Comment by jycouet** [comment]
The fix is in place, but not released yet. It will be with this PR: https://github.com/HoudiniGraphql/houdini/pull/450

In the meantime, your can add in your `schama.graphql` something like: 
```graphql
type Query {
  # a lot of useful stuff...
  
  node(id: ID!): Node # <- line to add
}
```

**Comment by yasserlens** [comment]
> The fix is in place, but not released yet. It will be with this PR: #450
> 
> In the meantime, your can add in your `schama.graphql` something like:
> 
> ```graphql
> type Query {
>   # a lot of useful stuff...
>   
>   node(id: ID!): Node # <- line to add
> }
> ```

That solved it locally - thanks very much. Will keep an eye on PR: #450 
Appreciate your quick response!
