### ISSUE TITLE
afterLoad Hook does not return data with mutation

### ISSUE THREAD

**Issue by digi4care** [HoudiniGraphql/houdini#444]
Hi I am trying to get the response data from a mutation in the afterLoad hook. but i somehow it is only working for queries and not for mutations?

Or am i doing something wrong here?
```
// index.svelte
<script context="module">
	// @ts-ignore
	export function afterLoad({ data }) {
		return {
			props: {
				message: 'Hi i am a message!'
			}
		};
	}
</script>

<script lang="ts">
	import { GQL_LoginUser } from '$houdini';
	import { getHoudiniContext } from '$houdini/runtime';

	// the context must be pulled out at the root of your component
	// so your HoudiniClient's fetch function has everything it needs
	const context = getHoudiniContext();

	export let message = '';

	let username: string = 'admin',
		password: string = 'password',
		data: any = {},
		error: any = {};

	async function loginUser() {
		await GQL_LoginUser.mutate({
			context,
			variables: {
				input: {
					username,
					password
				}
			}
		})
			.then(async (res) => {
				data = res;
			})
			.catch((err) => {
				error = err;
			});
	}
</script>

<div id="result">
	Message: <pre>{JSON.stringify(message)}</pre> <br>
	Data (inline): <pre>{JSON.stringify(data)}</pre> <br>
	Error (inline): <pre>{JSON.stringify(error)}</pre> <br>
</div>

<button class="" on:click={loginUser}>Click me</button>
```

**Comment by AlecAivazis** [comment]
Hey @digi4care! Sorry to hear you're running into this. The load hooks only work with inline queries so in order to do what you want, you'll have to perform the logic inside of the `then` callback of your mutate promise.

**Comment by digi4care** [comment]
Oke bummer. Will there be in the future a posibility to make this 'afterLoad'  possible for mutations?

**Comment by jycouet** [comment]
Hi @digi4care, what do you think about 👇

```ts
async function loginUser() {
  try {
    await GQL_LoginUser.mutate({context, variables: { ... } })
    // do things with data
  } catch (e) {
    // do things with error
  }
  // Actually, here you are "after mutation"
}
```

Would this be sufficient?

**Comment by digi4care** [comment]
Hi, thanks for your input but the thing i want to achive needs to be done in the GET hook

```
export const get: RequestHandler<OutputType> = async ({ params }) => {
	// get the houdini's response from the login mutation

	return {
		body: {
			data,
		},
	}
}
```

**Comment by digi4care** [comment]
need to figure out a work around. maybe mutate inline then post the results so i can intercept it in the POST handler (this handler would also be oke)

**Comment by jycouet** [comment]
I'm not sure exactly what you want to achieve.
It looks like you are trying to make the login. Right?

You should probably go through a `POST` to be able to pass username and password.
Then you can directly use your store in the endpoint.

Something like 
```ts
import { GQL_LoginUser } from '$houdini';

export async function POST() {
  await GQL_LoginUser.mutate({
    variables: { ... }
  });

  // You can do what you want here...
  // And return what you want.

  return {
    body: {
      message: 'login ok'
    }
  };
}
```

**Comment by digi4care** [comment]
Thanks for your time. i already made a work around but yours is more efficient.
while my workaround was posting the end data to the post end point because i thought it was not possible to mutate in a post end point. super going to test. thanks for your help

**Comment by digi4care** [comment]
your appraoch is giving me an error: window is not defined
Thats is the same problem i had

**Comment by AlecAivazis** [comment]
when using a store inside of an endpoint you need to pass the event arg as well as a fetch implementation. In this example, it'd look something like:

```

export async function POST( event ) {
  await GQL_LoginUser.mutate({
    event,
    fetch, // this uses the global fetch from node
    variables: { ... }
  });

}
```

**Comment by digi4care** [comment]
many thanks yours is working flawlessly :)
