### ISSUE TITLE
Houdini breaks with the latest SvelteKit

### ISSUE THREAD

**Issue by not-jan** [HoudiniGraphql/houdini#499]
### Describe the bug

$app/env has been renamed to $app/environment

https://github.com/sveltejs/kit/issues/5715

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

1. Install `houdini@0.15.9`
2. Install `@sveltejs/kit@1.0.0-next.445` or newer 
3. Houdini breaks the app

### Expected behavior

Houdini does not break the app

### System Info

```shell
System:
    OS: Linux
    CPU: AMD Ryzen 9
    Memory: 15.43 GB / 62.71 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.17.0 - /usr/bin/npm
  Browsers:
    Chromium: 104.0.5112.79
    Firefox: 103.0.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.67 
    @sveltejs/kit: next => 1.0.0-next.445 
    houdini: ^0.15.9 => 0.15.9 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.9
```

**Comment by AlecAivazis** [comment]
Thanks for the heads up! I'll get something out right ASAP

**Comment by AlecAivazis** [comment]
Should be fixed in `houdini@next`
