### ISSUE TITLE
Generated mutation mismatched variables key

### ISSUE THREAD

**Issue by DanielHritcu** [HoudiniGraphql/houdini#511]
### Describe the bug

The variables sent to the server uses the mutation input argument name instead of the named mutation argument name.

For the generated mutation:
```graphql
mutation CreateAccount($input: AccountInput!) {
  createAccount(data: $input) {
    email
    id
  }
}
```
Calling
```typescript
await GQL_CreateAccount.mutate({
  // Generated CreateAccount$input is correct.
  input: {
    email: "test@local.com"
  }
});
```

Will hit the server with the following variables:
```typescript
// `data` should be `input` as `$input` is declared in the mutation.
{ data: { email: 'test@local.com' }
```

### Severity

annoyance

### Steps to Reproduce the Bug

1. use a generated mutation with input.
2. use different variable name than the argument.

### Expected behavior

use the `$` variable name as key.\, not the argument name. in the request.

### System Info

```shell
N/A
```

**Comment by jycouet** [comment]
> Will hit the server with the following variables:
> 
> ```ts
> // `data` should be `input` as `$input` is declared in the mutation.
> { data: { email: 'test@local.com' }
> ```

I think that this is the response from the server, the result of your mutation.
Not what the server receives.

Update your mutation like this to check: 
```graphql
mutation CreateAccount($input: AccountInput!) {
  createAccount(data: $input) {
    #email # comment "email" to not request it in the result.
    id
  }
}
```

Let us know

---

What's your server?

**Comment by DanielHritcu** [comment]
@jycouet 
I'm using Yoga.

the output is from 

```typescript
export const resolvers: _AccountModule.Resolvers = {
  Mutation: {
    createAccount: async (_, _args, _ctx) => {
      console.log(_args)
      // { data: { email: 'test@local.com' }
      ...
    }
  }
}

**Comment by DanielHritcu** [comment]
> Update your mutation like this to check:
> 
> ```graphql
> mutation CreateAccount($input: AccountInput!) {
>   createAccount(data: $input) {
>     #email # comment "email" to not request it in the result.
>     id
>   }
> }
> ```
> 
> Let us know
> 

No change.

```typescript
// _args
{ data: { email: 'new@user.com', enabled: true } }
```

```GraphQL
# _ctx.query
mutation CreateAccount($input: AccountInput!) {
  createAccount(data: $input) {
    ..._AllAccounts_insert
    _id
  }
}

fragment _AllAccounts_insert on Account {
  _id
}
```

**Comment by DanielHritcu** [comment]
>I think that this is the response from the server, the result of your mutation.
>Not what the server receives.


It's what hits the server before any result is sent back. Check the resolver above.

**Comment by DanielHritcu** [comment]
Changing the server schema to:

```graphql
createAccount(thisIsTheIssue: AccountInput): Account
```

and modifying the Houdini query:

```GraphQL
mutation CreateAccount($input: AccountInput!) {
  createAccount(thisIsTheIssue: $input) {
    id
  }
}
```

will send the following variables in the request:
```typescript
{ thisIsTheIssue: { email: 'new@user.com', enabled: true } }
```

**Comment by jycouet** [comment]
Great to read that you are using `KitQL` 👌

Sorry, I was a bit fast reading your query.
The misleading field name is probably in the typedefs.
There, I think that you wrote `createAccount(data ...`

That's why your `args` is `data`

**Comment by jycouet** [comment]
> Changing the server schema to:
> 
> ```graphql
> createAccount(thisIsTheIssue: AccountInput): Account
> ```
> 
> and modifying the Houdini query:
> 
> ```graphql
> mutation CreateAccount($input: AccountInput!) {
>   createAccount(thisIsTheIssue: $input) {
>     id
>   }
> }
> ```
> 
> will send the following variables in the request:
> 
> ```ts
> { thisIsTheIssue: { email: 'new@user.com', enabled: true } }
> ```

Exactly. But this is not an issue.
You can rename `thisIsTheIssue` with `input` :)

The server is the server, and the client is the client.

From the client, we can't change the server behavior and variable names.

**Comment by DanielHritcu** [comment]
> Sorry, I was a bit fast reading your query. The misleading field name is probably in the typedefs. There, I think that you wrote `createAccount(data ...`
> 
> That's why your `args` is `data`

Not the case, check my comment above https://github.com/HoudiniGraphql/houdini/issues/511#issuecomment-1236172007

Also, Houdini would throw.
❌ Encountered error in src/graphql/account/_Mutation.AddAccount.gql
Unknown argument "data" on field "Mutation.createAccount"

**Comment by jycouet** [comment]
Not that easy to chat via a GitHub issue, sorry!

Yes, now that you renamed in your server: `data` to `thisIsTheIssue`
Houdini can't send a mutation with `data` and he is telling you nicely: `Unknown argument "data" on field "Mutation.createAccount`

**Comment by DanielHritcu** [comment]
Also, using a client like GraphiQL or Altair:

Will accept only what is defined with `$` as a variable name
<img width="438" alt="Screenshot 2022-09-03 at 2 03 21 PM" src="https://user-images.githubusercontent.com/90857471/188283000-e990fb78-92ea-4924-bb49-1d7991aeb598.png">

But not the actual operation's variable name

<img width="540" alt="Screenshot 2022-09-03 at 2 07 36 PM" src="https://user-images.githubusercontent.com/90857471/188283059-9154e6c0-13c1-4716-9148-8bd73e82cf98.png">

So I guess this is standard validation ?

**Comment by jycouet** [comment]
I think that you are confused with variable names (client thing) & argument names (server thing).

In your screenshot, in `variables` pad, you should match the variable `$input` described just above. (That's why Altair is telling you that he doesn't know $thisIsTheIssue, because you declared $input)

I could recommend you this video about Variables https://www.youtube.com/watch?v=PQvux9OAaBE

**Comment by DanielHritcu** [comment]
> I think that you are confused with variable names (client thing) & argument names (server thing).
> 
> In your screenshot, in `variables` pad, you should match the variable `$input` described just above. (That's why Altair is telling you that he doesn't know $thisIsTheIssue, because you declared $input)
> 
> I would recommend you this video about Variables https://www.youtube.com/watch?v=PQvux9OAaBE

So, in case of:
```GraphQL
mutation SomeMutation($someVar: Int)
  someMutation(anotherVar:$someVar){
     someField
  }
}
```

The expected behaviour is that Houdini will send:
```typescript
{
  "query": "mutation SomeMutation($someVar: Int)
    someMutation(anotherVar:$someVar){
      someField
    }
  }",
  "operationName": "SomeMutation",
  "variables": { "anotherVar": 0 }
}
```

Shouldn't the expected behaviour be:
```typescript
{
  "query": "mutation SomeMutation($someVar: Int)
    someMutation(anotherVar:$someVar){
      someField
    }
  }",
  "operationName": "SomeMutation",
  "variables": { "someVar": 0 }
}
```

**Comment by jycouet** [comment]
The server that no clue about `someVar`

The server describes in typedef I have a mutation: `SomeMutation` and this mutation needs an arg: `anotherVar`

Now, you can do your operation: 
```graphql
mutation SomeMutation($someVar: Int)
  someMutation(anotherVar:$someVar){
     someField
  }
}
```

And I can, _in another client_, do another operation without changing anything in the server: 
```graphql
mutation SomeMutation($my_cool_variable_name: Int)
  someMutation(anotherVar:$my_cool_variable_name){
     someField
  }
}
```

I can also, _in another client (Altair for example)_, have NO variable like:
```graphql
mutation SomeMutation
  someMutation(anotherVar: 7){
     someField
  }
}
```
