### ISSUE TITLE
If polling URL is down, local dev server stops

### ISSUE THREAD

**Issue by yasserlens** [HoudiniGraphql/houdini#535]
### Describe the bug

Hello!

The local dev server throws an exception and exits when the target apiUrl is down. I don't know if this happens in prod bundles, I hope not. Is there a reason why this should stop the local dev server? 
Isn't a warning about the state of the apiUrl not being reachable enough? 

See error below:
❌ Encountered error when pulling your latest schema: request to http://localhost:3000/shop-api failed, reason: connect ECONNREFUSED ::1:3000

I'm on v.0.16.1
sveltekit v1.0.0-next.476

Thanks!

### Severity

annoyance

### Steps to Reproduce the Bug

1) Specify a apiUrl in the houdini.config.js file
2) Take the apiUrl service offline
3) The local dev server throws an error and exits the process.

**Comment by jycouet** [comment]
Is `http://localhost:3000/shop-api` in your svelteKit app? or it's in a separate thing?

In your `houdini.config.js` you can set: `schemaPollInterval: null,` to disable automatic pulling

FYI: the pull is not here in prod.

**Comment by yasserlens** [comment]
the apiURL is a separate server, it's not part of the same app.
Thanks for the tip re: schemaPollInterval!
re: polling for prod - got it. So the poll is done locally, then the generated files are used in prod. Makes sense - thanks for clarifying.

**Comment by jycouet** [comment]
I was probably too fast closing the issue.

Maybe it would be better to have a warning showing you that the server is not reachable. Like this, you will start it.
What do you think @yasserlens ?

**Comment by yasserlens** [comment]
Thank you for following up. Yes, for sure. Shutting down the server is a severe measure because restarting the api service in dev can happen frequently. I still want it to pickup changes when they happen - so disabling polling isn't ideal. Reminding me that the API service is down (every x seconds) is much more useful.
