### ISSUE TITLE
Houdini 0.16 can't find runtime in monorepo - yarn workspaces

### ISSUE THREAD

**Issue by bbedward** [HoudiniGraphql/houdini#536]
### Describe the bug

Maybe relevant to [this](https://github.com/HoudiniGraphql/houdini/blob/60ecb333a1396f9aa7244eac2f38741a58e7281f/src/common/config.ts#L300)

We have a turbo monorepo structure for our project and attempting to migrate to houdini 0.16 and the new sveltekit, houdini is unable to find the runtime.

```
<root>
node_modules/houdini/xxx
apps/mysveltekitapp/houdini.config.js
```

Our structure is like this, where node_modules are installed in the root but the app lives in a project within the monorepo.

When running `yarn workspace @project/mysveltekitapp houdini generate` it failes with:

```
❌ ENOENT: no such file or directory, stat '/app/apps/mysveltekitapp/node_modules/houdini/build/runtime-esm'
```

It should be looking in the monorepo root, where the runtime exists : `/app/node_modules/houdini/build/runtime-esm`

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

1. Setup a sveltekit project in a monorepo using yarn workspaces
2. Follow houdini getting started guide
3. Error on `houdini generate` in yarn workspace.

**Comment by jycouet** [comment]
Could you remove `houdini` from the root and add it in `apps/mysveltekitapp/package.json`?

**Comment by bbedward** [comment]
@jycouet That is what we currently have. The workspace packages are just installed in the root project rather than in each package, this is typical of monorepos I believe.

**Comment by jycouet** [comment]
Could you please put your `monorepo/package.json` and `monorepo/apps/mysveltekitapp/package.json` here to better understand the situation? Thx

**Comment by bbedward** [comment]
I setup an example repo here https://github.com/bbedward/houdini-monorepo

You can run `yarn install && yarn workspace web houdini generate` and the error will be reproduced.
