### ISSUE TITLE
Unsubscribing too soon from the cache

### ISSUE THREAD

**Issue by fehnomenal** [HoudiniGraphql/houdini#543]
### Describe the bug

I tried many things and finally came to the conclusion that this is indeed a bug. It is related to the code generated by svelte...

I could only reproduce this with a query loaded inside `+page.ts` and used in `+page.svelte` (okok, I didn't try it with layouts).
```ts
// +page.ts
import { graphql, load_TestQuery } from '$houdini';
import type { PageLoad } from './$types';

export const load: PageLoad = async (event) => {
  return {
    ...(await load_TestQuery({ event })),
  };
};

graphql`
  query TestQuery {
    workshops_by_id(id: "dc0d85d8-c7f3-4e49-bc5f-abe57e762899") {
      uuid
      name
    }
  }
`;
```

Alright everything works just fine (as expected):
```svelte
<script lang="ts">
  import type { PageData } from './$types';

  export let data: PageData;

  $: ({ TestQuery } = data);
</script>

<pre>{JSON.stringify($TestQuery.data?.workshops_by_id, null, 2)}</pre>
```

Also with a mutation:
```svelte
<script lang="ts">
  import { graphql, TestMutationStore } from '$houdini';
  import type { PageData } from './$types';

  export let data: PageData;

  $: ({ TestQuery } = data);

  const updateName: TestMutationStore = graphql`
    mutation TestMutation {
      update_workshops_item(id: "dc0d85d8-c7f3-4e49-bc5f-abe57e762899", data: { name: "abc" }) {
        uuid
        name
      }
    }
  `;

  $: console.log('change', $TestQuery.data?.workshops_by_id);
</script>

<button
  on:click={async () => {
    await updateName.mutate(null);
  }}
>
  set name
</button>

<pre>{JSON.stringify($TestQuery.data?.workshops_by_id, null, 2)}</pre>
```

But one single, innocent line totally breaks this:
```diff
+  let { TestQuery } = data;
   $: ({ TestQuery } = data);
```

> I need this sometimes but only stumbled across this now as I need to populate form data for my form lib. In other cases I `Store.subscribe(...)` so there is no problem. Why? See below.

Just destructuring to get the store seems to be enough to make svelte generate code that subscribes to the store and seemingly immediately unsubscribes. Well, not immediately immediately but very soon.

I validated this by printing stuff inside the `QueryStore.subscribe` method to the console:
![image](https://user-images.githubusercontent.com/9959940/190383653-6233302d-3cf6-468a-9eb6-5a59624ea118.png)
`oldSubscriberCount` is the value of `this.subscriberCount` before incrementing or decrementing it.

The problem is when the count goes to `0` (i.e. at the first unsubscribe) the store also unsubscribes from the cache.

> This does not happen when calling `Store.subscribe(...)` as the count is higher in this case.

<details>
<summary>The generated code looks like this</summary>

```js
function instance($$self, $$props, $$invalidate) {
	let $TestQuery,
		$$unsubscribe_TestQuery = noop,
		$$subscribe_TestQuery = () => ($$unsubscribe_TestQuery(), $$unsubscribe_TestQuery = subscribe(TestQuery, $$value => $$invalidate(0, $TestQuery = $$value)), TestQuery);

	$$self.$$.on_destroy.push(() => $$unsubscribe_TestQuery());
	let { data } = $$props;
	let { TestQuery } = data;
	$$subscribe_TestQuery();

	const updateName = graphql`
    mutation TestMutation {
      update_workshops_item(id: "dc0d85d8-c7f3-4e49-bc5f-abe57e762899", data: { name: "abc" }) {
        uuid
        name
      }
    }
  `;

	const click_handler = async () => {
		await updateName.mutate(null);
	};

	$$self.$$set = $$props => {
		if ('data' in $$props) $$invalidate(3, data = $$props.data);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*data*/ 8) {
			$: $$subscribe_TestQuery($$invalidate(1, { TestQuery } = data, TestQuery));
		}

		if ($$self.$$.dirty & /*$TestQuery*/ 1) {
			$: console.log('change', $TestQuery.data?.workshops_by_id);
		}
	};

	return [$TestQuery, TestQuery, updateName, data, click_handler];
}
```

</details>

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

Just use `let { Store } = data;` in addition to `$: ({ Store } = data);` and observe that the store does no longer update.

**Comment by fehnomenal** [comment]
I noticed that removing the reactive destructuring also fixes this, and I don't even know when this should be necessary (I couldn't get `$: console.log('data update', data);` to trigger except for the first load).

**Comment by AlecAivazis** [comment]
Hm, I'm wondering if we need the subscriberCount logic at all any more 🤔 

It used to be there because when the stores were global we needed to reset them across route transitions but now that stores get instantiated on every request, i'm not sure we ever need to clean them up and get instead just let them get garbage collected with the rest of the component's variables...

I'll have some time later to dig into the specifics of the generated code in case we still need to keep it but I wanted to throw this out there in case you had thoughts

**Comment by fehnomenal** [comment]
Honestly, I don't know much about the cache implementation but I guess there is somewhere a callback that is called to update the query store. If we don't unsubscribe this callback remains in the cache and probably holds a reference to the query store? So this would never be garbage collected which might be a problem in really long running sessions without page reload. At least as long as the cache is global which it probably is.

But... I really never touched the cache code :sweat_smile:

**Comment by AlecAivazis** [comment]
So it turns out I already removed the bit of code I was hoping I could remove as part of the 0.16.0 work haha. Okay, it looks like this will require a deeper dive. I'll find some time this weekend 👍
