### ISSUE TITLE
Houdini 0.16.2 breaks +layout.server.ts

### ISSUE THREAD

**Issue by yoh-extradat** [HoudiniGraphql/houdini#544]
### Describe the bug

As soon as i add houdini to a sveltekit projekt, +server.layout.ts isn't working as expected.

## Expeceted behavior

+layout.server.ts
```ts
export async function load(event) {
    return { hello: "World" }
};
```
+layout.svelte
```html
<script>
   export let data
</script>
Layout Data: {JSON.stringify(data)}
```
rendered Layout
```
Layout Data: {hello:"World"}
```

## Behavior after adding Houdini

+layout.server.ts
```ts
export async function load(event) {
    return { hello: "World" }
};
```
+layout.svelte
```html
<script>
   export let data
</script>
Layout Data: {JSON.stringify(data)}
```
rendered Layout
```
Layout Data: {}
```

### Severity

blocking an upgrade

## Add Files 

+layout.server.ts
```ts
export async function load(event) {
    return { hello: "World" }
};
```

+layout.svelte
```html
<script>
   export let data
</script>
Layout Data: {JSON.stringify(data)}
```

+page.svelte
```html

```

**Comment by yoh-extradat** [comment]
Related to Houdini 0.16.2 updated.
0.16.0 and 0.16.1 work as expected!

**Comment by AlecAivazis** [comment]
Thanks for reporting this @yoh-extradat! I'll try to get a fix out today

**Comment by AlecAivazis** [comment]
Turns out this was relatively straight forward to fix. Will let you know when its deployed
