### ISSUE TITLE
types are not generated for GraphQL fragments

### ISSUE THREAD

**Issue by caboe** [HoudiniGraphql/houdini#552]
### Describe the bug

For a normal query, all TS types are generated correctly.
But when extracting parts to a fragment, the types are not included.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Clone https://github.com/caboe/houdini_fragment
2. Run the App, so the TS types are generated.
3. Have a look at +page.gql. The CountryFields are extracted to a fragment.
4. Inspect $houdini/artifacts/Country.d.ts

Expected result:
Includes all fields: 
`export type Country$result = {
    readonly country: {
        readonly name: string,
        readonly native: string,
        readonly capital: string | null,
        readonly emoji: string,
        readonly currency: string | null,
        readonly languages: ({
            readonly code: string,
            readonly name: string | null
        })[]
    } | null
};
`

Actual result:
Does not includes all fields:
`export type Country$result = {
    readonly country: {
        readonly $fragments: {
            CountryFields: true
        }
    } | null
};
`

**Comment by AlecAivazis** [comment]
Hey @caboe thanks for opening this.

I know it's a big surprising but this is actually an intended behavior. By default, houdini tries to protect you against coupling components together in coincidental ways by hiding fields that you did not explicitly ask for. In my experience, when 2 views ask for the same data but have different structure, the duplicate selection is more of a coincidence than a logical coupling and probably shouldn't be extracted into a fragment. If you were to change that fragment, you have to go hunt down every query that uses it and make sure that their components didn't rely on the old data. Typescript _does_ make this easier to do but imo its indicative of a leaky abstraction. If there are 2 views that have the same data requirement _and_ the same structure, then that's a perfect situation for a fragment, imo.  In those situations, a component with an inline query is the perfect way to encapsulate that coupling. 

It might help to have a concrete example so let's consider a UserAvatar component that takes in a user and renders their profile picture. If you had a view that rendered a UserAvatar, the query that requests that user might also want to know the user's first name for their own view. In that scenario, the route with the query should explicitly ask for the first name and not rely on the coincidence that UserAvatar also wants the first name. The reason for this is that if UserAvatar no longer wants the first name, now you have to go update the query: the route is tightly coupled to an implementation detail of another component.  By having masking turned on by default, houdini is encouraging you to minimize this so your views don't break in unexpected ways.

All of that being said, there are some situations where a fragment shouldn't be masked and for those situations, houdini lets you turn off masking on a specific fragment with the `@houdini(mask: false)` directive. You can also turn off masking globally with the `disableMasking` config value but I highly recommend leaving that on unless you are migrating to houdini in a project that wasn't built with this in mind.

**Comment by caboe** [comment]
Hi @AlecAivazis , 
Thanks for your detailed reply. I think there are some cases where it makes sense to merge the fragments into the types. In my case I have different types of articles, but they have some common fields, like title, author, etc. Also, when a new article is posted, an updated list of articles should come back. Fragments are useful here as well.
Nevertheless, the option to disable masking via a directive is perfectly sufficient for me. Maybe you can add that to the documentation (if I haven't missed it).
Thanks again for the quick detailed answer.

Carsten

**Comment by ewen-lbh** [comment]
For people stumbling upon this issue, the directive [has been renamed](https://github.com/HoudiniGraphql/houdini/blob/8409c703a79b037a655ac45455d10965aebae681/packages/houdini/CHANGELOG.md?plain=1#L480) `@houdini(mask: false)` is now `@mask_disable`
