### ISSUE TITLE
Local development environment not producable for contribution

### ISSUE THREAD

**Issue by sjcobb2022** [HoudiniGraphql/houdini#564]
### Describe the bug

Hi there,

I'm want to contribute to Houdini however the development environment does not function with the instructions provided on the `[website](https://www.houdinigraphql.com/guides/contributing)`.

If this is of any help: I am on Arch Linux (EndeavorOS).

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

1. Clone the houdini repo
2. Follow instructions on [guides/contributing](https://www.houdinigraphql.com/guides/contributing)
3. `pnpm i && pnpm run build`
4. This gets peer dependency errors (can be ignored with `strict-peer-dependencies=false`). Build also fails.
6. `cd example`
7. `pnpm run generate && pnpm run dev`
8. generate fails and dev fails because of this.

**Comment by DanielHritcu** [comment]
The example fails to build for me also.

Build error:
```
houdini/example/src/routes/[filter]/+page.svelte:4:23
 2 |  import GQL_AddItem from "$houdini/stores/AddItem";
 3 |  import { page } from "$app/stores";
 4 |  import { graphql, type AddItemStore, type AllItemsStore, type NewItemStore } from "$houdini";
                             ^
 5 |  import ItemEntry from "$lib/ItemEntry.svelte";
 6 |  import { derived } from "svelte/store";
error during build:
ParseError: Unexpected token
    at error (file:///houdini/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/compiler.mjs:17799:19)
```

Dev error:
```
TypeError: __vite_ssr_import_1__.default.init is not a function
    at eval (/src/routes/+layout.js:18:31)
```

I can run the build successfully, but I noticed this in the output:
```
[cmd] [exe] rpt2: options error TS6053: File 'houdini/example/$houdini/graphql/enums.d.ts' not found.
[cmd] [exe]   The file is in the program because:
[cmd] [exe]     Root file specified for compilation
```

**Comment by DanielHritcu** [comment]
@sjcobb2022 
I had an issue with the integration tests. 
But using `nvm` to switch to `node v16.17.0` fixed it.

Just curious, what version of `pnpm` and `node` are you using.
Also, can you post a gist with your error ?

**Comment by sjcobb2022** [comment]
> @sjcobb2022 I had an issue with the integration tests. But using `nvm` to switch to `node v16.17.0` fixed it.
> 
> Just curious, what version of `pnpm` and `node` are you using. Also, can you post a gist with your error ?

Hi @DanielHritcu. 

Sorry for the late response I'm prepping for uni. I am on node v18.9.0 and pnpm v7.12.1.

The errors appear as follows

## Using node v18.9.0

pnpm i:
```
ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

example
└─┬ graphql-relay 0.8.0
  └── ✕ unmet peer graphql@15.5.1: found 15.5.0

integration
├─┬ @replayio/playwright 0.2.23
│ └── ✕ unmet peer @playwright/test@1.19.x: found 1.25.0
└─┬ graphql-relay 0.10.0
  └── ✕ unmet peer graphql@^16.2.0: found 15.5.0

site
└─┬ vite-plugin-replace 0.1.1
  └── ✕ unmet peer vite@^2: found 3.0.9
```
pnpm generate:
```
> example-kit@0.13.0 generate /home/sjcobb/dev/houdini/example
> houdini generate

sh: line 1: houdini: command not found
 ELIFECYCLE  Command failed.
```
then for pnpm run dev

when running it is clear that sveltekit is clearly not initialized. (there is not .svelte-kit when I list the directory)

```
[web] ▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]
``` 

The graphQL server with yoga then also proceeds to fail it's init.

```
[api] 💡 🧘 Yoga - Running GraphQL Server at http://0.0.0.0:4000/graphql
[web] ⚠️  Couldn't pull your latest schema: request to http://localhost:4000/graphql failed, reason: connect ECONNREFUSED ::1:4000
```

And then when trying to access localhost

```
[web] __vite_ssr_import_1__.default.init is not a function
[web] TypeError: __vite_ssr_import_1__.default.init is not a function
[web]     at /src/routes/+layout.js:13:15
```


## Using Node 

pnpm i
```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

example
└─┬ graphql-relay 0.8.0
  └── ✕ unmet peer graphql@15.5.1: found 15.5.0

integration
├─┬ @replayio/playwright 0.2.23
│ └── ✕ unmet peer @playwright/test@1.19.x: found 1.25.0
└─┬ graphql-relay 0.10.0
  └── ✕ unmet peer graphql@^16.2.0: found 15.5.0

site
└─┬ vite-plugin-replace 0.1.1
  └── ✕ unmet peer vite@^2: found 3.0.9

```

pnpm run dev: 
```
[web] ▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

```

accessing localhost: 
```
[web] __vite_ssr_import_1__.default.init is not a function
[web] TypeError: __vite_ssr_import_1__.default.init is not a function
[web]     at /src/routes/+layout.js:13:15
```

So the only difference is that the yoga server is queried correctly.

**Comment by AlecAivazis** [comment]
So that error is accurate - `init` has been removed from the client since it's no longer necessary. Is that line you showed from the integration tests?

**Comment by AlecAivazis** [comment]
Okay, #569 updates the example (as well as some small QoL improvements to the types). For what it's worth, we've been using the integration tests as the primary test bed for local dev which is probably why this wasn't caught until now. I'll update the contributing guide to mention that instead.
