### ISSUE TITLE
Resolution error when building in Droplet with Ubuntu 20.04.5

### ISSUE THREAD

**Issue by revnelson** [HoudiniGraphql/houdini#565]
### Describe the bug

When trying to run (build or dev) my project, I get this error:

```
Could not resolve './adapter' from $houdini/runtime/index.js
error during build:
Error: Could not resolve './adapter' from $houdini/runtime/index.js
    at error (file:///home/PROJECT/PATH/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.handleResolveId (file:///home/PROJECT/PATH/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22350:24)
    at file:///home/PROJECT/PATH/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22313:26
error Command failed with exit code 1.
```

This error doesn't happen on my macbook, but when I tried to build directly on the server (DigitalOcean Droplet running Ubuntu 20.04.5) it throws this error. I'm posting here because without houdini it builds fine, but it may be some configuration issue I've messed up. I have tried this with Node 16 and 18. Same error.

My houdini config:
```typescript
/** @type {import('houdini').ConfigFile} */
const config = {
	client: "./packages/wp/client.ts",
	include: "{src,packages}/**/*.{svelte,graphql,gql,ts,js}",
	apiUrl: "https://api.example.com/graphql",
	framework: "svelte",
	disableMasking: true,
	schemaPollInterval: 0,
}

export default config
```

svelte.config.js:
```javascript
import adapter from "@sveltejs/adapter-node"
// import adapter from "@sveltejs/adapter-auto"

import path from "path"

import preprocess from "svelte-preprocess"

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [preprocess({ postcss: true })],

	kit: {
		adapter: adapter({ out: "dist" }),
		// adapter: adapter(),
		alias: {
			$components: "src/components",
			$ui: "src/components/ui",
			$machines: "src/machines",
			$common: "src/elements",
			$icons: "src/elements/icons",
			$stores: "src/stores",
			$wp: "packages/wp",
			$houdini: path.resolve(".", "$houdini"),
		},
	},
}

export default config
```

and my vite.config.js:
```javascript
import { sveltekit } from "@sveltejs/kit/vite"
import houdini from "houdini/vite"

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [houdini(), sveltekit()],
}

export default config
```

Relevant parts from package.json:
```json
"@sveltejs/adapter-node": "^1.0.0-next.87",
"@sveltejs/kit": "^1.0.0-next.437",
"houdini": "^0.16.5",
```

I'm not sure which other information would be useful, so please let me know and I will provide it as soon as possible.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Run `yarn build` or `yarn dev`

**Comment by AlecAivazis** [comment]
Hm, how strange. Okay I have a feeling this is one of those things that will be best figured out on a call. Is that something you're open to? If so, feel free to send me a friend request on discord. You can find me through the Svelte channel (my account is @AlecAivazis).

**Comment by AlecAivazis** [comment]
@revnelson is this still a problem?

**Comment by AlecAivazis** [comment]
I'm going to close this since its gone a bit stale and we're about to release a big update that might fix this. Feel free to open another ticket if you are  still struggling @revnelson!
