### ISSUE TITLE
Querying in nested route cases mutation of attributes in parent store during CSR

### ISSUE THREAD

**Issue by wattsjs** [HoudiniGraphql/houdini#575]
### Describe the bug

Hi there 👋 fantastic work on this library!

I've been stuck on an issue for a while and I would like to rule out a bug as I can't seem to track down what is happening

I have an app with a sidebar containing a list of items, and then a main content section that displays those same items with some additional fields in the query

Upon initial SSR load of the `./app/[slug]/+page` route, everything seems to work fine. However when client routing takes over there is some strange mutation of the parent GetRacesStore when the child query/store is updated - all of the `meeting` attributes in the parent store are updated to the `meeting` attribute of selected item

If i subscribe to the parent data store, I can see that it gets mutated when I update the child - every `race` from the `GetRacesStore` has it's meeting value updated to the `meeting` value of the result of the `GetRace` query

```gql
query GetRaces($dateFrom: String!, $dateTo: String!) {
	races(dateFrom: $dateFrom, dateTo: $dateTo) {
		meeting {
			location
			track
			type
			date
		}
		number
		status
		startTime
	}
}
```

```gql
query GetRace($id: String!) {
	race(id: $id) {
		meeting {
			location
			track
			type
			date
		}
		number
		status
		startTime

		runners {
			number
			name
		}
	}
}
```

Is this something to do with a naming conflit? Caching? Or am I just doing something silly here? 😬

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

1. Create a query for a list of objects in a parent `+layout.svelte` route
2. Create a query for an individual item of the same type in a nested child route

**Comment by wattsjs** [comment]
I've attached a screenshot below showing the state of the `meeting` object within the parent store

[](url)
![Screenshot 2022-09-28 at 22 08 18@2x](https://user-images.githubusercontent.com/60246116/192775226-429be997-3009-44c0-a565-b9a727324c3a.png)

**Comment by AlecAivazis** [comment]
I tried to reproduce this with the integration test suite but it seems to be working as I expect. Can you confirm that [these routes](https://github.com/HoudiniGraphql/houdini/tree/nested-list-cache-bug/integration/src/routes/stores/nested-lists) are setup correctly?

**Comment by wattsjs** [comment]
Thanks for having a look so quickly Alec

I will try and setup a stack blitz a bit later today 😊

Just to confirm - it was only nested properties of the parent query that
are mutated, so your example wouldn’t exhibit the behaviour on my end
either.

**Comment by AlecAivazis** [comment]
Oh okay, well if you wanted to just submit a PR with the necessary changes to show the problem in that route, it would be a much bigger help than a stack blitz (and probably quicker for you too)

**Comment by wattsjs** [comment]
Thanks mate - I've created https://github.com/HoudiniGraphql/houdini/pull/576 however I am not sure what values are available on the User store as there needs to be a nested property like I have shown

**Comment by AlecAivazis** [comment]
Okay, i pushed up some changes to that branch that uses a nested reference to avoid any differences with list handling. I'm not able to see the bug tho 🤔 Mind checking that I got it right?

**Comment by wattsjs** [comment]
Your changes look good to me - very strange! I'll have a bit more of a dig into this today and I'll report back. Is there a test API that I could run against?

Thanks again for looking into this

**Comment by AlecAivazis** [comment]
It's included in the integration test project, you should just need to do `pnpm run dev` and it will start both servers for you. Let me know if you run into any issues

**Comment by AlecAivazis** [comment]
Is there an `id` field for the records?

**Comment by wattsjs** [comment]
Ok so I made some changes to my schema on the server and the issue has gone away...
There is an id field but I think that maybe there was something malformed and it was causing houdini to get confused. I believe this still may be a bug in an edge case but it's no longer blocking me!

Thanks for your assistance Alec - keep up the great work!

**Comment by AlecAivazis** [comment]
Hm, okay. I'll keep an eye out for it but without a way to reproduce the issue I think we'll just have to wait til someone run into it and hopefully reports it. 

Thanks for the kind words ❤️
