### ISSUE TITLE
Imperative cache API

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#58]
Houdini needs to provide the user a way to interact with the cache imperatively to handle situations that aren't covered by the declarative API

**Comment by AlecAivazis** [comment]
Since #228 was merged the methods available on the cache are more user-friendly (there aren't a bunch of methods that really shouldn't be used but rely on typescript's `private` keyword). 

The biggest hurdle atm is how to handle the type specification when writing. It would be annoying to have to specify the `SubscriptionSelection` every time but we need some way of knowing how to store the values that the user is handing the cache.

**Comment by jycouet** [comment]
Not an easy topic, thx for putting a starting point 👍
I would like also to collect "Use Cases" to understand the different things to handle and provide _THE_ good API.
_I'll put notes here when I hit one_

**Comment by m4tr1k** [comment]
@AlecAivazis @jycouet so I found an interesting use case for this (I'm actually doing this on one of my projects):

- so I have an entity (let's call it `A`) that has a list of other entity (let's call it `B`)
- I have a mutation to delete `B`, and when deleting `B` I need to update `A` to reflect those changes on the screen
- so I call the `B` delete mutation, and then I get all `B`  from the list inside `A` to filter the deleted `B`
- then I call `Cache.write()` function to update `A` with the new list of `B`

**Comment by jycouet** [comment]
After a call with @AlecAivazis , let's put down a few thoughts:

```js
// reset everything 
cache.markAllStale()

// root
const rootCache = cache.getRoot()

// reset all `quoteEdge`
rootCache.markStale("quoteEdge")
// GQL_quoteEdge.markStale();

// reset some fields
const quoteEdge = rootCache.getFields("quoteEdge")
quoteEdge.markStale("nodes")
quoteEdge.markStale("totalCount")

// reset some fields when specific inputs
rootCache.markStale("quoteEdge",  {edge: { pagination: { skip: 0 }, filters: { creatorUserId: null} }})
rootCache.markStale("user", { name: 'JYC'} )
```

A lot of things are subject to change... but it's a start 😊

**Comment by frederikhors** [comment]
Don't have this is a HUGE BLOCKER for us to switching from urql to houdini.

I wish you to work on it expressing the best of yourself. 😄

**Comment by AlecAivazis** [comment]
@frederikhors it's looking like this will be the next thing we focus on. stay tuned!

**Comment by AlecAivazis** [comment]
@frederikhors mind telling me which features/ use cases you need most out of the imperative api? I'm assuming marking data as stale is an important one but I'm curious if there are others?

**Comment by frederikhors** [comment]
For now I only need invalidation.

We're using it hard because we invalidate & refetch in case of update/delete of an items.

I'll let you know if something else is needed.

**Comment by AlecAivazis** [comment]
Awesome! Thanks for the quick reply. Would you want a way to automatically trigger refetches of the deleted value or is that something you would do by hand? Or just the next time the query is fired?

**Comment by frederikhors** [comment]
I think this depends each time.

All the options? It's difficult?

**Comment by AlecAivazis** [comment]
Nope, not difficult just trying to figure out the priority for all of the features. There's a lot that I'd like to be able to do with this API but with `1.0` coming soon I'll have to shift focus over to accommodating some of the recent changes that will effect houdini so I'm trying to get _something_ out quickly before I get distracted
