### ISSUE TITLE
Session was not passed correctly. This should never happen. Please open a ticket on Github and we'll sort it out.

### ISSUE THREAD

**Issue by wattsjs** [HoudiniGraphql/houdini#582]
### Describe the bug

Hey guys 👋

`Session was not passed correctly. This should never happen. Please open a ticket on Github and we'll sort it out.`

After integrating some new authentication I've been stung with the above error. What is the expected behaviour here / where can I start poking around to resolve this?

Cheers

### Severity

annoyance

### Steps to Reproduce the Bug

Probably related to many nested routes with different `load` functions and not passing the session data in the right way?

**Comment by AlecAivazis** [comment]
👋 So usually this means you haven't defined your session in the  `hooks.server.js` file - does that sound right? If you _have_ defined your session, its possible there is something unexpected happening

**Comment by wattsjs** [comment]
Thanks Alec - spot on 👍

**Comment by revnelson** [comment]
> 👋 So usually this means you haven't defined your session in the `hooks.server.js` file - does that sound right? If you _have_ defined your session, its possible there is something unexpected happening

Can you explain more about defining session in this file? How do we need to do that? I have defined the type in `app.d.ts` but am still getting this error.

**Comment by AlecAivazis** [comment]
Sure! There is a page in the docs about this: https://www.houdinigraphql.com/guides/authentication

Let me know if that's not enough and I can try to explain whichever parts aren't clicking

**Comment by revnelson** [comment]
I followed that page but am getting the error. Perhaps I've done something wrong. Here's my `app.d.ts`

```typescript
/// <reference types="@sveltejs/kit" />

// import type { User$data } from "$houdini"

type TokensType = {
	auth: string | null
	refresh: boolean | string
}

// See https://kit.svelte.dev/docs/types#app
// for information about these interfaces
// and what to do when importing types
declare namespace App {
	interface Locals {
		body: any
		tokens: TokensType
		// user: User$data | null
		cart?: string | null
	}
	// interface Platform {}
	interface Session {
		tokens: TokensType
		// user: User$data | null
		cart?: string | null
	}
	// interface Stuff {}
}
```

And the `handle` function in `handle.server.js`

```javascript
export const handleAuth: Handle = async ({ event, resolve }) => {
	// Before endpoint call

	const { request, url } = event

	let refreshedToken: string | undefined = undefined
	let shouldLogout = false

	const cookies = cookie.parse(request.headers.get("cookie") || "")
	const authToken = cookies[AUTH_TOKEN_KEY]
	const refreshToken = cookies[REFRESH_TOKEN_KEY]

	houdiniClient.setSession(event, { tokens: { auth: null, refresh: false } })

	// Skip auth check when using authentication endpoints
	if (!url.pathname.startsWith("/auth")) {
		if (!isTokenValid(authToken)) {
			// Auth token is invalid

			// Check if refreshToken available
			if (isTokenValid(refreshToken)) {
				// Try to get new auth token

				try {
					console.warn("Trying to refresh auth token.")

					const refreshResponse = await fetch(AUTH_ENDPOINT, {
						method: "POST",
						body: JSON.stringify({ action: "REFRESH", token: refreshToken }),
					})

					const refreshData = await refreshResponse.json()
					const newToken = refreshData?.refresh?.data?.refreshJwtAuthToken?.authToken

					// If new auth token, set it for response headers
					newToken ? (refreshedToken = newToken) : (shouldLogout = true)
				} catch (error) {
					// Error during
					console.warn("Error during token refresh attempt.", refreshToken, error)
				}
			} else {
				// Auth token is invalid
				// Refresh token is invalid
				shouldLogout = true
			}
		} else {
			// User is authorized
			// Put authToken into locals for endpoint to access

			console.log("User is authorized")

			houdiniClient.setSession(event, { tokens: { auth: authToken, refresh: false } })

			event.locals.tokens = { ...event.locals.tokens, auth: authToken }
		}
	} else {
		// Going to auth endpoint

		console.log("Going to auth")

		// Put tokens into locals for endpoint to access

		event.locals.tokens = {
			...event.locals.tokens,
			auth: authToken ?? false,
			refresh: refreshToken ?? false,
		}
	}

	// Endpoint call
	const response = await resolve(event)

	// After endpoint call

	// If new auth token received, set cookie
	refreshedToken &&
		response.headers.append(
			"set-cookie",
			`${AUTH_TOKEN_KEY}=${refreshedToken}; HttpOnly; Path='/'; expires=${new Date(
				Date.now() + 15 * 60 * 1000,
			).toUTCString()}`,
		)

	// If shouldLogout, destroy tokens if they exist
	if (shouldLogout) {
		authToken &&
			response.headers.set(
				"set-cookie",
				`${AUTH_TOKEN_KEY}=deleted; Path='/'; expires=Thu, 01 Jan 1970 00:00:00 GMT`,
			)
		refreshToken &&
			response.headers.append(
				"set-cookie",
				`${REFRESH_TOKEN_KEY}=deleted; Path='/'; expires=Thu, 01 Jan 1970 00:00:00 GMT`,
			)
	}

	return response
}

```

I added the first `houdiniClient.setSession` in an attempt to troubleshoot thinking that the error may be caused by not setting a default-null/false session when unauthorized, but I still get the error.

**Comment by revnelson** [comment]
I just noticed the `cart` in the type definition for `Session` in `app.d.ts` which isn't being used. I commented that line out and am still getting the error.

**Comment by m4tr1k** [comment]
@revnelson you're not the only one getting that error. I don't know if this happens to you but when logging in and trying to set Houdini client, Houdini throws that specific error. However if I refresh the page right after, the error disappears.

To give some context of what I'm doing (which is a lot less specific than yours):

```ts
///src/hooks.server.js

import houdiniClient from './client';

export async function handle({ event, resolve }) {
	const accessToken = event.cookies.get(ACCESS_TOKEN);

	if (accessToken) {
		houdiniClient.setSession(event, { accessToken });
	}

	return await resolve(event);
}
```

```ts
///src/app.d.ts
declare namespace App {
	...
	interface Session {
		accessToken?: string | null;
	}
}
```

```ts
///src/client.ts
import { HoudiniClient, type RequestHandlerArgs } from '$houdini';

async function fetchQuery({ fetch, text = '', variables = {}, session }: RequestHandlerArgs) {
	const url = import.meta.env.VITE_GRAPHQL_ENDPOINT;
	const result = await fetch(url, {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
			Authorization: 'Bearer ' + session.accessToken
		},
		body: JSON.stringify({
			query: text,
			variables
		})
	});
	return await result.json();
}

export default new HoudiniClient(fetchQuery);
```

**Comment by AlecAivazis** [comment]
Damn, im sorry y'all are still running into this. I have a few things on my plate atm so it would be really helpful if one of you could put a stackblitz together that showcases the issue. The session infrastructure seems to work well in the e2e tests as well as my own projects using Houdini so there's probably some subtle difference.  

That being said, let's move that debugging conversation to a different issue so we don't spam wattsjs. 

@revnelson nothing is immediately wrong with what you showed  except for maybe the file name. I haven't been following the very latest in kit so I'm not sure if there's a difference betwen `hooks.server.js` and `handle.server.js`. Could you try stripping away different parts of that function to see if you can pinpoint the issue? If you have the time to put together a stackblitz I'll gladly take a look. 

@m4tr1k i have a feeling your issue is that you are conditionally setting the session but always accessing it by destructuring in your fetch function. Can you try doing something like:

```
///src/hooks.server.js

import houdiniClient from './client';

export async function handle({ event, resolve }) {
	const accessToken = event.cookies.get(ACCESS_TOKEN);

	houdiniClient.setSession(event, { accessToken });

	return await resolve(event);
}
```

```
///src/client.ts
import { HoudiniClient, type RequestHandlerArgs } from '$houdini';

async function fetchQuery({ fetch, text = '', variables = {}, session }: RequestHandlerArgs) {
	const url = import.meta.env.VITE_GRAPHQL_ENDPOINT;
	
	const headers = {
		'Content-Type': 'application/json',
	}
	
	if (session.accessToken) {
		headers['Authorization'] = 'Bearer ' + session.accessToken
	}
	
	const result = await fetch(url, {
		method: 'POST',
		headers,
		body: JSON.stringify({
			query: text,
			variables
		})
	});
	return await result.json();
}

export default new HoudiniClient(fetchQuery);
```

**Comment by m4tr1k** [comment]
@AlecAivazis thank you for your detailed answer. The error indeed disappeared. However, on the first request after logging in, I'm getting the same Unauthorized error. If I refresh the browser, everything works perfectly.

What I'm doing internally is login, then I redirect the user to the dashboard and while doing that, I'm doing a GraphQL query in a +page.ts file (using fetch() function)

**Comment by AlecAivazis** [comment]
@revnelson I think i _finally_ found what was causing your error. there was an inconsistency in the treatment of some fs functions in certain versions of node which have been addressed. If you're still trying to figure this out, mind giving `0.17.3` a shot?
