### ISSUE TITLE
`houdini generate` doesn't detect any graphql operations with version 0.16.7 on Windows

### ISSUE THREAD

**Issue by SeppahBaws** [HoudiniGraphql/houdini#592]
### Describe the bug

Integrating houdini 0.16.7 (latest version at the time of writing) breaks the `houdini generate` command, stating "No operation found".
Switching back to version 0.16.6 fixes the `houdini generate` command, and generates types.

OS: Windows
npm version: 8.11.0
node version: 16.15.1

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

1. clone the linked example repo
2. `npm install`
3. `npm run generate`
4. the output says "No operation found. If that's unexpected, please check your config."

changing the houdini version in `package.json` back to 0.16.6 will generate types again.

### Reproduction

https://github.com/SeppahBaws/houdini-generate-issue

**Comment by SeppahBaws** [comment]
Update: After a suggestion from a colleague, I have tried reproducing the issue on my Linux laptop, where it does seem to work perfectly fine.

**Comment by HarunKilic** [comment]
Got the same issue on Windows

**Comment by AlecAivazis** [comment]
Thanks for reporting this @SeppahBaws - I'll try to find some time this weekend to fix it

**Comment by AlecAivazis** [comment]
This should now be fixed on `0.16.8` 👍

**Comment by AlecAivazis** [comment]
Apparently this is still a problem. will look into it soon
