### ISSUE TITLE
npx houdini init failing with 0.17.0

### ISSUE THREAD

**Issue by sjcobb2022** [HoudiniGraphql/houdini#628]
### Describe the bug

Hi there. After updating to 0.17.0 I've had some migration issues so I attempted to try everything from a simple base program. 

After install `houdini` and `houdini-svelte`, I then attempted to run `npx houdini init`.

Whether I had config files already present or not, the code would fail anyway.

I have another breaking error with the update but I believe it is totally unrelated so i will make another issue for this.

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

1. npm create svelte@latest my-app
2. npm i -D houdini houdini-svelte
3. npx houdini init

Receive error

```bash
home/sjcobb/.npm/_npx/754cf465adfd4c79/node_modules/.bin/houdini: line 1: syntax error near unexpected token `('
/home/sjcobb/.npm/_npx/754cf465adfd4c79/node_modules/.bin/houdini: line 1: `import { createRequire as conflict_free } from 'module'; const require = conflict_free(import.meta.url);'
```

**Comment by AlecAivazis** [comment]
Damn, I had a hunch something like this would happen. Can you tell me what version of node you are using?

**Comment by sjcobb2022** [comment]
> Damn, I had a hunch something like this would happen. Can you tell me what version of node you are using?

LTS, 16.18

**Comment by AlecAivazis** [comment]
Okay, cool. I upgrade to 16.18 and reproduced it . I have a fix, will publish it along with the css fix. Thanks for being patient!

**Comment by sjcobb2022** [comment]
Awesome thanks man!
