### ISSUE TITLE
+page.gql are sent twice

### ISSUE THREAD

**Issue by jycouet** [HoudiniGraphql/houdini#632]
### Discussed in https://github.com/HoudiniGraphql/houdini/discussions/609

<div type='discussions-op-text'>

<sup>Originally posted by **philippxbt** October 17, 2022</sup>
Hi, 
I'm using automatic loading for my queries by adding a +page.gql file in the respective route directories. I have also defined the variables functions, because all my queries have variables. 

The queries are working, however, I noticed that each graphql request is sent twice to the server, the first request without variables and the second one with the variables. 

Is this default behavior or am I doing something wrong?</div>

A simple way to reproduce this is to have:
```gql

# +page.gql

query ProjectsList($limit: Int) {
  project(limit: $limit) {
    username
}
```
And add a log in your client `fetchQuery`. You will see that it will be fired 2 times.

This is because the preprocessor will generate code in: `+page.js` and `+layout.js`.

To fix this:
- `+page.gql` should only affect `+page.js` 
- `+layout.gql` should only affect `+layout.js`

**Comment by grischaerbe** [comment]
For me this also happens with queries without any variables, @jycouet can you confirm that?

**Comment by jycouet** [comment]
Yes, I confirm.
It's fixed in the PR #633 that will be merged soon 👍

**Comment by grischaerbe** [comment]
My guess is that this is also related to the following issue:

Assuming the following routes structure:

<img width="396" alt="Bildschirmfoto 2022-10-24 um 11 47 55" src="https://user-images.githubusercontent.com/46897060/197499039-f24310c4-2fb8-4184-96f3-172ffa3495bf.png">

navigating to `/some-collection/some-page` triggers the following queries in this order: 

- `routes/layout.gql` - (expected)
- `routes/page.gql` - (not expected)
- `routes/[collectionHandle]/[slug]/page.gql` - (expected)

I guess that the query `routes/layout.gql` leads to also querying `routes/page.gql` which should not be the case, right?

**Comment by jycouet** [comment]
Yes, exactly. 
And it's what is fixed in https://github.com/HoudiniGraphql/houdini/pull/633 🥳
