### ISSUE TITLE
Add light mode to docs 

### ISSUE THREAD

**Issue by gterras** [HoudiniGraphql/houdini#634]
### Describe the feature

Hi, 

Dark theme burns my eyes so I can't read the documentation (unless reader mode which isn't really practical in this case - smaller code blocks, no syntax coloration...), it's a small detail but it makes it _really_ hard to learn houdini (which look awesome by the way). 

Usually projects docs are either light or light+dark but almost never just dark (I suppose because of this). 

Thank you!

**Comment by AlecAivazis** [comment]
Oh no! Sorry to hear that dark mode is so painful for you. 

It might take a bit but we'll work on putting a light mode together 👍

**Comment by gterras** [comment]
Hi I will try to send an implementation in the next few weeks!
