### ISSUE TITLE
Generated types import QueryStore from unknown location

### ISSUE THREAD

**Issue by grischaerbe** [HoudiniGraphql/houdini#636]
### Describe the bug

Assuming the following `routes` directory structure:

<img width="169" alt="Bildschirmfoto 2022-10-24 um 12 24 15" src="https://user-images.githubusercontent.com/46897060/197505330-21e06538-a6f2-4daf-8353-ccadf37f2609.png">

This is what the contents of `$houdini/types/src/routes/$houdini.d.ts` (The types imported in `src/routes/+layout.svelte` by `import { LayoutData } from './$houdini'`) look like:

```ts
import type * as Kit from '@sveltejs/kit';
import type { VariableFunction, AfterLoadFunction, BeforeLoadFunction }  from '../../../plugins/houdini-svelte/runtime/types'
import type { PageLoadEvent, PageData as KitPageData } from './$types'
import type { LayoutLoadEvent, LayoutData as KitPageData } from './$types'

import { RootPage$result, RootPage$input } from '../../../artifacts/RootPage'
	import { RootPageStore } from '../../../stores/RootPage'
import { RootLayout$result, RootLayout$input } from '../../../artifacts/RootLayout'
	import { RootLayoutStore } from '../../../stores/RootLayout'

type PageParams = PageLoadEvent['params']
type LayoutParams = LayoutLoadEvent['params']











export type LayoutData = {
		RootLayout: RootLayoutStore
}    
export type PageData = {
		RootPage: RootPageStore
}    
```

My guess is that the import on line 9:

```ts
import { RootLayoutStore } from '../../../stores/RootLayout'
```

is not yet adapted to the new plugins system as it should be imported from

```ts
import { RootLayoutStore } from '../../../plugins/houdini-svelte/stores/RootLayout'
```

I'm working with 
- houdini@0.17.1
- houdini-svelte@0.17.1

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Use the generated TypeScript types of layout query in `+layout.svelte` as described above

**Comment by jycouet** [comment]
Thanks @grischaerbe for reporting this.
I'm preparing a talk for this afternoon and hit the exact same thing.

As a temporary workaround, I could suggest to use `houdini@0.16.8`.
But, as you know it's _"only"_ types. 

Anyway, we will fix this asap.
