### ISSUE TITLE
setSession not working? session is empty in client.js (Setting up auth following docs)

### ISSUE THREAD

**Issue by davidmadon** [HoudiniGraphql/houdini#640]
### Describe the bug

Hi,
First, thanks for a great library! Appreciate all the hard work!

I'm trying to setting up JWT auth according to the recommendations in the [Houdini docs](https://www.houdinigraphql.com/guides/authentication).

When I try to access the session inside of `client.js` it's empty.

This is my `hooks.server.js` file:

```
import { setSession } from '$houdini';

export async function handle({ event, resolve }) {
	// get the user information however you want
	const cookie = event.cookies.get('session');
    const session = cookie ? JSON.parse(cookie) : cookie;

	console.log(session); // This output is correct, an object containing my AuthToken.

	// set the session information for this event
    setSession(event, {session})

	// pass the event onto the default handle
	return await resolve(event)
}
```

And my `client.js` file:
```
import { HoudiniClient } from '$houdini';

async function fetchQuery({
	fetch,
	text = '',
	variables = {},
	session
}) {
	const url = import.meta.env.VITE_GRAPHQL_ENDPOINT || 'http://graphql.local/graphql';

	const headers = {
		'Content-Type': 'application/json'
	}
	
	console.log(session); // This outputs an empty object

	if (session?.session?.auth) {
		headers['Authorization'] = 'Bearer ' + session.session.auth
	}

	const result = await fetch(url, {
		method: 'POST',
		headers,
		body: JSON.stringify({
			query: text,
			variables
		})
	});

	return await result.json();
}

export default new HoudiniClient(fetchQuery);
```

The console log returns an empty object `{}`.

I've been wrestling with this for 2 days now.. 😅 Any insights are greatly appreciated! 

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

Implement auth following the docs: https://www.houdinigraphql.com/guides/authentication

**Comment by davidmadon** [comment]
Dependancies:
```
"devDependencies": {
        "@brainandbones/skeleton": "^0.56.2",
        "@sveltejs/adapter-auto": "next",
        "@sveltejs/kit": "next",
        "@tailwindcss/forms": "^0.5.2",
        "@tailwindcss/typography": "^0.5.3",
        "autoprefixer": "^10.4.7",
        "eslint": "^8.16.0",
        "eslint-config-prettier": "^8.3.0",
        "eslint-plugin-svelte3": "^4.0.0",
        "graphql": "^15.5.0",
        "houdini": "^0.17.2",
        "houdini-svelte": "^0.17.2",
        "postcss": "^8.4.14",
        "postcss-load-config": "^4.0.1",
        "prettier": "^2.6.2",
        "prettier-plugin-svelte": "^2.7.0",
        "svelte": "^3.44.0",
        "svelte-check": "^2.7.1",
        "svelte-preprocess": "^4.10.7",
        "tailwindcss": "^3.1.5",
        "typescript": "^4.7.4",
        "vite": "^3.1.0"
},
```

**Comment by AlecAivazis** [comment]
Sorry to hear you are running into this @davidmadon :(

Do you have the time to put together a stackblitz that shows the issue? The e2e tests are passing so I suspect there is something subtle going on here

**Comment by davidmadon** [comment]
Hi @AlecAivazis! Sure, never used stackblitz but will give it a go :)

**Comment by davidmadon** [comment]
Okey I've put together a stackblitz showing the issue.

https://stackblitz.com/edit/sveltejs-kit-template-default-nexpnj?file=src/hooks.server.js

Notes:

- I used the stackblitz SvelteKit template as a start
- Installed Houdini following the docs
- Added auth following the Houdini docs
- I used a mock graphql server (https://api.mocki.io/v2/c4d7a195/graphql) (It's throwing some CORS errors, but only after the session issue so it shouldn't make any differens)
- I dropped a `+page.gql` file in the `about` route just to trigger a call to the Houdini client.
- I've added `console.log` of the data before setting the session in `hooks.server.js` and for receiving the data in`client.js`. 

The session in `client.js` is empty.

**Comment by davidmadon** [comment]
Strange, when the stackblitz is running the first time it's throwing some errors. When I run `npm run dev` a second time it works..

**Comment by AlecAivazis** [comment]
Awesome, thanks for doing that! I was able to reproduce your issue. I'll let you know when I found the problem 👍 

> Strange, when the stackblitz is running the first time it's throwing some errors. 

I think this is because of an error thrown when trying to pull your schema down. I haven't looked too closely but I also see the need for a double refresh.

**Comment by AlecAivazis** [comment]
Good news! I found the issue. Should have a fix very soon. This was a good catch - thanks for submitting something @davidmadon!

**Comment by davidmadon** [comment]
Thats awesome!

I can confirm it fixed the issue for me :)
