### ISSUE TITLE
Can't run a SvelteKit project with Houdini on Windows

### ISSUE THREAD

**Issue by samuel-utbult-oborgen** [HoudiniGraphql/houdini#656]
### Describe the bug

I have a root page that is only defined through the file `src/routes/+page.svelte`, which means no `src/routes/page.ts` (or `src/routes/page.js`) file is needed. If I start the project without Houdini applied as a plugin in `vite.config.js`, this file is generated:

```
export { default as component } from "..\\..\\..\\src\\routes\\+page.svelte";
```

However, this file is generated when Houdini is applied as a plugin in `vite.config.js`:

```
import * as shared from "..\\..\\..\\src\\routes\\+page.ts";
export { shared };
export { default as component } from "..\\..\\..\\src\\routes\\+page.svelte";
```

This file refers to a non-existent file `src/routes/+page.ts`. This is not a problem on macOS 12 as the runtime seems to ignore it, but on Windows 10, this error is shown in the web browser when visiting that page:

```
[plugin:vite:import-analysis] Failed to resolve import "..\..\..\src\routes\+page.js" from ".svelte-kit\generated\nodes\3.js". Does the file exist?
C:/Users/my-username/path/to/svelte/project/.svelte-kit/generated/nodes/3.js:1:26
1  |  import * as shared from "..\\..\\..\\src\\routes\\+page.js";
   |                           ^
2  |  export { shared };
3  |  export { default as component } from "..\\..\\..\\src\\routes\\+page.svelte";
    at formatError (file:///C:/Users/my-username/path/to/svelte/project/node_modules/vite/dist/node/chunks/dep-61d2428a.js:42899:46)
    at TransformContext.error (file:///C:/Users/my-username/path/to/svelte/project/node_modules/vite/dist/node/chunks/dep-61d2428a.js:42895:19)
    at normalizeUrl (file:///C:/my-username/path/to/svelte/project/node_modules/vite/dist/node/chunks/dep-61d2428a.js:39763:33)
    at async TransformContext.transform (file:///C:/Users/my-username/path/to/svelte/project/node_modules/vite/dist/node/chunks/dep-61d2428a.js:39896:47)
    at async Object.transform (file:///C:/Users/my-username/path/to/svelte/project/node_modules/vite/dist/node/chunks/dep-61d2428a.js:43148:30)
    at async loadAndTransform (file:///C:/Users/my-username/path/to/svelte/project/node_modules/vite/dist/node/chunks/dep-61d2428a.js:39539:29
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

If `src/routes/+page.ts` is created without any content, another very similar error occurs on Windows about `src/routes/+layout.js`, which does not exist either. Here, macOS do complain and warns that `Sourcemap for "/src/routes/+layout.svelte" points to missing source files` but no problem occurs in practice. The following has been generated about `src/routes/+layout.js`:

```
import * as shared from "../../../src/routes/+layout.js";
export { shared };
export { default as component } from "../../../src/routes/+layout.svelte";
export const server = true;
```

However, without Houdini, this is generated, which just refers to the default layout:

```
export { default as component } from "..\\..\\..\\node_modules\\@sveltejs\\kit\\src\\runtime\\components\\layout.svelte";
```

The problem can be circumvented by creating empty files on the paths that SvelteKit complains about not finding.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Use Windows 10.
2. Set up a skeleton SvelteKit project (https://kit.svelte.dev/, bottom right)
3. Add Houdini as described in https://www.houdinigraphql.com/guides/setting-up-your-project#starting-a-new-project
4. Start the project, open a web browser and go to the described localhost address.
6. See the error.

**Comment by samuel-utbult-oborgen** [comment]
I am running 0.17.4 and still getting the error.

**Comment by AlecAivazis** [comment]
Are you getting the source map in `0.17.4`?

**Comment by ryou90** [comment]
Hi,
I am using the latest version 0.17.4 with Windows. Get also the same problem as described above. The only current solution is to manually create the page.js and layout.js files.

**Comment by AlecAivazis** [comment]
Damn okay. Would one of you be willing to hop on a call with me at some point to dig into this? Like I said, the e2e tests run on a windows machine and we don't have the `+page.ts` file so I'm surprised to hear it's breaking. Are you using Windows 10 aswell @ryou90?

**Comment by ryou90** [comment]
@AlecAivazis yes I using Windows 10.

I'm really new to svelte + svelteKit, but sure... happy to help as best I can :)

**Comment by samuel-utbult-oborgen** [comment]
> Are you getting the source map warning in `0.17.4`?

I tried to reproduce the sourcemap warning on any version but i can't seem to reproduce it. Sorry.

> Damn okay. Would one of you be willing to hop on a call with me at some point to dig into this? Like I said, the e2e tests run on a windows machine and we don't have the `+page.ts` file so I'm surprised to hear it's breaking. Are you using Windows 10 aswell @ryou90?

I could call you. The most suitable time for me would be during a European evening or on a weekend. However, my employer is fine with me taking a call during a weekday.

**Comment by AlecAivazis** [comment]
Fantastic! If either of you could reach out to me on discord, we can try to find a time to work through this. Unforunately, I dont have a windows 10 machine so it's kind of tricky for me to do it on my own

**Comment by stevefan1999-personal** [comment]
I can also confirm this bug's presence in Windows 11

**Comment by jycouet** [comment]
I just had a try on `0.17.14` & windows 11, but I can't produce the issue. (Nothing in console, nothing in build)

Was it fixed, or I don't look at the right thing?

**Comment by AlecAivazis** [comment]
I'm going to close this issue since it's gone very stale. If someone runs into this and wants to give it a shot, I'd gladly review a PR or help anyway I can.
