### ISSUE TITLE
Type error when using loadAll function.

### ISSUE THREAD

**Issue by revnelson** [HoudiniGraphql/houdini#658]
### Describe the bug

There is a type error showing in VS Code when using the `loadAll` function. The full error code is:

```
Argument of type 'Promise<{ GetMainMenu: GetMainMenuStore; }>' is not assignable to parameter of type 'LoadAllInput'.
  Type 'Promise<{ GetMainMenu: GetMainMenuStore; }>' is not assignable to type 'LoadResult'.
    Type '{ GetMainMenu: GetMainMenuStore; }' is not assignable to type '{ [key: string]: QueryStore<any, {}, {}>; }'.
      Property 'GetMainMenu' is incompatible with index signature.
        Type 'GetMainMenuStore' is not assignable to type 'QueryStore<any, {}, {}>'.
          Types of property 'store' are incompatible.
            Type 'Writable<{ data: GetMainMenu$result | null; errors: { message: string; }[] | null; isFetching: boolean; partial: boolean; source: DataSource | null; variables: null; }>' is not assignable to type 'Writable<{ data: any; errors: { message: string; }[] | null; isFetching: boolean; partial: boolean; source: DataSource | null; variables: {}; }>'.
              Type '{ data: GetMainMenu$result | null; errors: { message: string; }[] | null; isFetching: boolean; partial: boolean; source: DataSource | null; variables: null; }' is not assignable to type '{ data: any; errors: { message: string; }[] | null; isFetching: boolean; partial: boolean; source: DataSource | null; variables: {}; }'.
                Types of property 'variables' are incompatible.
                  Type 'null' is not assignable to type '{}'.ts(2345)
```

As far as I can tell, I am using the function exactly as stated in the [Deep Dive: Loading multiple stores simultaneously](https://www.houdinigraphql.com/api/query#manual-loading) section of the docs. It seems to work as intended, just gives that dreaded red squiggly.

Additionally, types are not inferred/generated when using the `loadAll` function, so I'm currently having to use it as follows to get types working in the svelte page:

```typescript
...((await loadAll(
	load_GetMainMenu({ event }),
	load_GetCart({ event }),
	load_GetCurrentUser({ event }),
)) as unknown as {
	GetMainMenu: GetMainMenuStore
	GetCart: GetCartStore
	GetCurrentUser: GetCurrentUserStore
}),
```

### Severity

annoyance

### Steps to Reproduce the Bug

Add the loadAll function to a `+page.ts` or `+layout.ts` file.

**Comment by AlecAivazis** [comment]
Ouch, okay thanks for reporting this. I'll try to find some time over the weekend to adress it

**Comment by AlecAivazis** [comment]
Found some time to look at this over lunch and I _think_ This is specified correctly

<img width="513" alt="image" src="https://user-images.githubusercontent.com/916317/198729880-586d2607-1959-4953-8e57-f8920e0d7bf1.png">

Admittedly, I'm not the strongest with typescript so i could be missing something. I'm going to try to get some help with this but if you have any ideas for how to fix this, I'm all ears. I suppose worst case scenario you will just have to pass the return type as a generic parameter to `loadAll`

**Comment by AlecAivazis** [comment]
Okay, I reached out to some people and I think they found a solution. I'm honestly amazed how quickly they came up with it. I haven't taken the time to test it in the e2e tests but on the surface it does seem to work. Leave the link here for future me: [link](https://www.typescriptlang.org/play?target=99#code/FAFwngDgpgBAigVygJzAZRAe2VAPAfQBEBDEYgGhnwEkA7CBEAPhgF4YBvGAE1OIC4qJMjAC+oSLAAymYtwBKUAM4IANiDYwACskwBbAJZK8XANoBrKGEFKQyA7QDmAXUGIU6LDlzFaYShyiLEES0DAycgCCqqp0DBrsEQrKahoAPjCKAMbY3Li29k6USYoq6kzAwAD0VTCOUCBKMMQxMCAAFrAAbi1ITQBmunrNtDCYAEYAVlBZIKGwAGq9UADy-bgAKjBQAB4gULTcTdm5uDqY0MjgANJWlAi05rSYAO60TCzsGxZWmP0wG2clRqbWQviU-WweiaAANIjAMgAhBEwADCKIAdFiYW1MDA4TAAGQwZHE9HErEYmHzGAAVVoBkwtA2mDo+2QxlmjNouFpnxgAApads9gcjiMwDAAPyC8yCWkASjYLC6mAM3BggloUC6KCVu32hyaArlMAc-RQMGoStYKrV3GAAEgZdQnVqdSgANyVaq1OzgyHIaH4kopdQ4hxYM2NZovYgGfYa8DQX2ggNQ2EcAThWTJMogUQ43wanAQVTELLKNqdGCWSV-auwVS5mA4fMwF4J9r44jU5OwOgW5Ch-ObEWG8VJaKxeiMflbA1i44zU7my23fxm2hDzJVxdGnNyUqpFgyjhO0zXLcwDeuGBLVRINa4SJxhNQPKlD7AUSagHjpdDzzVJpRgV940TTYWHdXVkEqYglDAWgshgfoHi5JkYGbKIYlwJ0QXqbV7BQqNaGIZBdBeRtmgo4hJRyCiZhAVQwCdKQAIPKcYjiRhyHw2pCJQAwSLxeoNBaVQxn+DpYAceImkwGTkE7Yxo1Q+NVAU0YZPxSlqUdJImn3SdTGcJgBSdR1KWwo5BEMp0FUEc5DGMXkGSZFk2RQTkQG5XBz0dR1L2vOsG0Mu9BxQEdUlwQzLzMp1RFMWgED0cYUDMipgAQpCULQ5DfMwmzpwsqysRspQ7NzaceJAUzgEc7QhiMPATmQPICgcRxKHcVAMGwPBfE3QIPhYAKQReWBtQ-XEYByGImOaVoGx0iBmuMJoHGaGAlC61QmyMDQOlIDtYE7VpiDfDQtrW-QWoxCSRiTTpRnGBADFUDUEAgJ0cloWwYFulzlCqo8wzq5xNHq-jqIARz6QrRkmmB2mIXVZvBSbkDNJoXk6JTtloOxJSMbagZasZsd8MYpkWhtyY236mQBoxnIp9gBR6VRQe4GrZxARquZxoDj3UZVLIAchk2gJevIXCWJCX+gcCSwFlrb5cVrJSCydp1dGLnKkdQNBT+gGDmJqSsNzJQlQCx0DH+AUAEJWfWqABQt1AlQVmApZe-XCeJu3LMdDpKJgbUqIAUQo7ABQlwAZcnxaWIyaZ5xJgLn1VrKxUOwEYaemWZAYQ4wkzxYqYglhVLPESyQXVC3HclamvclTsOmomEMVTmA9AadpMAdQLHcFN27uMT2ie9kPAsdBnlAxBglHaafg7r7ZNNge3jYLgUzY0H5Ny5pBIYbFZadmDEvYMZR19nzhQ4dp2J+BznlgVOf54X92lGXhAq8P6PigLXH+v4oDbyfj-MO7QI5RxgLHXQyBSowJhMnAAJBwOsv5SYZ22tnDUp9YAm2phMYuGgIBlxmlGKuqgMQwAAJqYAQP3QBlCy7UTbCBBsxBrZyHwP1HAqF0KI30j-MB89xBSLrolI2IJnhUWOhoSaEt0bzX2rMGaj0Vo1kXkoSgV187YxknoJ0l0IJNUnlAB6MQBT6NrjDHR0k9F-xorANsmBVC6g1EoUSeJxgVnMGMWC1FiGnVOsIxwBhdSjD4TgQ+yAEAlwTE6faGhuFi3YIEI2JsD7Mw0O3K2FVv6N3+Ko4RzZMDmC6s0TOi9KAJg7B9SSf0yBbR0nWSyY8BRvxag-MAX9oGBUvhQh6ShdqOFoAKTJIBKAWKae3SRECoG71GUxcZkzpnP1mXxH+IIFmFNgpKcJHSazkMWsWZoEyDBTLUlGWZz91nX0GPoaOM875KFQfPQ5Vjga2NUN8+ezyQA3w+ffJZGI9DEAgAKHKyFBTH0oMQ5wNoWCmGfvPOseyYGOhBRiYhXzfnEIVKYAADM4HFP9UWYskYFOlyy5EwwqbAbgTIoBOhwCABAyBRiPProffh3B8CQjxOweFKEBSNTZq5LgorBBcF4GQQQABGMQYhPgsAFHKzAmAFU8D4Kq9Voha6CpsvgQJ2NxWIQRVKpy7t-IwEtfqpV2YABMxrNWCi4M6zgBrlUwA9b+E1lRBUJCFSVc1oqpUBEjlAF4G5BDmstVKsQjjQXS3yf9LxNjmyOAVEAA).
