### ISSUE TITLE
Loading States as a first-class citizen

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#662]
Here is the most recent design doc for this feature: https://certain-dedication-0a6.notion.site/Loading-States-222a3db3810240d2a31ccce9a0acbcfa

### Describe the feature

@ronkeiser had a _very_ cool idea for improving the support for loading states that comes in 2 parts:

1. an extension of the partial data support that returns the full shape with placeholder values for all of the leaves (instead of just returning null for the first non-existent value we run into)
2. A new tag in any component, something like  `<houdini-loading>` that lets the user design their loading states with arbitrary granularity. Conceptually, it acts very much like an ErrorBoundary in React: if a loading value from the extension described in 1 is ever rendered, the closest loading state will render instead of the rest of the component (going up the tree).

These 2 features combined result in something like this:

```svelte
<script>
    const Foo= graphql`
        query { 
            friends @houdini(loadingCount: 4) { ...UserCard } 
        }
      `
</script>

{#each users Foo.data.friends as friend}
    <UserCard user={friend} />
{/each}
```
```svelte
<script>
   export let user

   $: data = fragment(user, graphql`
       name
   `)
</script>

<houdini-loading>
loading user...
</houdini-loading>

<div>{data.name}</div>
```

Open questions / Notes:

- Does `houdini-loading` _have_ to be at the root of a component and only one of them?

**Comment by ronkeiser** [comment]
A magic prop would definitely be useful for certain situations and generally should probably be available so the component can be aware of the loading state. That being said, using a component like `houdini-loading` is more declarative and helps to reduce the repetition of logic blocks for a need which many, many components will have.
