### ISSUE TITLE
Bidirectional cursor-based pagination

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#670]
### Describe the feature

As discussed in #666, we should expand the current implementation of `@paginate` to support bi-directional pagination. 

I suspect that we should probably loosen the constraints on the current pagination behavior to not think of each direction as a distinct feature. The generated stores already have `loadPrevious` and `loadNext` so i think we should be able to just have both always working. The original constraint was in place because I was being a bit lazy about computing the initial page size but as the feature developed it ended up not being so necessary. It does help us a bit with the type information but again, if the store can just always do both then thats okay. 

One small hurdle is to figure out if we want to force users to provide page sizes for both directions. I think the best DX would be to give the user the freedom but not force them. That is to say, if they specify `first` and no `last` then we can just use the `first` value as the page size for reverse pagination (similarly for `last`). If they provide both, we should use the appropriate one for the appropriate direction. This will mean adding some bits to the generate artifact so we can persist the two values but that's relatively harmless.

**Comment by AlecAivazis** [comment]
If anyone is interested in working on this, it's a small-to-medium level difficulty. Will require _some_ work in the codgen portion but most of the work boils down to moving existing code around

**Comment by samuel-utbult-oborgen** [comment]
If bidirectional cursor-based pagination is implemented, I'd guess the idea would be to be able to start at a specific cursor and then load forwards and backwards based on this cursor. The cursor would have to belong to an element in the list, which needs to be included somehow. I have a custom implementation of this in the project I'm working on where a component accepts a fragment, which the list is initialized with. Then I load the backwards and forwards elements based on the cursor. Would something like this be suitable or would another approach be better?

**Comment by AlecAivazis** [comment]
hey @samuel-utbult-oborgen! 

So the way things work now, the `@paginate` directive is applied to a field that contains the initial value of the list (this is what's shown for SSR). The `pageInfo` value corresponds to this initial load. From that result, we are able to fire another query to load the next page in either direction. I think this is a simpler approach than basing it off of a single cursor in the list but I'm open to suggestions if you have a particular api in mind. 

One side effect of this is that the query must be valid. Since it doesn't make sense to ask for `first` and `last` in the same query we only have one pageSize that we can infer for the loading. That's probably a fine compromise and is already working with the current implementation so I'm inclined to keep it that way. That means that implementing this really just boils down to:
- consolidating the [query](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/runtime/stores/pagination/query.ts)and [fragment ](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/runtime/stores/pagination/fragment.ts) stores that there was no distinction between the two stores (ie, `QueryStoreCursor` should have both `loadNextPage` and `loadPreviousPage` ). 
- make the svelte plugin generate the correct stores which is specified [here](https://github.com/HoudiniGraphql/houdini/blob/5319c7e16762a0f64ea32dae96735b72be1acf40/packages/houdini-svelte/src/plugin/kit.ts#L369-L384).
- Various bits of cleanup like removing the [direction key](https://github.com/HoudiniGraphql/houdini/blob/a8237aa5c309de68b126ed55c6fe3fd6f1b24503/packages/houdini/src/runtime/lib/types.ts#L85) of the artifact's refetch block, which is set [here](https://github.com/HoudiniGraphql/houdini/blob/a8237aa5c309de68b126ed55c6fe3fd6f1b24503/packages/houdini/src/codegen/transforms/paginate.ts#L333).

I'll try to keep this comment up to date as I think of more things 👍 If you or someone else wants to tackle this, I'd gladly offer any guidance necessary.

**Comment by samuel-utbult-oborgen** [comment]
Copied from #824:

### Describe the feature

How would you know in which end of a list an error occured when #670 is implemented? I have a custom implementation of bidirectional cursor-based pagination where a "try again"-button is shown on either the start or the end of the list, which the users can press to refetch the query that caused an error. However, this logic needs to know where the error occurred. I have three possible cases in my implementation:

1. The error occurs during the initial loading.
2. The error occurs when loading the previous page.
3. The error occurs when loading the next page.

It would be useful to get some kind of signal about where the error occurred when bidirectional cursor-based pagination is implemented.

### Criticality

cool improvement, my projects will benefit from it

**Comment by AlecAivazis** [comment]
i'm gonna pick this up and get it in for `1.0`. 

@samuel-utbult-oborgen I will let you know once I have a better idea of the exact details.  The way I see things now, there will be 2 distinct methods: `loadNextPage` and `loadPreviousPage`. When you call one of them, you can `await` them in an async function or use `catch` to capture the error message and then tie it up to your component's error state.  Would that work for your situation?

**Comment by samuel-utbult-oborgen** [comment]
> i'm gonna pick this up and get it in for `1.0`.
> 
> @samuel-utbult-oborgen I will let you know once I have a better idea of the exact details. The way I see things now, there will be 2 distinct methods: `loadNextPage` and `loadPreviousPage`. When you call one of them, you can `await` them in an async function or use `catch` to capture the error message and then tie it up to your component's error state. Would that work for your situation?

Yes, I think I could make that work. Thank you.

**Comment by AlecAivazis** [comment]
I just pushed up a working version of bidirectional pagination in #846 that behaves like I outlined above. Still have to review it but at least this means it will be in `1.0` for sure. Thanks for being so patient everyone!
