### ISSUE TITLE
Hint in docs: schema.graphql required to start dev server

### ISSUE THREAD

**Issue by ryou90** [HoudiniGraphql/houdini#671]
### Describe the bug

Hello,
When my graphql endpoint is not available, npx houdini init fails. The consequence is that no schema.graphql is created. But this file is needed to start the dev server. And there is no hint in the docs to create this file if it is not available. 

Also, I need to add the following line `type query` because the schema.graphql must not be empty.

A little hint in the docs would certainly be useful for others.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. execute npx houdini init
2. graphql endpoint available -> No
3. Abort
4. npm run dev -> failed

**Comment by AlecAivazis** [comment]
Ah yea, we can do a better job there for sure. `init` is responsible for creating a lot of files that won't work without it but we should at least point the user to the setting up guide. Thanks for the report!
