### ISSUE TITLE
Houdini package publish files

### ISSUE THREAD

**Issue by romelperez** [HoudiniGraphql/houdini#698]
### Describe the bug

The [NPM package houdini](https://www.npmjs.com/package/houdini) currently has 27MB in file size since it is not explicitly defining package exported files.

The package can use the [`package.json` `files` setting](https://docs.npmjs.com/cli/v8/configuring-npm/package-json?v=true#files) to define what files to publish to NPM. This way the final bundle file size should be reduced.

Let me know if you need help and I can submit a PR with it.

### Severity

annoyance

### Steps to Reproduce the Bug

Go to https://www.npmjs.com/package/houdini and check the "Unpacked Size" field value.

**Comment by AlecAivazis** [comment]
Thanks for reporting this @romelperez! If you wanna throw a PR together to fix this, i'd gladly review it. While you're at it, mind handling #657?

**Comment by romelperez** [comment]
Hey, perfect, I'll work on those two! 🙌
