### ISSUE TITLE
types generation doesn't go deeper than deepest houdini_load

### ISSUE THREAD

**Issue by gterras** [HoudiniGraphql/houdini#700]
### Describe the bug

With the following structure: 

```ts
routes
  - +layout.ts 
  folder1 
     - +page.svelte 
```

and `+layout.ts` containing a `houdini_load` export,

`houdini generate` won't generate `folder1/$types.d.ts` (unlike svelte-kit)

So importing from `./$houdini` in `folder1/+page.svelte` will trigger a TS type not found error: 

```ts 
// folder1/+page.svelte
import type { PageData } from './$houdini' // ts error 
```

Workaround is to import an upper type:
```ts
// folder1/+page.svelte 
import type { PageData } from './../$houdini' // ok 
```

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Follow the steps above

**Comment by AlecAivazis** [comment]
Thanks for reporting this @gterras!

@sjcobb2022 do you have time to look into this?

**Comment by sjcobb2022** [comment]
> Thanks for reporting this @gterras!
> 
> @sjcobb2022 do you have time to look into this?

Sure I can take a look.

@gterras could u make a stackblitz reproduction because there is really enough info for me to go off. Feel free if you need an endpoint or anything to test.
