### ISSUE TITLE
PageData has generic type if beforeLoad is declared in layout.ts

### ISSUE THREAD

**Issue by gterras** [HoudiniGraphql/houdini#712]
### Describe the bug

Repro: 
- https://github.com/gterras/houdini-typeloss-repro 
- branch `type_loss_repro`
- Sorry for accidental merge request ! 

See the `src/routes/layout-type-loss` folder. I didn't know how to write a test for a TS check so you just have to run the app and open `layout-type-loss/+page.svelte` in your IDE and see the type is:

```ts
  data: {
    [x: string]: any
  }
  ``` 
  You can toggle the bug on/off by commenting `beforeLoad` in the `+layout.ts` file. 
  
  It took me a long time to reproduce because of a certain fragility/randomness to the thing (at least that's what appeared to me). I made sure the error is reproductible if you delete `.svelte-kit` and `$houdini` folders before running the app. I think there are other ways to trigger the error. 

Sorry if it's unclear as I keep feeling turning around something that I can't understand. Don't hesistate to ask for more information!

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Follow the steps above

### Reproduction

https://github.com/gterras/houdini-typeloss-repro

**Comment by sjcobb2022** [comment]
Just fixed this vicariously in #715

**Comment by gterras** [comment]
Thanks a lot for this :pray:
