### ISSUE TITLE
PageData  has a promise type if layout afterLoad is async

### ISSUE THREAD

**Issue by gterras** [HoudiniGraphql/houdini#713]
### Describe the bug

Repro:
- https://github.com/gterras/houdini-typeloss-repro
- branch `layout-async-afterload`

See the `src/routes/layout-async-afterload` folder. I didn't know how to write a test for a TS check so you just have to run the app and open `layout-async-afterload/+page.svelte` in your IDE and see the type is:

```
  data: {
    // ... 
    then: 
    catch: 
    finally: 
  }
```
You can toggle the bug on/off by commenting afterLoad in the +layout.ts file.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1- Follow the steps above 

### Reproduction

https://github.com/gterras/houdini-typeloss-repro

**Comment by sjcobb2022** [comment]
This should be pretty easy to implement. Just need to use the Awaited\<F\> type.

Currently it uses the Promise\<ReturnType\> but Awaited\<F\> unwraps this for us.
