### ISSUE TITLE
quietQueryErrors custom logic

### ISSUE THREAD

**Issue by FlymeDllVa** [HoudiniGraphql/houdini#721]
### Describe the feature

Hi, I want to be able to throw 200/400 on some types of errors (with loaded data) and 500 only on the real ones from the server or other types of errors not handled by the client

**Comment by FlymeDllVa** [comment]
If quietQueryErrors is false, how do you propose to handle the errors? Consider that if the query returned an error, then it completely failed?
Is it possible to handle error from +page.gql, +layout.gql? I want to handle error with current page template.

**Comment by AlecAivazis** [comment]
You should be able to handle errors by defining a `+error.svelte` file like normal, is that not working for you?

**Comment by FlymeDllVa** [comment]
I would like to be able to write my own error handler.
I don't quite understand why the client doesn't return data in case of any error, but only returns errors. I would like to be able to work with partial GQL response.

**Comment by FlymeDllVa** [comment]
I see that Apollo provides [errorPolicy](https://www.apollographql.com/docs/react/data/error-handling/) for this.
I'm thinking about the best way to return entities with partially unavailable fields based on their permissions, maybe you have a beast practice?

**Comment by jycouet** [comment]
Any reason why not having `quietQueryErrors: true`?
Because with this, you would have `data` & `errors`, similar to what you showed in Apollo doc.

**Comment by FlymeDllVa** [comment]
If I set quietQueryErrors to true, all I get is a throw 500 call, but when I subscribe to store `$GQL_*` I only see
 ```{
  "data": null,
  "errors": [
    {
      "message": "err",
      "path": [
        "t",
      ]
    }
```
Although the http response is back and the data

Perhaps you know a more elegant way of working with partial answers? +error.svelte doesn't work for me, because I don't want to draw an alternate page template.

**Comment by jycouet** [comment]
Are you sure your field is `nullable`?

Can you check first in graphiql for example with your query?
Something like: (where you see ✅releaseCreatedAtUtc and ❌ makeError)
![image](https://user-images.githubusercontent.com/5312607/204652414-8aa7a320-2154-41ea-a86a-675bb2612d76.png)

Inside the browser with Houdini, I get the same result with also the data and the error.
![image](https://user-images.githubusercontent.com/5312607/204652865-fc6f5737-d37d-4c6f-88ea-86d9f0004311.png)

**Comment by FlymeDllVa** [comment]
Thanks for the example, I understand the logic, it works well.
Do I understand correctly that the output in data takes into account the error path?

Is there no way to return a standard type value if a mandatory field has an error?
I'm wondering how I can return a PERMISSION_DENIED error for fields that are not available to the user. I don't want to make all fields optional, as they are mandatory if there are enough permissions.

**Comment by FlymeDllVa** [comment]
In fact, looking at the way it works in the example, I had an idea that in Houdini you could make a mark @reload based on path, which in case of an error in a branch, could try to load the part of data that was not loaded the first time with a separate request. 

I don't need it, but it might give me some ideas

**Comment by jycouet** [comment]
I would suggest you to read about graphql and nullability as it's a great concept enabling a lot of patterns (that could be counter intuitive at the beginning when coming with a database background for example). 

Houdini, is just complying to the spec 🎉
So, I'm not sure how to help here. 

_Side node: in your `client.ts`, you can look at the result and have a retry custom logic with the raw result._

**Comment by FlymeDllVa** [comment]
Yes, all in all it is clear, thank you!

Rather, I was trying to understand what alternatives to error handling can be implemented using Houdini

Thanks for the cool solution to work with GraphQL!

**Comment by xmlking** [comment]
I am trying to handle errors my self after setting `quietQueryErrors: true`  at this code:

https://github.com/xmlking/svelte-starter-kit/blob/main/src/routes/(app)/dashboard/policies/%2Bpage.server.ts#L58-L66

errors are not printed at this statement `console.log('errors', errors);`  it was  captured in `try catch` block. 

That means `quietQueryErrors` has no effect  on global queries in `+page.server.ts` ? is this a bug?

you can reproduce this issue, in my repo by running `npm run dev` and access `http://localhost:5173/dashboard/policies?name=&subType=subject_type_group&limit=50`  ,  it is connected to `hasura` cloud backend. 

I intentionally made typo `subject_type1` to cause error:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/627951/205890929-d4a6ed88-a79d-46b9-80da-c1a26da99ac3.png">

**Comment by xmlking** [comment]
lets assume I am not using `try/catch`,  I am fetching data in server-side code (+page.server.ts)
with  `quietQueryErrors: true`  I should be able to destructure `errors, data` from **QueryResult** right ?
why it is still throwing 500 error ? the execution is not reaching `console.log` statements. 

can you please try this case from your side and verify? I am not sure where I am doing mistake to suppress error throwing.  

```ts
const { errors, data, isFetching, source } = await GQL_SearchPolicies.fetch({
	event,
	policy: CachePolicy.CacheAndNetwork,
	variables
});
console.log('errors', errors);
console.log('source', source);
console.log('isFetching', isFetching);
console.log('data', data);
```




<img width="790" alt="image" src="https://user-images.githubusercontent.com/627951/207397782-f683e5fb-896b-4fc9-b433-3a7a2dcc6b9a.png">

**Comment by jycouet** [comment]
If you want to have results in the server side you have to have `blocking: true`
Something like 👇
```ts
const { errors, data, isFetching, source } = await GQL_SearchPolicies.fetch({
	event,
        blocking: true,
	policy: CachePolicy.CacheAndNetwork,
	variables
});
```

You can check in the section in the doc `deep dive: Blocking navigation` on this page https://www.houdinigraphql.com/api/query#manual-loading
You will learn that `blocking` is not ideal in CSR mode (subsequent client-side navigation).

With `quietQueryErrors: true` I'm doing some checks in the client side (with the `browser` variable)

**Comment by xmlking** [comment]
even with `blocking: true` still error is thrown. 

<img width="713" alt="image" src="https://user-images.githubusercontent.com/627951/207403286-6687da4e-3554-4288-b623-70f7272084b1.png">

**Comment by jycouet** [comment]
I cloned the repo, but I have to log with my account... Sorry I will not do it!
Could you reproduce a minimal reproduction?

A few things on top of my head: 
- With an error `500`, you can handle it in `client.ts`, no? (quiteErrors, is happening later)
- a bit strange to have this error, as when I change the query, and the schema doesn't have this field, I have a message directly:
![image](https://user-images.githubusercontent.com/5312607/207460923-79becbe3-c1db-41b8-a205-4fca66bafea6.png)

I'm not sure if we should continue speaking on this closed issue. (Reopen it? create a new one?)

**Comment by AlecAivazis** [comment]
@xmlking any chance you've been able to put together a reproduction i can look at? I'd like to get this issue fixed for the upcoming `1.0` release

**Comment by AlecAivazis** [comment]
Ah! I think i found the problem - the repo you linked to has `quietQueryErrors` in the top level config file. It belongs under the `houdini-svelte` plugin. I'm going to close this since its gone a bit stale but if you are still running into an issue after moving the config value, I will gladly reopen to investigate (or you can open another issue)

**Comment by xmlking** [comment]
Thanks works now as expected 

is it safe to declare stores globally like this? https://github.com/xmlking/svelte-starter-kit/blob/main/src/routes/(app)/dashboard/policies/%2Bpage.server.ts#L21

**Comment by AlecAivazis** [comment]
It will definitely work but you need to be careful that the store does not contain any user-specific data. If you're sure that you aren't leaking data across requests, then its totally fine 👍
