### ISSUE TITLE
Unable to use fragment in root query

### ISSUE THREAD

**Issue by JacobArrow** [HoudiniGraphql/houdini#729]
### Describe the bug

I'm having trouble using a fragment in my root query.

### Severity

annoyance

### Steps to Reproduce the Bug

#Page 

```
<script lang="ts">
	import { type RootStore, graphql } from '$houdini';

	import PrimaryMenu from '$components/PrimaryMenu.svelte';

	const store: RootStore = graphql`
		query Root {
			...PrimaryMenu
		}
	`;

	$: ({ data: root } = $store);
</script>

<PrimaryMenu {root} />
```

#PrimaryMenu component
```
<script lang="ts">
	import { type PrimaryMenuStore, graphql, fragment } from '$houdini';

	export let root: PrimaryMenuStore;

	const data = fragment(
		root,
		graphql`
			fragment PrimaryMenu on RootQuery {
				menuItems(where: { location: PRIMARY }) {
					nodes {
						key: id
						parentId
						title: label
						url
					}
				}
			}
		`
	);
</script>
```

**Comment by AlecAivazis** [comment]
Sorry to hear you are running into issues - what problem at your running into?? Also, the fragment expression should be a reactive statement

**Comment by JacobArrow** [comment]
@AlecAivazis I'm getting typing errors on the `root` variable I'm passing into the component and also on the `root` variable used inside fragment. This means that I have no typings when on `data`. And when I `console.log(data)`, it returns `undefined`. What reactive statement am I missing?

**Comment by JacobArrow** [comment]
Okay, so after messing around a bit, I've found out that the fragment do indeed return correct data - so thats good!
But I am still unable to understand how I get the correct typing. The `root` prop seems to be of the wrong type. So what type should it be, if not `PrimaryMenuStore`?

**Comment by jycouet** [comment]
Souldn't it be something like: 
```ts
<script lang="ts">
	import { type PrimaryMenu, graphql, fragment } from '$houdini';

	export let root: PrimaryMenu;

	$: data = fragment(
		root,
		graphql`
			fragment PrimaryMenu on RootQuery {
				menuItems(where: { location: PRIMARY }) {
					nodes {
						key: id
						parentId
						title: label
						url
					}
				}
			}
		`
	);
</script>
```

**Comment by JacobArrow** [comment]
Oh wow... Now I feel stupid...

THANK YOU @jycouet!

I mixed up the typing... The store-type is used for queries, not fragments, I see that now.

**Comment by jycouet** [comment]
You know where I looked at? 
Your PR 🥳🥳🥳. Thx🙏

Would you close the issue or there is something else?

**Comment by JacobArrow** [comment]
Haha, at least I got it right in my PR

Thank you for your quick help on this one. I'm closing the issue.
