### ISSUE TITLE
Use env in houdini.config.js

### ISSUE THREAD

**Issue by JacobArrow** [HoudiniGraphql/houdini#734]
### Describe the bug

I'm trying to import my GraphQL endpoint in the houdini.config.js file via the .env file, but I unable to get it working. 
I have tried the following methods:

```
import { $env } from '$env/dynamic/public';
apiUrl: $env.PUBLIC_GRAPHQL_ENDPOINT
```

```
import { PUBLIC_GRAPHQL_ENDPOINT } from '$env/static/public';
apiUrl: PUBLIC_GRAPHQL_ENDPOINT
```

`apiUrl: process.env.PUBLIC_GRAPHQL_ENDPOINT`

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

Add variable to .env and try to import it houdini.config.js

**Comment by jycouet** [comment]
It was not possible to set the url via `env`. Thx for the request.

I just created a PR where it will be possible to do: 
```
{
  apiUrl: "env:PUBLIC_GRAPHQL_ENDPOINT"
}
```

**Comment by JacobArrow** [comment]
Thank you @jycouet !

**Comment by xmlking** [comment]
@jycouet can we also use env for access tokens ?
Eg., https://github.com/xmlking/svelte-starter-kit/blob/main/houdini.config.js#L18

**Comment by jycouet** [comment]
@xmlking it should work already in `schemaPollHeaders`.
It's not the case?

**Comment by xmlking** [comment]
I didn’t  know it works, based on PR https://github.com/HoudiniGraphql/houdini/commit/758683fdf5d28eaf995eae8acb3c03e231f91b56 I thought it only support for apiUrl
It didn’t work for me with "houdini": "0.17.14"

**Comment by jycouet** [comment]
Because it was already supported before 🥳
You should be able to see it in the doc as well 👍

**Comment by xmlking** [comment]
am I using `env:` syntax correct?  getting following error when useing `env:` syntax 

**houdini.config.js**
```js
        apiUrl: 'https://decent-donkey-56.hasura.app/v1/graphql',
	schemaPollHeaders: {
		'x-hasura-admin-secret': 'env:PUBLIC_CONFY_API_TOKEN' // <-- error with this setting
                // 'x-hasura-admin-secret': 'my_token_string' // <-- this works
	},
```

**Error:**

```
 Couldn't pull your latest schema: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: undefined.
```

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/627951/207407312-1a64c7e2-84a4-42d7-86e7-e80f34d7e333.png">
