### ISSUE TITLE
`env:` apiUrl & schemaPollHeaders

### ISSUE THREAD

**Issue by jycouet** [HoudiniGraphql/houdini#759]
am I using `env:` syntax correct?  getting following error when useing `env:` syntax 

**houdini.config.js**
```js
        apiUrl: 'https://decent-donkey-56.hasura.app/v1/graphql',
	schemaPollHeaders: {
		'x-hasura-admin-secret': 'env:PUBLIC_CONFY_API_TOKEN' // <-- error with this setting
                // 'x-hasura-admin-secret': 'my_token_string' // <-- this works
	},
```

**Error:**

```
 Couldn't pull your latest schema: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: undefined.
```

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/627951/207407312-1a64c7e2-84a4-42d7-86e7-e80f34d7e333.png">

there is multiple methods to use `env` in documentation, which cause confusion. Is this FAQ still valid ?   
https://github.com/HoudiniGraphql/houdini/blob/main/site/src/routes/guides/faq/+page.svx#L91-L119

_Originally posted by @xmlking in https://github.com/HoudiniGraphql/houdini/issues/734#issuecomment-1349291822_

**Comment by jycouet** [comment]
@xmlking, I opened a dedicated issue here; thx for reporting.

I think that the doc anyway needs an update with `env:` in the doc.
It should work for both... `apiUrl` & `schemaPollHeaders`

Could you log your value to make sure you have something inside?

**Comment by xmlking** [comment]
when I added `console.log('PUBLIC_CONFY_API_TOKEN>>>', process.env.PUBLIC_CONFY_API_TOKEN);` to  `houdini.config.js` it is printing  `PUBLIC_CONFY_API_TOKEN>>> undefined` 

my PUBLIC_CONFY_API_TOKEN is defined in `.env` file. I assumed it will pickup as vite use `dotenv`. 

it works when explicitly export variable. 
```shell
export PUBLIC_CONFY_API_TOKEN=xyz
npm run dev
```

it would be nice if we can make it work with `.env/.env.local` files like SvelteKit do for env variables.  e.g., https://github.com/xmlking/svelte-starter-kit/blob/main/src/lib/graphql/client.ts#L11

**Comment by xmlking** [comment]
I am using this as temp workaround.  Houdini `v0.17.14`  don't  have `apiUrl` env support. looking forward for next release!
 
```ts
// file: houdini.config.js
Object.assign(process.env, loadEnv(process.env.NODE_ENV, process.cwd(), ['PUBLIC', 'VITE']));
```

<img width="902" alt="image" src="https://user-images.githubusercontent.com/627951/207486282-f2097192-8ef3-43d4-8a2d-7e8fe229f458.png">

**Comment by AlecAivazis** [comment]
Found some time to address this. #779 makes things load environment variable from `.env` files using vite's `loadEnv` utility and takes into account the `svelte.config.js` file so it should replicate the behavior like you described. If you have the time to pull it down and give it a shot, i'd appreciate it

**Comment by xmlking** [comment]
Sure will do. Thanks for adding this.
Hope it will also work `.env.local` as we can keep local dev settings in local and not commit to git

**Comment by iolyd** [comment]
I'm facing this issue with both `.env` and `.env.local` files. If i log the env values sourced inside houdini's config `apiUrl(env)`, none of my variables defined in env files are available. I'm working with a pnpm monorepo, but I don't think that has anything to do with it because it seems broken no matter where I put the vars and regardless of what I set `svelte.config.js`'s `config.kit.env.dir` to.

```sh
error when starting dev server:
Error: Missing PUBLIC_GRAPHQL_URL env var.
    at apiUrl (...monorepo/frontend/houdini.config.js:8:10)
```

**Comment by AlecAivazis** [comment]
Hey @iolyd - what version of houdini are you using?

**Comment by iolyd** [comment]
Freshly installed `0.20.4`. (Since I'm just setting houdini and graphql up, I suspect it could also be due to some error on my part.)

**Comment by AlecAivazis** [comment]
SO by default, vite only loads environment variables starting with `VITE_` - could you try adding that?

**Comment by iolyd** [comment]
Problem persists if I prefix env vars with the default `VITE_`, no matter if I remove my custom svelte.config's `env.publicPrefix` or set it to `VITE`.

**Comment by AlecAivazis** [comment]
Hm, that's strange. I'll try to find some time soon to dig into this. [Here](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/plugin/index.ts#L174-L187) is where the env loading logic is defined in case you can see anything.

**Comment by iolyd** [comment]
If I'm reading right, I don't think the path is valid? Shouldn't it be [`svelte_kit_cfg.kit?.env.dir`](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/plugin/index.ts#L174-L187) instead of `svelte_kit_cfg.kit?.dir` ? But even then, it should fallback to `.` yet somehow it still fails.

**Comment by eikaramba** [comment]
unfortunately this problem persists with latest houdini and sveltekit. upon running sveltekit the env variables from VITE are not there. only after generating runtime they appear. i am currently trying to debug it to collect more infos

**Comment by jycouet** [comment]
Are you sure you are using `env:YOUR_ENV` or the function and not importing from `$env/static/...`?

**Comment by eikaramba** [comment]
yes i am using the function. as i said after generating the runtime it works. funny enough it seems to not be a problem that the first call of the function does not include the variables from VITE.
