### ISSUE TITLE
Houdini doesn't work with new TS v4.9 satisfies operator

### ISSUE THREAD

**Issue by 524c** [HoudiniGraphql/houdini#765]
### Describe the bug

The Sveltekit generate TS with new `satisfies operator` since this [PR](https://github.com/sveltejs/kit/pull/8001).

I updated my code `hooks.server.ts` to use this, [like this example](https://kit.svelte.dev/docs/hooks#server-hooks), and I get an error.

The output after running the `houdini generate -v` command and updating my `hooks.server.ts` to use this new operator:
```
❌ Encountered error in src/hooks.server.ts
    at file:///devel/.local/share/pnpm/global/5/.pnpm/houdini@0.18.1/node_modules/houdini/build/cmd-esm/index.js:76213:15
    at async Promise.all (index 2)
    at async collectDocuments (file:///devel/.local/share/pnpm/global/5/.pnpm/houdini@0.18.1/node_modules/houdini/build/cmd-esm/index.js:76188:3)
    at async compile (file:///devel/.local/share/pnpm/global/5/.pnpm/houdini@0.18.1/node_modules/houdini/build/cmd-esm/index.js:76080:21)
    at async Command2.generate 
(file:///devel/.local/share/pnpm/global/5/.pnpm/houdini@0.18.1/node_modules/houdini/build/cmd-esm/index.js:76375:5)
```

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

It is possible to use `houdini/e2e/sveltekit` to reproduce the error, and then:

update the src/hooks.server.ts with with this code:
```typescript
import { setSession } from '$houdini';
import type { Handle } from '@sveltejs/kit';

export const handle = (async ({ event, resolve }) => {
  // set the session information for this event
  setSession(event, { user: { token: '1234-Houdini-Token-5678' } });

  // pass the event onto the default handle
  return await resolve(event);
}) satisfies Handle;
```

then run `houdini generate -v`

**Comment by AlecAivazis** [comment]
Oh damn! Good catch. So this happens [here](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini/src/lib/parse.ts). Do you have the time to hunt down the latest version of `@babel/parser` and bumping the version to support this?

**Comment by 524c** [comment]
OK good. I'll look into that and submit a PR 👍
