### ISSUE TITLE
Houdini init nukes existing svelte.config.js and ignores vite.config.js

### ISSUE THREAD

**Issue by SeppahBaws** [HoudiniGraphql/houdini#782]
### Describe the bug

When running `npx houdini init` on our project, it discards the existing options in `svelte.config.js` and replaces everything with its own minimal setup.

houdini version used: 0.18.3

### Severity

annoyance

### Steps to Reproduce the Bug

1. clone the reproduction repo
2. enter the nuke-svelte-config folder
3. take note of the `prerender` option in the `svelte.config.js` file
4. run `npm install`
5. run `npx houdini generate`
6. see the contents of `svelte.config.js` file have been replaced, and the `prerender` option is gone.

### Reproduction

https://github.com/SeppahBaws/houdini-issues/tree/main/nuke-svelte-config

**Comment by AlecAivazis** [comment]
Yes, unforunately this is how the script works which is why we ask you to have your project committed. I know its slightly annoying but its best way for us to balance maintaining the script as things change.

**Comment by SeppahBaws** [comment]
Ah okay I see, fair enough! 😄

**Comment by AlecAivazis** [comment]
Thanks for understanding!
