### ISSUE TITLE
Respect "useTabs" and "tabWidth" setting in Prettier configuration

### ISSUE THREAD

**Issue by bivainis** [HoudiniGraphql/houdini#805]
### Describe the feature

If a project is set to use spaces instead of tabs and `houdini-init` is run, then it would be nice that the generated configuration files would be consistent with the project, especially if they overwrite the old files.

### Criticality

cool improvement, my projects will benefit from it

**Comment by AlecAivazis** [comment]
Seems like the easiest way to pull this off would be to run prettier after `init` has done its thing. If you wanted to submit a PR, i would gladly review it!

**Comment by AlecAivazis** [comment]
After talking with the rest of the maintainers, we've decided that this would introduce a lot of complexity in the `init` command with little payoff. Most users/projects that want to enforce prettier's styling will have an easier time executing the correct thing than we would if we try to execute it by hand.
