### ISSUE TITLE
Bug: SvelteKit build in node docker image fails - Cannot find module './$houdini'

### ISSUE THREAD

**Issue by marcbinz** [HoudiniGraphql/houdini#817]
### Describe the bug

Hello 👋 

When trying to build our SvelteKit application with a Dockerfile for deployment on the server, we currently receive an error when running the step `svelte-check`: "Error: Cannot find module './$houdini' or its corresponding type declarations. (ts)". Removing this step from the Dockerfile leads to an successful build, but then the application breaks during runtime: "Undefined property pageInfo" (using a pagination setup here).

After quite a lot of debugging, I figured out that the `houdini generate` command does not write all of the necessary files. Within the generated `$houdini` folder, the path `types/src/routes` is empty, where it should actually create all of the `.d.ts` files describing the available data for each page. On the other hand, the `$houdini/artifacts` folder is filled correctly. Why those files have not been written remains unknown. The standard SvelteKit type files (`.svelte-kit/types/src/routes/...`) are generated properly.

This issue only occurs when building the application in the environment of the node image. On my local system (macOS) there is no such issue. We make use of groups in the folder-based router (e.g. `src/routes/(protected)/articles/+page.svelte` and thought this might be an issue, but a route such as `src/routes/api/...` is not processed as well.

I hope my explanations above clarify the issue properly. If there is any other information required for debugging and analysis, please just let me know!

Any help in fixing this issue is very much appreciated 🙏  Thanks!

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

1. Setup houdini with SvelteKit as per the official documentation.
2. Create a Dockerfile to build the product using the official node docker image.
3. Run `svelte-check` as part of the process to detect this error early on (otherwise it would come up at runtime).
4. Tested with all recent versions of houdini and houdini-svelte (0.18.0 -> 1.0.0-next.1).

**Comment by marcbinz** [comment]
Here is the relevant part of our current Dockerfile:

```Dockerfile
FROM node:18.13.0 as build

# Copy all source files needed for the build.
COPY frontend /src/frontend

# Change into the correct working directory.
WORKDIR /src/frontend

# Download & install NPM dependencies.
RUN npm ci --frozen-lockfile

# Generate all required source files (especially for the GraphQL API).
RUN npm run gen # <-- this runs 'houdini generate'

# Lint and check types.
RUN npm run lint && npm run check # <-- this is the step where it breaks

# Compile the application.
RUN npm run build
```

We also tried different versions of the node image itself. When checking the contents of the `/src/frontend` folder after the step `RUN npm run gen`, the `$houdini` folder exists, but with an empty `types/src/routes` folder as described in the issue summary above.

**Comment by jycouet** [comment]
I think that you can remove completely: `npm run gen` (it was the "old" workflow, now the vite plugin handles it for you). 

So, `npm run build` should do the generate for you in the background.
You would need to do this step before `RUN npm run lint && npm run check`

Let me know if it's better.

**Comment by marcbinz** [comment]
Hey @jycouet, thanks for the quick response 😀

I kind of tried a similar approach already by using my local `$houdini` folder for the docker build (removing it from `.dockerignore`, so it gets loaded into the docker build process). I then removed the generate step, as the files are already there:

```Dockerfile
...

# Lint and check types.
RUN npm run lint && npm run check

# Compile the application.
RUN npm run build
```

Here the build is successful, but the "undefined" error as described above was still coming up at runtime. I then checked the contents of the `$houdini` folder after the build and noticed that the generation killed the files at `$houdini/types/src/routes` as well, leading to the same issue once more 😬

**Comment by jycouet** [comment]
Maybe I'm missing something 😬

Can you keep `$houdini` in ignore, we don't need these files.
And try this order 👇
```Dockerfile
# Compile the application.
RUN npm run build

# Lint and check types.
RUN npm run lint && npm run check
```

**Comment by marcbinz** [comment]
Oh sorry, I should have mentioned that I tried it with this order as well and got the same result 😬

**Comment by marcbinz** [comment]
So, I tried running the e2e example, but to be honest did not get it to work properly. The workspace versioning is what troubles me, I have not yet worked with that before.. 😬 

Here is the full Dockerfile:

```Dockerfile
# syntax=docker/dockerfile:1

FROM node:18.13.0-alpine as base

# Update NPM itself to the latest version.
RUN npm -g i npm


FROM base as build

# Copy all source files needed for the build.
COPY frontend /src/frontend

# Change into the correct working directory.
WORKDIR /src/frontend

# Download & install NPM dependencies.
RUN npm ci --frozen-lockfile

# Compile the application.
RUN npm run build

# Lint and check types.
RUN npm run lint && npm run check


FROM base as runtime

# Switch to the runtime directory for the application.
WORKDIR /app
RUN rm -rf ./*

# Copy the compiled files to the final image.
COPY --from=build /src/frontend/build .
COPY --from=build /src/frontend/package.json .
COPY --from=build /src/frontend/package-lock.json .

# Install production dependencies.
RUN npm ci --omit=dev --frozen-lockfile --ignore-scripts

# Run the image as a custom non-root user.
USER node

# Tells docker that the container listens on the specified network port at runtime.
# This is the default as defined by the application itself.
EXPOSE 3000

# Command to be used to execute when the image is used to start a container.
CMD [ "node", "index.js" ]

```

And the command to run it: `docker build -t app:latest -f ./Dockerfile .`

**Comment by AlecAivazis** [comment]
Okay, so after poking around a bit I think I have uncovered the issue. Unfortunately its a bit tricky to verify that it will work without just deploying a new version with something I _think_ would fix it which I'd rather not do until we confirm. Would you be willing to reach out to me on discord so we can try a few things?

**Comment by AlecAivazis** [comment]
Okay,  #820 should fix this. I'm able to build the docker file above 🎉

**Comment by marcbinz** [comment]
Hey, I updated to the new patch release and the build is running smoothly 😀

Just wanted to say thanks for the quick resolution of the issue! I really appreciate it 🙏

**Comment by AlecAivazis** [comment]
Fantastic! Thanks for confirming 🙌
