### ISSUE TITLE
"Class extends value undefined is not a constructor or null" when using custom stores and more than one store

### ISSUE THREAD

**Issue by sistrall** [HoudiniGraphql/houdini#818]
### Describe the bug

Hi!

I'm using Houdini, and I'm actually impressed by the quality of the library and by the ideas behind it.

I think I spot a bug while trying to use custom stores on a SvelteKit project: I want to inherit a custom store from `QueryStore`, and it actually works... but **only with a single query: when I add more queries and more stores are generated**, I receive the following error:

```
Class extends value undefined is not a constructor or null
TypeError: Class extends value undefined is not a constructor or null
    at /$houdini/plugins/houdini-svelte/stores/Countries.js:4:37
    at async instantiateModule (./node_modules/vite/dist/node/chunks/dep-5e7f419b.js:52224:9)
```

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

Clone the repo at https://github.com/sistrall/houdini-breaks-with-custom-stores and start SvelteKit with `npm run dev`.

### Reproduction

https://stackblitz.com/github/sistrall/houdini-breaks-with-custom-stores

**Comment by AlecAivazis** [comment]
Whoa super cool to hear someone is actually using this! It was added to the API so I could experiment with stuff in the wild. I'd love to hear more about what you're trying to do with it.

Anyway, I pulled down your project and it looks like the problem is a circular dependency issue. If I change the update in your custom store to 

```
import { QueryStore } from '$houdini/plugins/houdini-svelte/runtime';
```

It seems to run. I'll see what I can do with the import orders to make these resolve 👍

**Comment by AlecAivazis** [comment]
Hm, i'm not finding a good way to address the cycle in the import. It doesn't seem to matter if I shift the `export` declaration around. Maybe you can figure out something now that we know the problem? I'd gladly review a PR with a fix if its possible

**Comment by sistrall** [comment]
Hi @AlecAivazis :-)

Nice to meet you!

> Whoa super cool to hear someone is actually using this! It was added to the API, so I could experiment with stuff in the wild. I'd love to hear more about what you're trying to do with it.

I'm working for [DatoCMS](https://www.datocms.com/), and these days we're improving our support for Svelte: so I built [a simple demo](https://github.com/datocms/sveltekit-demo) that — of course — uses Houdini. Then, I added the support for previewing draft contents when I found the problem.

Previews are pretty useful: you edit content in DatoCMS, and you immediately see the result on the page. To do that, I want to leverage our Real-time Updates API via the [datocms-listen](https://github.com/datocms/datocms-listen) package. So, I though to inherit all the stores from a custom store that supports the preview feature.

> Maybe you can figure out something now that we know the problem?

Mmh, I don't know: despite the years in the JS ecosystem, I keep feeling like a newbie with this kind of intricacy. I'll try, though. At the moment, though, your fix is enough to move on: thank you very much for being so reactive!

**Comment by sistrall** [comment]
Hello again @AlecAivazis :-)

Since you were curious to know, [here is the PR](https://github.com/datocms/sveltekit-demo/pull/1) that implements support for previews on SvelteKit, based on custom stores.

I also created [a small PR on Houdini](https://github.com/HoudiniGraphql/houdini/pull/835) to solve an issue with custom stores configuration.
