### ISSUE TITLE
❌ Syntax Error: Expected "{", found "...".

### ISSUE THREAD

**Issue by el-schneider** [HoudiniGraphql/houdini#819]
### Describe the bug

it's happening after updating from 17 to anything higher

```
🎩 Generating runtime...
❌ Syntax Error: Expected "{", found "...".
```

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

Just running `npm run dev`

I'm using queries, that look like below, and the union types might be the problem here,

```gql
query Projects {
	entries(collection: "projects", sort: "order asc") {
		data {
			... on Entry_Projects_Project {
				...ProjectsFragment
			}
		}
	}
}
```

**Comment by jycouet** [comment]
I just tried a fragment in a union with the latest Houdini package, and it's working well.

It's a bit hard to help without the schema & fragment definition.
Could you provide more details?

**Comment by AlecAivazis** [comment]
@el-schneider any update?

**Comment by el-schneider** [comment]
Sorry for not getting back to you earlier. I was caught up in other stuff. I just sent you an invite to a minimal reproduction of the issue with the API I'm using.

**Comment by AlecAivazis** [comment]
Ah wonderful! I was able to reproduce the issue. I'll try to have something out in the next few days

**Comment by AlecAivazis** [comment]
Well that was easier than I thought. It's getting late so I want to give it a quick look over with fresh eyes when i wake up. Will merge in the morning 👍

**Comment by AlecAivazis** [comment]
This should now be fixed in `v0.20.3`. Let me know if the problem still persists!

**Comment by el-schneider** [comment]
Thank you for your effort. It's working now!

**Comment by AlecAivazis** [comment]
Awesome! thanks for being patient
