### ISSUE TITLE
Errors in bidirectional cursor-based pagination

### ISSUE THREAD

**Issue by samuel-utbult-oborgen** [HoudiniGraphql/houdini#824]
### Describe the feature

How would you know in which end of a list an error occured when #670 is implemented? I have a custom implementation of bidirectional cursor-based pagination where a "try again"-button is shown on either the start or the end of the list, which the users can press to refetch the query that caused an error. However, this logic needs to know where the error occurred. I have three possible cases in my implementation:

1. The error occurs during the initial loading.
2. The error occurs when loading the previous page.
3. The error occurs when loading the next page.

It would be useful to get some kind of signal about where the error occurred when bidirectional cursor-based pagination is implemented.

### Criticality

cool improvement, my projects will benefit from it

**Comment by AlecAivazis** [comment]
Hey @samuel-utbult-oborgen! Mind adding this to #670 so we can keep all of the conversation in one place? I really appreciate the thoughts. I'll try to find some time over the next few days to go through everything you've written and post a summary for how I imagine this being implemented in #670
