### ISSUE TITLE
Error: Could not find referenced fragment definition: FragmentName

### ISSUE THREAD

**Issue by el-schneider** [HoudiniGraphql/houdini#840]
### Describe the bug

Sometimes existing fragments don't seem to be processed early enough. When I `run build` twice, it often  – but not reliably – works. It seems to only happen when there are a couple more fragments

@AlecAivazis: I updated the reproduction from https://github.com/HoudiniGraphql/houdini/issues/819 with a bunch of other queries and fragments from my project. Maybe you can reproduce it like this? A slug you could use for testing is: `etcetera`

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

just try to build it

**Comment by AlecAivazis** [comment]
I'll try to find some time soon to look at this

**Comment by AlecAivazis** [comment]
So I was able to reproduce your issue but it seems to be gone in the release candidate for `1.0`. Could you confirm for me? You can install the latest using `houdini@next` and `houdini-svelte@next`

**Comment by el-schneider** [comment]
I can confirm, that after updating, the error is gone. Great work! Thank you
