### ISSUE TITLE
client not getting session data for mutate call

### ISSUE THREAD

**Issue by xmlking** [HoudiniGraphql/houdini#844]
### Describe the bug

for **fetch** call, I am getting _session_ data as expected

<img width="640" alt="image" src="https://user-images.githubusercontent.com/627951/214209577-16ade0fa-17f8-4d48-9f48-09421e4e6225.png">

But, for **mutate** call,  same client not printing  the _session_ data

<img width="640" alt="image" src="https://user-images.githubusercontent.com/627951/214209795-21faab3b-a10f-4c91-be62-e8b0e4ed5e0f.png">

My [client](https://github.com/xmlking/svelte-starter-kit/blob/main/src/lib/graphql/client.ts#L14-L19)
[hook](https://github.com/xmlking/svelte-starter-kit/blob/main/src/lib/server/middleware/houdini.ts#L18) where I set token into session. 

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

https://github.com/xmlking/svelte-starter-kit

### Reproduction

https://xmlking@github.com/xmlking/svelte-starter-kit.git

**Comment by AlecAivazis** [comment]
hey @xmlking 👋 

I found some time today to dig into this and the issue is that you are on the server so the normal session injection isn't working. Atm there's no way to pass the `event` to the mutation so that it can be picked up like it is for queries. I'll make sure this is fixed for `1.0`

**Comment by AlecAivazis** [comment]
#847 adds an `event` field to `mutate`'s second argument that you can pass to get `fetch` and `session` injected correctly

**Comment by xmlking** [comment]
@AlecAivazis awesome! thanks a lot for your quick support.
