### ISSUE TITLE
[ERROR] Could not resolve "HOUDINI_CONFIG_PATH"

### ISSUE THREAD

**Issue by neoel** [HoudiniGraphql/houdini#854]
### Describe the bug

Suddenly getting this error: 

```✘ [ERROR] Could not resolve "HOUDINI_CONFIG_PATH"

    node_modules/.pnpm/houdini@0.20.3/node_modules/houdini/build/lib-esm/index.js:61460:43:
      61460 │   return defaultConfigValues((await import("HOUDINI_CONFIG_PATH")).default);
            ╵                                            ~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "HOUDINI_CONFIG_PATH" as external to exclude it from the bundle, which will
  remove this error. You can also add ".catch()" here to handle this failure at run-time instead of
  bundle-time.

10:53:26 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.pnpm/houdini@0.20.3/node_modules/houdini/build/lib-esm/index.js:61460:43: ERROR: Could not resolve "HOUDINI_CONFIG_PATH"
    at failureErrorWithLog (/home/dexter/Projects/wolbodo/members/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1604:15)
    at /home/dexter/Projects/wolbodo/members/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1056:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Unsure what triggered it and how to fix it.

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

The code is available on https://github.com/wolbodo/members/tree/svelte-kit%40v1

Its being triggered just by setting up the app and running `pnpm run dev`

**Comment by jycouet** [comment]
I see that you have a `package-lock.json` with version 0.13 and a `pnpm-lock.yaml` with version 0.20
Could you remove node_modules and select npm or pnpm (deleting the other lock file?)

Restart & let us know?

**Comment by AlecAivazis** [comment]
Fwiw, this import has been drastically redesigned so it should be a lot smoother in `1.0.0`

**Comment by neoel** [comment]
I removed the import and updated 0.20.4, it now doesn't crash the app, but still shows the error. 
As I'm upgrading this project to svelte-kit@1 and all dependencies. I'll check out houdini@1 too 

Really dig the changes so far (coming from 0.13), so nice I can drop the custom serverside querying with graphql-request.

**Comment by AlecAivazis** [comment]
I'm going to close this since we know the issue 👍
