### ISSUE TITLE
Unexpected partial result

### ISSUE THREAD

**Issue by fehnomenal** [HoudiniGraphql/houdini#878]
### Describe the bug

I'm still in the upgrading process and got to a breaking change.

I have a cart page and a checkout page. Both pages load similar data about the cart:

```gql
# .../cart/+page.gql
query GetMyCartItems {
  activeCart {
    id

    items {
      id
      amount
      product {
        id
        name
        brand
        availableStock # different
        price
      }
    }
  }
}
```

```gql
# .../checkout/+layout.gql
query GetCartForCheckout {
  activeCart {
    id

    items {
      id
      amount
      product {
        id
        name
        brand
        price
        taxRate # different
      }
    }
  }
}
```

As you can see the documents only differ in `avalableStock` and `taxRate`. I would expect (as this was the case in the ancient version of 0.15) that on client side navigation the other query is executed because data is missing in the cache.
And indeed this is true for the cart->checkout navigation.

But going back after a F5 reload breaks (I destructure the `items` on the cart page) as I only get a partial result. I printed the store contents on both pages and the cart prints `partial: true` and `items: [ null ]`. `source: "cache"` after navigation regardless of direction.

Setting `defaultPartial: false` or adding `@cache(partial: false)` has no effect (as I expected because partal data should be opt-in, right?).

Could the problem be that one generates a layout load?

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

I will try to whip something up...

**Comment by AlecAivazis** [comment]
Hm okay, so it sounds like the new stuff is ignoring the partial flag and including it anyway? I'll take a look 👍. Don't worry about the reproduction just yet. If I'm struggling to see it then we can worry about it

**Comment by AlecAivazis** [comment]
hm okay yea i took a quick look and the plugin _should_ be respecting the `partial` value in your artifact. Can you check in `$houdini/artifacts/GetMyCartItems.js` that it's set to false?

**Comment by AlecAivazis** [comment]
Oh! I think I have a hunch what's causing this but rather than just shooting blind I'd like to wait til we have a reliable reproduction. I'll try to make one in the e2e tests

**Comment by AlecAivazis** [comment]
Oh! I think I have a hunch what's causing this but rather than just shooting blind I'd like to wait til we have a reliable reproduction. I'll try to make one in the e2e tests

**Comment by AlecAivazis** [comment]
Mind giving `1.0.0-next.12` a shot?

**Comment by fehnomenal** [comment]
Works like a charm. I love it :heart:
