### ISSUE TITLE
pagination loadNextPage not passing auth headers to backend

### ISSUE THREAD

**Issue by xmlking** [HoudiniGraphql/houdini#888]
### For "Load More" button,   it is not passing headers. i.e.. `fetchParams` in client is not getting invoked.

 
<img width="1015" alt="Screen Shot 2023-02-02 at 3 33 13 PM" src="https://user-images.githubusercontent.com/627951/216474743-2bd19b15-6714-413c-9ab5-cf2926d9de6b.png">

### For "Refresh" button, it is passing headers as coded in the **client**
<img width="930" alt="Screen Shot 2023-02-02 at 3 24 13 PM" src="https://user-images.githubusercontent.com/627951/216473745-19c354c2-5fcb-4d96-881b-7b50f86cbae3.png">

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

https://github.com/xmlking/svelte-starter-kit/blob/main/src/routes/(play)/play/houdini/%2Bpage.svelte

### Reproduction

https://github.com/xmlking/svelte-starter-kit/blob/main/src/routes/(play)/play/houdini/%2Bpage.svelte

**Comment by xmlking** [comment]
due to missing auth token I am getting backed error 
```json
{"errors":[{"extensions":{"code":"validation-failed","path":"$.selectionSet.tz_policies"},"message":"field 'tz_policies' not found in type: 'query_root'"}]}
```

**Comment by AlecAivazis** [comment]
Thanks for reporting this! I'll take a look tonight 👍

**Comment by AlecAivazis** [comment]
This should be fixed in `next.14`
