### ISSUE TITLE
LoadInput Type generation incorrect

### ISSUE THREAD

**Issue by sjcobb2022** [HoudiniGraphql/houdini#916]
### Describe the bug

If there is both a page and a layout query, the type generation creates 2 separate types for the LoadInput value.

This is due to the houdini-svelte codegen plugin. 

https://github.com/HoudiniGraphql/houdini/blob/f535af8de5838722888de944ca4a21d7450f0b8e/packages/houdini-svelte/src/plugin/codegen/routes/index.ts#L185

### Severity

annoyance

### Steps to Reproduce the Bug

1. Initialize a project
2. Have both a layout load and page load queries with inputs
3. Generated see generated load input incorrect

**Comment by AlecAivazis** [comment]
👋 Thanks for reporting this! Do you have the time to get a fix out?

**Comment by sjcobb2022** [comment]
> wave Thanks for reporting this! Do you have the time to get a fix out?

Fix incoming! just a single line change.
