### ISSUE TITLE
Cannot fetch schema with cookie authentication

### ISSUE THREAD

**Issue by yaroslavros** [HoudiniGraphql/houdini#926]
### Describe the bug

Cookie authentication always fails when fetching schema because cookie header value contains "=" and it is getting lost due to `header.split("=")`

Replacing `header.split("=")` with `header.split(/=(.*)/s)` in cmd/pullSchema.ts and cmd/init.ts fixes the issue

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

Attempt to use init or pull-schema against graphql API that uses Cookie authentication or any other header containing "="

**Comment by AlecAivazis** [comment]
hey @yaroslavros! Thanks for finding the fix - mind submitting a PR?

**Comment by AlecAivazis** [comment]
Thanks again for submitting the fix!
