### ISSUE TITLE
Argument of type 'RequestHandler<any>' is not assignable to parameter of type 'ConstructorArgs'

### ISSUE THREAD

**Issue by chornbec** [HoudiniGraphql/houdini#930]
### Describe the bug

My system:
- Operating system: `Windows 10 x64`
- Houdini version: `1.0.1`
- Svelte version: `3.47.0`
- Vite version: `4.0.3`
- Plugins: `houdini-svelte v1.0.1`

Not really a bug, but the documentation on the Authentication [page](https://www.houdinigraphql.com/guides/authentication) might be outdated.

The page has the following snippet:

```ts
import { HoudiniClient } from '$houdini'
import type { RequestHandler } from '$houdini'

const requestHandler: RequestHandler = async ({ fetch, text, variables = {}, session }) => {
    const url = 'http://localhost:4000/graphql'
    const result = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${session?.user.token}`
        },
        body: JSON.stringify({
            query: text,
            variables
        })
    })

    return await result.json()
}

export default new HoudiniClient(requestHandler)
```

There's two issues I'm encountering:
1. `RequestHandler` type is not found in `$houdini`. Intellisense is saying `RequestHandler` is in `$houdini/plugins` (which just does `export * from '../runtime/client/plugins'`)
2. I get a Typescript error saying `Argument of type 'RequestHandler<any>' is not assignable to parameter of type 'ConstructorArgs'` because `HoudiniClient` accepts an arg of type `ConstructorArgs` and not `RequestHandler`.

I'm not sure what's up with # 1, but # 2 can be solved by just updating the Authentication page with the new implementation. I see this recent [commit](https://github.com/HoudiniGraphql/houdini/commit/7e2977ff5f1e737aebbb606e473708036f303d02) introduced `ConstructorArgs`.

### Severity

annoyance

### Steps to Reproduce the Bug

(following the KitQL [docs](https://www.kitql.dev/docs/all-in))
1. Create demo Sveltekit app
2. Install Houdini
3. Follow Houdini Authentication [guide](https://www.houdinigraphql.com/guides/authentication) to create a `client.ts` file for the `HoudiniClient`
4. See the following Typescript errors reflecting issues # 1 and # 2 mentioned in the bug description:
    1. `Module '"$houdini"' has no exported member 'RequestHandler'`
    2. `Argument of type 'RequestHandler<any>' is not assignable to parameter of type 'ConstructorArgs'`

**Comment by AlecAivazis** [comment]
Oh whoops! Thanks for reporting this - I'll update the docs now. 

The file should look like this:
```typescript
import { HoudiniClient } from '$houdini'

export default new HoudiniClient({
    url: 'http://localhost:4000/graphql',
    fetchParams({ session }) {
        return { 
            headers: { 
                Authorization: `Bearer ${session?.user.token}`,
            }
        }
    }
})
```
