### ISSUE TITLE
HTTP Errors from fetches in loaders don't trigger Sveltekit's handleErrors hook

### ISSUE THREAD

**Issue by fnimick** [HoudiniGraphql/houdini#942]
### Describe the bug

I'm not sure if this is a Sveltekit or Houdini issue to be honest - but errors that are triggered in Houdini loads don't result in the Sveltekit `handleError` hook being called.

In my case, this is for a fetch being triggered via manual loading as described in https://www.houdinigraphql.com/api/query#manual-loading .

The offending code:
```
export async function load(event: LayoutServerLoadEvent) {
  const Shared = new SharedStore();
  try {
    const result = await Shared.fetch({ event });
  } catch (error) {
    console.error(error);
    throw error;
  }
}
```

This correctly reports an error occurring in the fetch call:
```
HttpError {
  status: 500,
  body: { message: 'ERROR: An unknown error occurred.' }
}
```

However, my handleError function in `hooks.server.ts` is never called:
```
export const handleError: HandleServerError = async ({ event, error }) => {
  console.log("test handleError");
  console.error(error);
};
```

When discussing with Sveltekit they suggested that this is due to something in Houdini's error handling, as throwing an error manually in my loader in the same place results in the `handleError` hook being correctly called.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

Make a graphql request in a loader that results in a 500 error from the graphql server.

**Comment by jycouet** [comment]
By default, errors are now `quiet`.
To check could you log `result` and see what's in there?
And do something if result.data is null for example.

You can also go back to `throwOnError` as described here https://www.houdinigraphql.com/guides/release-notes#100 in the section Error handling.

Let us know

**Comment by fnimick** [comment]
@jycouet thank you! I hadn't updated to 1.x yet.

Using the `throwOnError` as described doesn't work for this use case due to sveltekit `error` not triggering `handleError` logic (e.g. for sentry logging) - however, returning an Error object does. Do you see any issues with returning an Error object rather than using the error function?

**Comment by AlecAivazis** [comment]
Hey @fnimick! There shouldn't be any issues with that if you're seeing the behavior you want.

I'm going to close this since the conversation seems to have come to a natural conclusion but let me know if there's anything else we need to do
