### ISSUE TITLE
@include and @skip directives don't generate nullable TypeScript types

### ISSUE THREAD

**Issue by SeppahBaws** [HoudiniGraphql/houdini#945]
### Describe the bug

Upon generating typings for a query with `@include` and `@skip` directives in it, Houdini doesn't generate these types as nullable.

For this simple query:
```gql
query MyTestQuery($sayHello: Boolean!) {
  hello @include(if: $sayHello)
  user(id: "1", snapshot: "my-user") {
    id
    name
  }
}
```

Houdini generates this type:
```ts
export type MyTestQuery$result = {
    readonly hello: string;
    readonly user: {
        readonly id: string;
        readonly name: string;
    };
};
```

However, if `$sayHello` is set to false, the api will return an object without that field, and in the `$store.data` object, that field will contain `undefined`. But the types don't reflect this, which can lead to confusion. I would expect that the `hello` field in this case would look something like this:
```diff
export type MyTestQuery$result = {
-     readonly hello: string;
+     readonly hello: string | undefined;
    readonly user: {
```

My personal choice would be to use `string | undefined`, because that's what JavaScript will populate that object with by default. Making it `string | null` would lead to weird bugs with `!== null` checking, when the actual data would be `undefined`.

### Severity

annoyance

### Steps to Reproduce the Bug

1. paste the example query in a test project
2. run `houdini generate`
3. observe the `hello` field to be not nullable
4. if you run this query, you will see that the `hello` field will contain `undefined`

**Comment by AlecAivazis** [comment]
ohhh good point! i think you're right that `| undefined` is the right move 👍 [Here](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini/src/codegen/generators/typescript/inlineType.ts) is where that logic lives if you or someone else wants to pick this up.

**Comment by SeppahBaws** [comment]
I can try to take a look at it this weekend 🙂
