### ISSUE TITLE
Bring back the ability to use a completely different fetch in the client

### ISSUE THREAD

**Issue by ascclemens** [HoudiniGraphql/houdini#953]
### Describe the feature

I'm making a [Tauri](https://tauri.app) app with a Svelte + Houdini frontend. 1.0 has removed the ability for me to use Tauri's fetch function in an easy way.

Previously, I could do something like this:
```ts
import { HoudiniClient, type RequestHandlerArgs } from '$houdini';
import { Body, fetch } from '@tauri-apps/api/http';
import { get } from 'svelte/store';
import { authToken } from '$lib/stores';

async function fetchQuery(args: RequestHandlerArgs) {
    const {
        text = '',
        variables = {},
    } = args;

    const headers: Record<string, string> = {
        'Content-Type': 'application/json',
    };

    const auth = get(authToken);
    if (auth) {
        headers['x-auth-token'] = auth;
    }

    const url = '...';
    const result = await fetch(url, {
        method: 'POST',
        headers,
        body: Body.json({
            query: text,
            variables,
        }),
    });

    return result.data as any;
}

export default new HoudiniClient(fetchQuery);
```

This worked great. The `fetch` function provided by Tauri is not really compatible with the `fetch` function provided by the browser. Their signatures are incompatible, and a wrapper function between them is messy and unfun, so this makes setting `ctx.fetch` in a client plugin extremely difficult.

This `fetch` function from Tauri uses the Rust backend's HTTP stack, and it critically doesn't require CORS headers. My entire application relies on being able to use this function, so I can't use 1.0 at all with this change!

It would be great if there could be a way to easily do something like this again. Or perhaps there is and I've just missed it!

### Criticality

waiting for it to switch all my project to Houdini

**Comment by AlecAivazis** [comment]
Hey @ascclemens! 

You should be able to pass your own fetch plugin to your client in order to customize the logic. You can either define it yourself for ultimate control or you can use the `fetch` plugin factory that's exported from `$houdini/plugins`. From your example, it would probably look something like:

```typescript
import { HoudiniClient } from '$houdini'
import { fetch as houdiniFetchPlugin } from '$houdini/plugins'
import { Body, fetch } from '@tauri-apps/api/http';
import { get } from 'svelte/store';
import { authToken } from '$lib/stores';

async function fetchQuery(args: RequestHandlerArgs) {
    const {
        text = '',
        variables = {},
    } = args;

    const headers: Record<string, string> = {
        'Content-Type': 'application/json',
    };

    const auth = get(authToken);
    if (auth) {
        headers['x-auth-token'] = auth;
    }

    return  await fetch('...', {
        method: 'POST',
        headers,
        body: Body.json({
            query: text,
            variables,
        }),
    });
}


export default new HoudiniClient({
    url: "...",
    plugins: [ houdiniFetchPlugin(fetchQuery) ]
})
```

If you'd rather build your own fetch implementation, you can look at the body of the factory for inspiration which is located [here](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini/src/runtime/client/plugins/fetch.ts).

**Comment by ascclemens** [comment]
Wow, thank you so much. I didn't realise there even *was* a fetch plugin you could use like that even after reading the docs. It works fine like that!
