### ISSUE TITLE
Website down? 

### ISSUE THREAD

**Issue by douglasward** [HoudiniGraphql/houdini#967]
### Describe the bug

When opening https://www.houdinigraphql.com/ I get the following error message

<img width="560" alt="Screenshot 2023-03-03 at 09 59 42" src="https://user-images.githubusercontent.com/8439137/222677288-27aa59e7-c18d-46a2-affc-e094636ff512.png">

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

go to https://www.houdinigraphql.com/

### Reproduction

https://www.houdinigraphql.com/

**Comment by AlecAivazis** [comment]
Ah damn. Thanks for the heads up. I'll work on getting it back now 👍

**Comment by AlecAivazis** [comment]
Should be back now
