### ISSUE TITLE
acceptImperativeInstability console warning even if enabled

### ISSUE THREAD

**Issue by wattsjs** [HoudiniGraphql/houdini#973]
### Describe the bug

I'm still getting the warning of `The imperative cache API is considered unstable and will change in any minor version release Please acknowledge this by setting acceptImperativeInstability to true in your config file.`, even if i set this in my config file.

I'm using the cache for a fast updating subscription and so it's causing this to be logged to the console repeatedly.

Is this something I'm doing wrong on my end?

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. Use the `cache` api
2. See the warning

**Comment by wattsjs** [comment]
Should be easy to see in the E2E tests but a small recreation here: https://stackblitz.com/edit/sveltejs-kit-template-default-2lmxaj?file=src/routes/+page.svelte

**Comment by AlecAivazis** [comment]
Thanks for reporting this and for the reproduction. I actually wasn't able to see it locally so having the stackblitz was super helpful.

Should have a fix deployed soon

**Comment by wattsjs** [comment]
amazing thank you @AlecAivazis !
