### ISSUE TITLE
Framework detection in monorepo

### ISSUE THREAD

**Issue by rmarscher** [HoudiniGraphql/houdini#977]
### Describe the bug

We have a pnpm monorepo with multiple SvelteKit apps. Houdini, Svelte, SvelteKit and other packages used by all are defined in our top-level workspace package.json and not in each app's package.json.

So that seems to be causing the [framework detection](https://github.com/HoudiniGraphql/houdini/commit/b223c6079bb4a19d5708ad7daf905fe913dbec1e#diff-90d9a9d0bc46f7c17254b07af285124eedc1218243ed7552c4c226abf3c31226R13-R41) to pick 'svelte' as the framework. 

Maybe it could additionally look for `svelte.config.{ts,js}` and set the framework to sveltekit if found? 

Maybe it could also be added as an option to `houdini/ConfigFile` so projects have a way to set it if the automatic detection fails for some other reason?

### Severity

Can be worked around by adding `@sveltejs/kit` to each app's package.json

### Steps to Reproduce the Bug

- Create a pnpm monorepo.
- Create a sveltekit / houdini project in a sub-folder.
- Move the svelte, sveltekit and houdini dependencies to monorepo top-level package.json file.

While the repro is for pnpm, this could happen with other setups.

**Comment by jycouet** [comment]
Thanks for reporting, and sorry for the inconvenience.
Yeah, that makes it hard to have an "auto-detection"!

And if I understand well, your setup you could have this:
```
./apps/prj-kit
./apps/prj-svelte
```

Reading `svelte.config.{ts,js}` is an option by AST but it's quite some code to do & maintain.

The easiest is probably to bring back a setting in `houdini.config.js` defaulting to `kit`.

**Comment by rmarscher** [comment]
Can `svelte.config.js` exist if it's not a kit project? I was thinking you could do a file exists check [like you are doing for pnpm here](https://github.com/HoudiniGraphql/houdini/commit/b223c6079bb4a19d5708ad7daf905fe913dbec1e#diff-90d9a9d0bc46f7c17254b07af285124eedc1218243ed7552c4c226abf3c31226R54-R57) - but if it has to be parsed... than that's not ideal. Instead of parsing, you could maybe just check the contents of the svelte.config.js for "@sveltejs/kit" to detect if it is svelte.kit.

If you brought back a houdini.config.js framework setting... maybe it could default to `undefined` and do auto detection if it is not set.

**Comment by jycouet** [comment]
Yes, in a `svelte` project, you have a `svelte.config.js`.

The more I think about it the more I'm thinking to put back the config. @AlecAivazis, what's your view?
