### ISSUE TITLE
Fragments inside of an `@list` gets set to undefined

### ISSUE THREAD

**Issue by SeppahBaws** [HoudiniGraphql/houdini#991]
### Describe the bug

Using a fragment inside of an `@list` doesn't pass the data in the fragment on to the component consuming the fragment.
However, removing the `@list` makes it pass the fragment data just fine.

the result:
![image](https://user-images.githubusercontent.com/10342829/224971414-9f0a0f55-70f0-445c-a97c-d41330519cc3.png)

+page.gql:
```gql
query ListUsers {
  usersConnection(snapshot: "users-list-fragment") @list(name: "UsersList") {
    edges {
      node {
        name
        ...UserListItem
      }
    }
  }
}
```

+page.svelte:
```svelte
<script lang="ts">
  import type { PageData } from './$houdini';
  import UserItem from './UserItem.svelte';

  export let data: PageData;
  $: ({ ListUsers } = data);
</script>

{#if $ListUsers.data}
  <ul>
    {#each $ListUsers.data.usersConnection.edges as userEdge}
      {@const user = userEdge.node}
      {#if user}
        <UserItem {user} />
      {/if}
    {/each}
  </ul>
{/if}
```

UserItem.svelte:
```svelte
<script lang="ts">
  import { fragment, graphql, type UserListItem } from '$houdini';

  export let user: UserListItem;
  $: data = fragment(
    user,
    graphql(`
      fragment UserListItem on User {
        id
        name
        birthDate
      }
    `)
  );
</script>

{#if $data}
  <li>
    {$data.name} - {$data.birthDate}
  </li>
{/if}
```

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

1. clone the repro codebase on branch `bug-repro/fragment-in-list`
2. run e2e/kit example and go to the `/list-fragment` route
3. see the birthday set as undefined as in the screenshot above
4. remove the `@list` from the +page.gql file
5. now see the birthday being passed along just fine

### Reproduction

https://github.com/SeppahBaws/houdini/tree/bug-repro/fragment-in-list

**Comment by AlecAivazis** [comment]
This should now be fixed in `1.1.1`
